---
permalink: install-ip/concept_considerations_drive_assignment.html 
sidebar: sidebar 
keywords: drive auto-assignment, drive, adp, advanced disk partitioning, root disk, unmirrored root, data partition, root partition, shelf-by-shelf, AFF A320, AFF A220, AFF A250, AFF A300, AFF A400, AFF A700, AFF A800, FAS2750, FAS8200, FAS500f, FAS9000 
summary: 從推出《支援使用ADP的更新系統》（進階磁碟分割）的《支援更新安裝的支援範例ONTAP 》（《支援使用MetroCluster ADP的更新AFF 系統》、《支援更新的安裝程序》、 
---
= 自動指派磁碟機和ONTAP ADP系統的考量事項、位於更新版本的更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從推出《支援使用ADP的更新系統》（進階磁碟分割）的《支援更新安裝的支援範例ONTAP 》（《支援使用MetroCluster ADP的更新AFF 系統》、《支援更新的安裝程序》、在大多數的組態中、分割區和磁碟指派會在MetroCluster 初始設定的站台期間自動執行。

適用於ADP支援的下列變更包含在更新版本中：ONTAP

* 資源池0磁碟指派在原廠完成。
* 無鏡射根目錄是在原廠建立。
* 資料分割區指派是在客戶站台的設定程序期間完成。
* 在大多數情況下、磁碟機指派和分割會在設定程序期間自動完成。



NOTE: 從ONTAP S得9.4升級至9.5時、系統會辨識現有的磁碟指派。



== 自動分割

ADP會在平台初始組態期間自動執行。


NOTE: 從ONTAP 功能更新9.5開始、磁碟的自動指派必須使用命令「shorage disk option modify -autodassign on」來啟用。

安裝期間最多可自動分割96個磁碟機。您可以在初始安裝之後新增額外的磁碟機。



== 機櫃自動指派的運作方式

如果每個站台有四個外部磁碟櫃、則每個磁碟櫃都會指派給不同的節點和不同的資源池、如下列範例所示：

* 此時會自動將site_A-balle_1上的所有磁碟指派給node_a_1的Pool 0
* 此時會自動將site_A-balle_3上的所有磁碟指派給node_a_2的資源池0
* 此時會自動將site_B-b櫃_1上的所有磁碟指派給node_B_1的Pool 0
* 此時會自動將site_B-b櫃_3上的所有磁碟指派給node_B_2的資源池0
* 此時會自動將site_B-b櫃_2上的所有磁碟指派給node_a_1的資源池1
* 此時會自動將site_B-b櫃_4上的所有磁碟指派給node_a_2的集區1
* 此時會自動將site_A-bally_2上的所有磁碟指派給node_B_1的集區1
* 此時會自動將site_A-bally_4上的所有磁碟指派給node_B_2的集區1




== 如何填入部分已滿的磁碟櫃

如果您的組態使用的磁碟櫃未完全填滿（有空的磁碟機支架）、則必須根據磁碟指派原則、將磁碟平均分配到整個磁碟櫃。磁碟指派原則取決於每MetroCluster 個站台有多少磁碟櫃。

如果您在每個站台使用單一磁碟櫃（或AFF 只使用內部磁碟櫃、位於一個E800*系統上）、則會使用一個磁碟櫃原則來指派磁碟。如果磁碟櫃未完全裝滿、請將磁碟機平均安裝在所有季度。

下表顯示如何將24個磁碟放入48個磁碟機內部磁碟櫃的範例。也會顯示磁碟機的擁有權。

|===


| 48個磁碟機支架分為四季： | 每季在前六個磁碟槽中安裝六個磁碟機... 


 a| 
第1季：Bay 0-11
 a| 
托架0-5



 a| 
第2季：Bay 12-23
 a| 
磁碟槽12-17



 a| 
第3季：Bay 24-035
 a| 
托架24至29個



 a| 
第4季：Bay 36-48
 a| 
托架36-41

|===
如果您在每個站台使用兩個磁碟櫃、則會使用半磁碟櫃原則來指派磁碟。如果磁碟櫃未完全裝滿、請從磁碟櫃任一端平均安裝磁碟機。

例如、如果您要在24個磁碟機櫃中安裝12個磁碟機、請在0到5和18到23個磁碟機槽中安裝磁碟機。



== 手動指派磁碟機（ONTAP S9.5）

在支援S9.5的系統中ONTAP 、需要在具有下列機櫃組態的系統上手動指派磁碟機：

* 每個站台有三個外部磁碟櫃。
+
兩個磁碟櫃會使用半磁碟櫃指派原則自動指派、但第三個磁碟櫃必須手動指派。

* 每個站台有四個以上的磁碟櫃、外部磁碟櫃的總數並不是四個的倍數。
+
四個磁碟機中最接近的多個磁碟櫃仍未指派、因此必須手動指派磁碟機。例如、如果站台有五個外部磁碟櫃、則必須手動指派磁碟櫃五。



您只需要在每個未指派的機櫃上手動指派一個磁碟機。然後會自動指派磁碟櫃上的其餘磁碟機。



== 手動指派磁碟機（ONTAP 例如、9.4）

在NetApp 9.4中ONTAP 、下列機櫃組態的系統需要手動指派磁碟機：

* 每個站台不到四個外部磁碟櫃。
+
磁碟機必須手動指派、以確保磁碟機的對稱指派、每個集區的磁碟機數量必須相等。

* 每個站台有四個以上的外部磁碟櫃、外部磁碟櫃的總數則不是四個的倍數。
+
四個磁碟機中最接近的多個磁碟櫃仍未指派、因此必須手動指派磁碟機。



手動指派磁碟機時、您應該對稱地指派磁碟、並為每個集區指派相同數量的磁碟機。例如、如果每個站台的組態有兩個儲存磁碟櫃、您可以使用一個磁碟櫃連接本機HA配對、另一個磁碟櫃連接至遠端HA配對：

* 將ssite a櫃1上的一半磁碟指派給node_a_1的資源池0。
* 將s加_A-bider_1上的一半磁碟指派給node_a_2的資源池0。
* 將ssite A-bider_2上的一半磁碟指派給node_B_1的集區1。
* 將ssite A-bider_2上的一半磁碟指派給node_B_2的集區1。
* 將ssite B-sider_1上的一半磁碟指派給node_B_1的Pool 0。
* 將s加 至node_B_2的Pool 0的s加 至s加 至s加 至s加 至sente_B-sidb_1的一半磁碟。
* 將s加 至node_a_1之集區1的se_b-be-bider_2上的一半磁碟指派給該集區。
* 將s加 至node_a_2集區1的s加 至s站 點_B-side_2上的一半磁碟。




== 新增磁碟櫃至現有組態

自動磁碟機指派可在現有組態中對稱地新增磁碟櫃。

新增磁碟櫃時、系統會將相同的指派原則套用至新增的磁碟櫃。例如、每個站台只有一個機櫃、如果新增了一個機櫃、系統就會將機櫃指派規則套用至新機櫃。

link:concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.html["必要MetroCluster 的知識、包括知識、知識、知識、知識、知識、知識"]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["磁碟與Aggregate管理"^]



== ADP和磁碟指派差異、依系統MetroCluster 而異、以供搭配使用

進階磁碟分割（ADP MetroCluster ）的操作以及在各種不同的系統模式下自動指派磁碟。


NOTE: 在使用ADP的系統中、會使用分割區來建立集合體、將每個磁碟機分割至P1、P2和P3分割區。根Aggregate是使用P3分割區建立的。

您必須符合MetroCluster 支援磁碟機數量上限和其他準則的要求。

https://hwu.netapp.com["NetApp Hardware Universe"]



=== ADP和磁碟指派、位於AFF 不受保護的A320系統上

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
48個磁碟機
 a| 
每個外部機櫃上的磁碟機分為兩個相同的群組（一半）。每個半磁碟櫃都會自動指派給個別的資源池。
 a| 
本機HA配對使用一個機櫃。第二個機櫃由遠端HA配對使用。

每個機櫃上的分割區都用於建立根Aggregate。根Aggregate中的兩個叢集都包含下列分割區::
+
--
* 八個資料分割區
* 兩個同位元檢查分割區
* 兩個備用磁碟分割


--




 a| 
支援的磁碟機下限（每個站台）
 a| 
24個磁碟機
 a| 
磁碟機分為四個等群組。每個季度櫃都會自動指派給個別的資源池。
 a| 
根Aggregate中的兩個叢集分別包含下列分割區：

* 三個資料分割區
* 兩個同位元檢查分割區
* 一個備用分割區


|===


=== ADP和磁碟指派、適用於AFF Solidon A220系統

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
僅限內部磁碟機
 a| 
內部磁碟機分為四個相同群組。每個群組都會自動指派給個別的集區、而且每個集區都會指派給組態中的個別控制器。


NOTE: 一半的內部磁碟機在MetroCluster 設定完使用功能前仍未指派。
 a| 
本地HA配對使用四分之二。其餘兩季則由遠端HA配對使用。

根Aggregate在每個叢中包含下列分割區：

* 三個資料分割區
* 兩個同位元檢查分割區
* 一個備用分割區




 a| 
支援的磁碟機下限（每個站台）
 a| 
16個內部磁碟機
 a| 
磁碟機分為四個等群組。每個季度櫃都會自動指派給個別的資源池。

每個機櫃上的四分之二可以有相同的集區。根據擁有該季的節點來選擇資源池：

* 如果由本機節點擁有、則會使用Pool0。
* 如果是由遠端節點擁有、則會使用Pool1。


例如：第1季到第4季的機櫃可以指派下列作業：

* Q1：node_a_1 Pool0
* Q2：node_a_2 Pool0
* 問題3：node_B_1 Pool1
* Q4：node_B_2 Pool1



NOTE: 一半的內部磁碟機在MetroCluster 設定完使用功能前仍未指派。
 a| 
根Aggregate中的兩個叢集分別包含下列分割區：

* 一個資料分割區
* 兩個同位元檢查分割區
* 一個備用分割區


|===


=== ADP和磁碟指派、位於AFF Solide A250系統上

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
48個磁碟機
 a| 
每個外部機櫃上的磁碟機分為兩個相同的群組（一半）。每個半磁碟櫃都會自動指派給個別的資源池。
 a| 
本機HA配對使用一個機櫃。第二個機櫃由遠端HA配對使用。

每個機櫃上的分割區都用於建立根Aggregate。根Aggregate在每個叢中包含下列分割區：

* 八個資料分割區
* 兩個同位元檢查分割區
* 兩個備用磁碟分割




 a| 
支援的磁碟機下限（每個站台）
 a| 
僅限16個內部磁碟機
 a| 
磁碟機分為四個等群組。每個季度櫃都會自動指派給個別的資源池。
 a| 
根Aggregate中的兩個叢集分別包含下列分割區：

* 三個資料分割區
* 兩個同位元檢查分割區
* 一個備用分割區


|===


=== ADP和磁碟指派、位於AFF Solida300系統上

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
48個磁碟機
 a| 
每個外部機櫃上的磁碟機分為兩個相同的群組（一半）。每個半磁碟櫃都會自動指派給個別的資源池。
 a| 
本機HA配對使用一個機櫃。第二個機櫃由遠端HA配對使用。

每個機櫃上的分割區都用於建立根Aggregate。根Aggregate在每個叢中包含下列分割區：

* 八個資料分割區
* 兩個同位元檢查分割區
* 兩個備用磁碟分割




 a| 
支援的磁碟機下限（每個站台）
 a| 
24個磁碟機
 a| 
磁碟機分為四個等群組。每個季度櫃都會自動指派給個別的資源池。
 a| 
根Aggregate中的兩個叢集分別包含下列分割區：

* 三個資料分割區
* 兩個同位元檢查分割區
* 一個備用分割區


|===


=== ADP和磁碟指派、位於AFF Solida400系統上

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
96個磁碟機
 a| 
磁碟機會依機櫃自動指派。
 a| 
根Aggregate中的兩個叢集分別包括：

* 20個資料分割區
* 兩個同位元檢查分割區
* 兩個備用磁碟分割




 a| 
支援的磁碟機下限（每個站台）
 a| 
24個磁碟機
 a| 
磁碟機分為四個等群組（四個季度）。每個季度櫃都會自動指派給個別的資源池。
 a| 
根Aggregate中的兩個叢集分別包括：

* 三個資料分割區
* 兩個同位元檢查分割區
* 一個備用分割區


|===


=== ADP和磁碟指派、位於AFF Solida700系統上

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
96個磁碟機
 a| 
磁碟機會依機櫃自動指派。
 a| 
根Aggregate中的兩個叢集分別包括：

* 20個資料分割區
* 兩個同位元檢查分割區
* 兩個備用磁碟分割




 a| 
支援的磁碟機下限（每個站台）
 a| 
24個磁碟機
 a| 
磁碟機分為四個等群組（四個季度）。每個季度櫃都會自動指派給個別的資源池。
 a| 
根Aggregate中的兩個叢集分別包括：

* 三個資料分割區
* 兩個同位元檢查分割區
* 一個備用分割區


|===


=== ADP和磁碟指派、位於AFF Solida800系統上

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | 根Aggregate的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
內部磁碟機和96個外部磁碟機
 a| 
內部分割區分為四個相等的群組（季度）。每一季都會自動指派給個別的資源池。外部磁碟櫃上的磁碟機會依機櫃自動指派、每個磁碟櫃上的所有磁碟機都會指派MetroCluster 到位在「還原」組態中的四個節點之一。
 a| 
根Aggregate是以內部機櫃上的12個根分割區所建立。

根Aggregate中的兩個叢集分別包括：

* 八個資料分割區
* 兩個同位元檢查分割區
* 兩個備用磁碟分割




 a| 
支援的磁碟機下限（每個站台）
 a| 
僅限24個內部磁碟機
 a| 
內部分割區分為四個相等的群組（季度）。每一季都會自動指派給個別的資源池。
 a| 
根Aggregate是以內部機櫃上的12個根分割區所建立。

根Aggregate中的兩個叢集分別包括：

* 三個資料分割區
* 兩個同位元檢查分割區
* 一個備用磁碟分割


|===


=== ADP和磁碟指派、位於AFF SolidWa 900系統

|===


| 準則 | 每個站台的磁碟櫃 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
96個磁碟機
 a| 
磁碟機會依機櫃自動指派。
 a| 
根Aggregate中的兩個叢集分別包括：

* 20個資料分割區
* 兩個同位元檢查分割區
* 兩個備用磁碟分割




 a| 
支援的磁碟機下限（每個站台）
 a| 
24個磁碟機
 a| 
磁碟機分為四個等群組（四個季度）。每個季度櫃都會自動指派給個別的資源池。
 a| 
根Aggregate中的兩個叢集分別包括：

* 三個資料分割區
* 兩個同位元檢查分割區
* 一個備用分割區


|===


=== FAS2750系統上的磁碟指派

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
24個內部磁碟機和24個外部磁碟機
 a| 
內部與外部磁碟櫃分為兩半。每一半會自動指派給不同的資源池
 a| 
不適用。

|===


=== FAS8200系統上的磁碟指派

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
48個磁碟機
 a| 
外部磁碟櫃上的磁碟機分為兩個等群組（兩個半）。每個半磁碟櫃都會自動指派給個別的資源池。
 a| 
不適用。

|===


=== FAS500f系統上的磁碟指派

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
96個磁碟機
 a| 
磁碟機會依機櫃自動指派。
 a| 
不適用。

|===


=== FAS9000系統上的磁碟指派

|===


| 準則 | 每個站台的磁碟機數量 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
96個磁碟機
 a| 
磁碟機會依機櫃自動指派。
 a| 
不適用。



 a| 
支援的磁碟機下限（每個站台）
 a| 
48個磁碟機
 a| 
磁碟櫃上的磁碟機分為兩個等群組（兩個半）。每個半磁碟櫃都會自動指派給個別的資源池。
 a| 
支援的磁碟機下限（每個站台）（主動/被動HA組態）

|===


=== FAS9500系統上的磁碟指派

|===


| 準則 | 每個站台的磁碟櫃 | 磁碟機指派規則 | root分割區的ADP配置 


 a| 
建議的最低磁碟機數（每個站台）
 a| 
96個磁碟機
 a| 
磁碟機會依機櫃自動指派。
 a| 
不適用



 a| 
支援的磁碟機下限（每個站台）
 a| 
24個磁碟機
 a| 
磁碟機分為四個等群組（四個季度）。每個季度櫃都會自動指派給個別的資源池。
 a| 
支援的磁碟機下限（每個站台）（主動/被動HA組態）

|===