---
permalink: install-ip/concept_considerations_mediator.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: 各種MetroCluster 版本的不二組態在必要的元件上有主要差異。 
---
= 不一樣的地方ONTAP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP S廳9.7開始、您可以在ONTAP ESIIP組態中使用由資訊管理員輔助的自動非計畫性切換（MAUSO）MetroCluster 、也可以使用MetroCluster Setiebreaker軟體。不需要使用 MAUSO 或 Tiebreaker 軟體、但如果您選擇不使用其中任何一項服務、則必須使用 link:../disaster-recovery/concept_dr_workflow.html["執行手動恢復"] 發生災難時。

不同MetroCluster 的功能組態會在不同情況下自動切換：

* *使用AUSO功能的SFC組態（不存在於SIP組態中）MetroCluster MetroCluster *
+
在這些組態中、如果控制器故障但儲存設備（如果有橋接器）仍可運作、則會啟動AUSO。

* *使用 ONTAP Mediator 的 MetroCluster IP 配置（ONTAP 9.7 及更高版本）*
+
在這些組態中、MAUSO會在與AUSO相同的情況下啟動、如前所述、也會在完整站台故障（控制器、儲存設備和交換器）之後啟動。

+
link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html["瞭解 ONTAP Mediator 如何支援自動非計畫性切換"]。

* *使用主動模式下的Tiebreaker軟體進行IP或FC組態* MetroCluster
+
在這些組態中、當整個站台發生故障時、斷路器會啟動非計畫性的切換。

+
使用Tiebreaker軟體之前、請先檢閱 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["物件斷路器軟體安裝與組態MetroCluster"]





== 不受任何應用程式與應用程式與應用裝置之間的互通性ONTAP

您無法搭配ONTAP 使用任何可觸發切換的第三方應用程式或應用裝置、以搭配使用「媒體資訊器」。此外MetroCluster 、使用「SIESITERator」時、不支援使用MetroCluster ESITERE斷路 器軟體監控任何一個ESITESE組態ONTAP 。
