---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: 從 ONTAP 9.7 開始，ONTAP Mediator 可以透過提供實體上獨立的狀態資訊儲存庫來協助 MetroCluster IP 設定執行自動排程外切換。 
---
= MetroCluster IP 組態的 ONTAP Mediator 安裝需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您的環境必須符合特定要求。

下列需求適用於單一災難恢復群組（DR群組）。深入瞭解 link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["DR群組"]。

* 如果您打算更新 Linux 版本，請在安裝最新版本的 ONTAP Mediator 之前進行更新。
* ONTAP Mediator 和 MetroCluster Tiebreaker 軟體不應同時與相同的 MetroCluster 配置一起使用。
* ONTAP 調解器必須安裝在與 MetroCluster 站點不同位置的 Linux 主機上。
+
每個站台之間的連線ONTAP 能力必須是兩個獨立的故障領域。

* 支援自動非計畫性的切換ONTAP 功能、可在更新版本的更新版本中使用。
* 從 ONTAP 9.19.1 和 ONTAP Mediator 1.12 開始，您可以設定 ONTAP Mediator 使用 HTTPS 而非 iSCSI 進行通訊。當 ONTAP Mediator 配置為使用 HTTPS 時，每個 ONTAP Mediator 執行個體只能監控一個 MetroCluster IP 組態。如需詳細資訊，請參閱 <<選擇 ONTAP Mediator 的通訊協定>>。
* 從 ONTAP 9.18.1 和 ONTAP Mediator 1.11 開始，單一配置了 iSCSI 的 ONTAP Mediator 實例最多可以同時管理十個 MetroCluster 組態。在 ONTAP 9.17.1 和 ONTAP Mediator 1.10 及更早版本中，配置了 iSCSI 的 ONTAP Mediator 最多可以同時支援五個 MetroCluster 組態。
* 從ONTAP 9.18.1 開始，在MetroCluster IP 設定中， ONTAP Mediator 1.11 或更高版本支援 IPv6。




== 在 MetroCluster 配置中使用 ONTAP 調解器的網路需求

若要在 MetroCluster 設定中安裝 ONTAP 調解器，您必須確保該配置符合多個網路需求。

* 延遲
+
最大延遲低於75ms（RTT）。

+
不穩定性不得超過5毫秒。

* MTU
+
MTU大小必須至少為1400。

* 封包遺失
+
對於網際網路控制訊息傳輸協定（ICMP）和TCP流量、封包遺失必須低於0.01%。

* 頻寬
+
ONTAP 調解器和一個 DR 組之間的連結必須至少具有 20Mbps 的頻寬。

* 獨立連線
+
每個站台和ONTAP 這個「位址器」之間必須獨立連線。一個站台發生故障時、不得中斷其他兩個不受影響站台之間的IP連線。





== MetroCluster 配置中 ONTAP 調解器的主機需求

您必須確保組態符合多項主機需求。

* 必須在實體與兩個實體叢集分離的外部站台安裝此資訊卡。ONTAP ONTAP
* 不需要超過主機作業系統的CPU和記憶體（RAM）最低需求。ONTAP
* 除了主機作業系統的最低需求之外、還必須至少提供30GB的額外可用磁碟空間。
+
** 每個DR群組最多需要200MB的磁碟空間。






== 選擇 ONTAP Mediator 的通訊協定

預設情況下，MetroCluster IP 節點使用 iSCSI 工作階段存取 ONTAP Mediator 信箱 LUN。ONTAP Mediator 依賴 SCST 套件提供 iSCSI。iSCSI 工作階段使用挑戰交握驗證通訊協定（CHAP）進行驗證，該通訊協定使用模糊化、機器產生的預先共用金鑰，但並非完全加密。

從 ONTAP 9.19.1 和 ONTAP Mediator 1.12 開始，您可以設定 ONTAP Mediator 執行個體，使其使用 HTTPS 而非 iSCSI 進行通訊。HTTPS 是一種安全的通訊協定，它使用 SSL/TLS 對整個工作階段進行加密，與 iSCSI 相比，安全性更高。

您只能透過 CLI 設定使用 HTTPS 的 ONTAP Mediator。不支援 System Manager。

[CAUTION]
====
* 如果將 ONTAP Mediator 設定為使用 HTTPS，則單一 ONTAP Mediator 執行個體只能監控一個 MetroCluster IP 組態。不支援同時監控多個 MetroCluster IP 組態。
* 如果您需要設定 ONTAP Mediator 並啟用 HTTPS 來監控多個 MetroCluster IP 配置，則必須為每個 MetroCluster IP 配置單獨配置 ONTAP Mediator 實例。在選擇為 MetroCluster IP 設定 ONTAP Mediator 並啟用 HTTPS 之前，您必須仔細評估 MetroCluster IP 環境的需求。
* 如果要使用單一 ONTAP Mediator 實例來監控多個 MetroCluster IP 配置，則應使用 iSCSI 而非 HTTPS 設定 ONTAP Mediator。


====
如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation["ONTAP Mediator 的 HTTPS 和 iSCSI 安裝選項"^]。



== 在 MetroCluster 配置中升級 ONTAP 調解器的指南

如果要升級 ONTAP Mediator，則必須滿足 Linux 版本要求並遵循升級指南。

* ONTAP Mediator 可以從前一個版本升級到目前版本。
* 所有的媒體版本都支援MetroCluster 執行ONTAP 支援支援的各種知識、例如執行支援的知識產權配置、例如更新版本的支援。


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["安裝或升級 ONTAP 調解器"^]



== 升級之後

完成調控器和作業系統升級之後、您應該使用「shorage iscsi啟動器show」命令來確認調控器連線正常。
