---
permalink: install-ip/switch-move-cluster-lifs.html 
sidebar: sidebar 
keywords: ip, switch, configuring, configure, factory defaults, cisco, MACsec encryption, 9336C, 9336, forward error correction, fec 
summary: 更新交換器韌體或參考組態檔案 （RCF） 時，需要將叢集 LIF 移至合作夥伴交換器，以便在升級期間實現叢集的無中斷運作。 
---
= 在 MetroCluster IP 組態中進行交換器、RCF 或韌體變更之前，移動叢集 LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您更換 MetroCluster IP 交換器或變更交換器韌體或參考組態檔案 （RCF） 時，需要將叢集 LIF 移至合作夥伴交換器，以實現不間斷的叢集作業。

.關於這項工作
* 在升級或降級交換器韌體、更換交換器 RCF 或更換 IP 交換器之前，必須執行此工作。
+

NOTE: 如果是第一次設定交換器，則可以跳過此工作，除非您要更換交換器。

* 此工作需要您同時使用 ONTAP 命令和交換器命令；除非另有說明，否則皆使用 ONTAP 命令。
* 在本程序的範例中，您正在升級 IP_switch_A_1，因此您需要將叢集 LIF 移轉至 IP_switch_A_2。
* 本程序中的命令輸出範例顯示 Cisco 交換器的詳細資訊。輸出結果可能因交換器型號和廠商而異。


.步驟
. 顯示連接到每個節點上叢集交換器的叢集連接埠：
+
「網路裝置探索秀」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node_A_2/cdp
            e10b   IP_switch_A_2
                                             Ethernet1/18      N9K-C9336C-FX2
            e2a    IP_switch_A_1
                                             Ethernet1/18      N9K-C9336C-FX2
            e4a    IP_switch_A_1
                                             Ethernet1/2       N9K-C9336C-FX2
            e4b    IP_switch_A_2
                                             Ethernet1/2       N9K-C9336C-FX2
            e5b    IP_switch_A_1
                                             Ethernet1/10      N9K-C9336C-FX2
            e7b    IP_switch_A_2
                                             Ethernet1/10      N9K-C9336C-FX2
            e9a    local_network_switch
                                             Ethernet1/5       N9K-C9372PX
            e9b    local_network_switch
                                             Ethernet1/6       N9K-C9372PX
node_A_2/lldp
            e0M    mgmt_switch (00:08:2f:16:8e:02)
                                             Eth121/1/1        -
            e10b   IP_switch_A_2 (cc:90:70:e8:73:a0)
                                             Ethernet1/18      -
            e2a    IP_switch_A_1 (cc:90:70:e8:50:48)
                                             Ethernet1/18      -
            e5b    IP_switch_A_1 (cc:90:70:e8:50:28)
                                             Ethernet1/10      -
            e7b    IP_switch_A_2 (cc:90:70:e8:73:80)
                                             Ethernet1/10      -
            e9a    local_network_switch (88:f0:31:86:fe:a8)
                                             Ethernet1/5       -
            e9b    local_network_switch (88:f0:31:86:fe:a9)
                                             Ethernet1/6       -
node_A_1/cdp
            e10b   IP_switch_A_2
                                             Ethernet1/17      N9K-C9336C-FX2
            e2a    IP_switch_A_1
                                             Ethernet1/17      N9K-C9336C-FX2
            e4a    IP_switch_A_1
                                             Ethernet1/1       N9K-C9336C-FX2
            e4b    IP_switch_A_2
                                             Ethernet1/1       N9K-C9336C-FX2
            e5b    IP_switch_A_1
                                             Ethernet1/9       N9K-C9336C-FX2
            e7b    IP_switch_A_2
                                             Ethernet1/9       N9K-C9336C-FX2
            e9a    local_network_switch
                                             Ethernet1/3       N9K-C9372PX
            e9b    local_network_switch
                                             Ethernet1/4       N9K-C9372PX
node_A_1/lldp
            e0M    mgmt_switch (00:08:2f:16:8e:03)
                                             Eth121/1/2        -
            e10b   IP_switch_A_2 (cc:90:70:e8:73:9c)
                                             Ethernet1/17      -
            e2a    IP_switch_A_1 (cc:90:70:e8:50:44)
                                             Ethernet1/17      -
            e5b    IP_switch_A_1 (cc:90:70:e8:50:24)
                                             Ethernet1/9       -
            e7b    IP_switch_A_2 (cc:90:70:e8:73:7c)
                                             Ethernet1/9       -
            e9a    local_network_switch (88:f0:31:86:fe:a6)
                                             Ethernet1/3       -
            e9b    local_network_switch (88:f0:31:86:fe:a7)
                                             Ethernet1/4       -
30 entries were displayed.
----
====
. 檢查每個叢集連接埠的管理和運作狀態。
+
.. 確認叢集所有連接埠均已啟動且狀態正常：
+
`network port show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network port show -role cluster

Node: node_A_1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/40000 healthy  false

Node: node_A_2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/40000 healthy  false
4 entries were displayed.
----
====
.. 確認所有叢集介面（LIF）都位於主連接埠上：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      101.101.101.88/18  node_A_1      e4a     true
            node_A_1_clus2 up/up      101.101.101.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      101.101.101.96/18  node_A_2      e4a     true
            node_A_2_clus2 up/up      101.101.101.97/18  node_A_2      e4b     true
4 entries were displayed.

cluster_A::*>
----
====
.. 確認叢集顯示兩個叢集交換器的資訊：
+
`system switch ethernet show -is-monitoring-enabled-operational true`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> system switch ethernet show -is-monitoring-enabled-operational true
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
IP_switch_A_1               cluster-network    10.231.7.251     N9K-C9336C-FX2
     Serial Number: FDO26020KLJ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(4)
    Version Source: CDP/ISDP

IP_switch_A_2               cluster-network    10.231.7.252     N9K-C9336C-FX2
     Serial Number: FDO26020KGL
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(4)
    Version Source: CDP/ISDP

2 entries were displayed.

cluster_A::*>
----
====


. 停用叢集 LIF 的自動還原功能。叢集 LIF 容錯移轉到合作夥伴叢集交換器，並在您對目標交換器執行升級程序時保持在該交換器上：
+

NOTE: 如果您要升級第二個架構，則可以跳過此步驟並轉到<<shut-down-ports,步驟4.>>。

+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface modify -vserver Cluster -lif * -auto-revert false

Warning: Disabling the auto-revert feature of the cluster logical interface may
         effect the availability of your cluster network. Are you sure you want
         to continue? {y|n}: y

Warning: Changes to a cluster LIF can affect the health of the Cluster. Are you
         sure you want to continue? {y|n}: y
4 entries were modified.
----
====
. [[shut-down-ports]]在叢集交換器 IP_switch_A1 上，關閉連接到節點叢集連接埠的連接埠。
+
[role="tabbed-block"]
====
.Cisco
--
[listing]
----
IP_switch_A_1(config)# sh int eth1/1,eth1/2 brief

--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch
#
--------------------------------------------------------------------------------
Eth1/1          101     eth  access up      none                      40G(D) --
Eth1/2          101     eth  access up      none                      40G(D) --
IP_switch_A_1(config)#
IP_switch_A_1(config)# int eth1/1,eth1/2
IP_switch_A_1(config-if-range)# shut
IP_switch_A_1(config-if-range)#
----
--
.Broadcom
--
[listing]
----
IP_switch_A1(config)# interface eth1/1/1-2,eth1/7-8
IP_switch_A1(config-if-range)# shutdown
----
--
.NVIDIA
--
.. 顯示叢集介面：
+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ nv show interface
Interface    Admin Status  Oper Status  Speed  MTU    Type      Remote Host     Remote Port  Summary
-----------  ------------  -----------  -----  -----  --------  --------------  -----------  ---------
swp1         up            up           100G   9216   swp       cluster1         e1a
----
.. 關閉叢集介面連接埠：
+
[listing]
----
sudo python3 <RCF_name> runCmd swp1 state down
----


--
====
. [[verify_cluster_lif_migration]] 驗證叢集 LIF 是否已移轉到叢集交換器 IP_switch_A2 上託管的連接埠。這可能需要幾秒鐘。
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      101.101.101.88/18  node_A_1      e4b     false
            node_A_1_clus2 up/up      101.101.101.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      101.101.101.96/18  node_A_2      e4b     false
            node_A_2_clus2 up/up      101.101.101.97/18  node_A_2      e4b     true
4 entries were displayed.
----
====
. 驗證叢集是否正常：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node_A_1             true    true          false
node_A_2             true    true          false
2 entries were displayed.
----
====


.完成後
叢集 LIF 移轉到合作夥伴交換器後，您可以依照交換器廠商的標準組態程序完成升級至目標韌體或 RCF 版本：

* link:../install-ip/task_switch_config_broadcom.html["設定Broadcom IP交換器"]
* link:../install-ip/task_switch_config_cisco.html["設定Cisco IP交換器"]
* link:../install-ip/task_switch_config_nvidia.html["設定NVIDIA IP交換器"]



NOTE: 在第一個架構中設定交換器後，必須重複上述步驟，將叢集 LIF 移轉至第二個架構。
