---
permalink: install-ip/task_sw_config_configure_mediator.html 
sidebar: sidebar 
keywords: metrocluster ip, ontap, mediator, tiebreaker 
summary: 您可以下載並安裝在第三個站台MetroCluster 上、也可以下載或安裝《斷位器》軟體、或是從ONTAP 《讚賞9.7》開始、ONTAP 即「《不知道如何使用」。 
---
= 設定MetroCluster 斷功能器或ONTAP 不含資料的資訊
:allow-uri-read: 


[role="lead"]
您可以下載並安裝在第三個站台MetroCluster 上、也可以下載或安裝《斷位器》軟體、或是從ONTAP 《讚賞9.7》開始、ONTAP 即「《不知道如何使用」。

您必須有一個Linux主機、可以透過網路連線到MetroCluster 位在整個過程中的兩個叢集。具體要求請參閱MetroCluster 《斷器》ONTAP 或《資訊系統》文件。

如果您要連線至現有的斷路器或ONTAP 不知如何使用的資料保護器執行個體、則需要使用者名稱、密碼和斷路器或訊務管理器服務的IP位址。

如果您必須安裝ONTAP 全新的《不景不景》執行個體、請依照指示安裝及設定軟體。

link:concept_mediator_requirements.html["針對ONTAP 非計畫性自動切換設定「功能不全」服務"]

如果您必須安裝新的Tiebreaker軟體執行個體、請遵循 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["安裝及設定軟體的指示"]。

您無法同時使用MetroCluster 相同ONTAP 的ESITireaker軟體和ESITERator MetroCluster 、以及相同的ESITESE組態。

link:../install-ip/concept_considerations_mediator.html["使用ONTAP 《不知道如何使用》或MetroCluster 《斷邊器》的考量"]

.步驟
. 設定ONTAP 「不適用」服務或Tiebreaker軟體：
+
** 如果您正在使用ONTAP 現有的《不知道如何使用》執行個體、請將ONTAP 《不知道如何使用》服務新增ONTAP 至《不知道如何使用》：
+
《支援組態設定的中介者新增-中介者位址IP位址-中介者主機」MetroCluster

** 如果您使用的是Tiebreaker軟體、請參閱 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Tiebreaker文件"]。



