---
permalink: install-ip/task_switch_config_broadcom.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, factory defaults 
summary: 您必須設定Broadcom IP交換器作為叢集互連和後端MetroCluster 的靜態IP連線。 
---
= 設定Broadcom IP交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須設定Broadcom IP交換器作為叢集互連和後端MetroCluster 的靜態IP連線。


NOTE: 您的組態在下列情況下需要額外授權（6個100-GB連接埠授權）：

* 您使用連接埠53和54做為40-Gbps或100-Gbps MetroCluster 的支援。
* 您所使用的平台將本機叢集和MetroCluster 功能區介面連接至連接埠49 - 52。




== 將Broadcom IP交換器重設為原廠預設值

在安裝新的交換器軟體版本和RCFs之前、您必須清除Broadcom交換器設定並執行基本組態。

.關於這項工作
* 您必須在MetroCluster 各個採用EIP組態的IP交換器上重複這些步驟。
* 您必須使用序列主控台連線至交換器。
* 此工作會重設管理網路的組態。


.步驟
. 變更為提升命令提示字元（`#'）：「enable」
+
[listing]
----
(IP_switch_A_1)> enable
(IP_switch_A_1) #
----
. 清除啟動組態並移除橫幅
+
.. 清除啟動組態：
+
*「erase啟動組態」*

+
[listing]
----
(IP_switch_A_1) #erase startup-config

Are you sure you want to clear the configuration? (y/n) y

(IP_switch_A_1) #
----
+
此命令不會清除橫幅。

.. 移除橫幅：
+
*「no set clibanner」*

+
[listing]
----
(IP_switch_A_1) #configure
(IP_switch_A_1)(Config) # no set clibanner
(IP_switch_A_1)(Config) #
----


. 重新啟動交換器：*（ip_switch_a_1）#reboot*
+
[listing]
----
Are you sure you would like to reset the system? (y/n) y
----
+

NOTE: 如果系統在重新載入交換器之前詢問是否要儲存未儲存或變更的組態、請選取*否*。

. 等待交換器重新載入、然後登入交換器。
+
預設使用者為「admin」、未設定密碼。畫面會顯示類似下列的提示：

+
[listing]
----
(Routing)>
----
. 變更為提高權限的命令提示字元：
+
「啟用」

+
[listing]
----
Routing)> enable
(Routing) #
----
. 將服務連接埠傳輸協定設為「無」：
+
'無服務傳輸協定'

+
[listing]
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----
. 將IP位址指派給服務連接埠：
+
「erviceport ip _ip-address__netask__gateway_」

+
以下範例顯示指派IP位址「10.10.10.10」的服務連接埠、子網路為「255．255．255．0」、閘道為「10．10．10」：

+
[listing]
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----
. 確認服務連接埠設定正確：
+
「How ServicePort」

+
下列範例顯示連接埠已啟動、且已指派正確的位址：

+
[listing]
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----
. 如有需要、請設定SSH伺服器。
+

NOTE: RCF檔案會停用Telnet傳輸協定。如果您未設定SSH伺服器、則只能使用序列連接埠連線存取橋接器。

+
.. 產生RSA金鑰。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----
.. 產生DSA金鑰（選用）
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----
.. 如果您使用的是FIPS相容版本的EFOS、請產生ECDSA金鑰。下列範例會建立長度為256的金鑰。有效值為256、384或521。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 256
----
.. 啟用SSH伺服器。
+
如有必要、請結束組態內容。

+
[listing]
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+

NOTE: 如果金鑰已經存在、系統可能會要求您覆寫金鑰。



. 如有需要、請設定網域和名稱伺服器：
+
設定

+
以下範例顯示「IP網域」和「IP名稱伺服器」命令：

+
[listing]
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----
. 如有需要、請設定時區和時間同步（SNTP）。
+
以下範例顯示「shntp」命令、指定SNTP伺服器的IP位址和相對時區。

+
[listing]
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----
. 設定交換器名稱：
+
「主機名稱ip_switch_a_1」

+
交換器提示會顯示新名稱：

+
[listing]
----
(Routing) # hostname IP_switch_A_1

(IP_switch_A_1) #
----
. 儲存組態：
+
寫入記憶體

+
您會收到類似下列範例的提示和輸出：

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(IP_switch_A_1) #
----
. 在其他三個MetroCluster 交換器上重複上述步驟、以進行REIP組態設定。




== 下載並安裝Broadcom交換器EFOS軟體

您必須將交換器作業系統檔案和RCF檔案下載到MetroCluster 各個交換器、使其採用EWIP組態。

.關於這項工作
此工作必須在MetroCluster 每個交換器上重複執行、且必須採用EIP組態。

[]
====
*請注意下列事項：*

* 從EFOS 3.4.x.x升級至EFOS 3.7.x.x或更新版本時、交換器必須執行EFOS 3.4.4.6（或更新版本3.4.x.x）。如果您執行之前的版本、請先將交換器升級至EFOS 3.4.4.6（或更新版本3.4.x.x）、然後將交換器升級至EFOS 3.7.x.x或更新版本。
* EFOS 3.4.x.x和3.7.x.x或更新版本的組態不同。若要將EFOS版本從3.4.x.x變更為3.7.x.x或更新版本、或將其變更為3.7.x.x或更新版本、必須將交換器重設為原廠預設值、並套用對應EFOS版本的RCF檔案（重新）。此程序需要透過序列主控台連接埠存取。
* 從EFOS 3.7.x.x或更新版本開始、我們提供不符合FIPS標準的版本、以及符合FIPS標準的版本。從非FIPS相容的版本移至FIPS相容的版本時、會套用不同的步驟、反之亦然。將EFOS從非FIPS相容的版本變更為FIPS相容的版本、反之亦然、會將交換器重設為原廠預設值。此程序需要透過序列主控台連接埠存取。


====
.步驟
. 使用「show FIPS STATUS」命令檢查您的EFOS版本是否符合FIPS標準或不符合FIPS標準。在下列範例中、「ip_switch_a_1」使用FIPS相容的EFOS、而「ip_switch_a_2」使用的是非FIPS相容的EFOS。
+
*範例1*

+
[listing]
----
IP_switch_A_1 #show fips status

System running in FIPS mode

IP_switch_A_1 #
----
+
*範例2*

+
[listing]
----
IP_switch_A_2 #show fips status
                     ^
% Invalid input detected at `^` marker.

IP_switch_A_2 #
----
. 請使用下表來判斷您必須遵循的方法：
+
|===


| *程序* | *目前的EFOS版本* | *全新EFOS版本* | *高階步驟* 


 a| 
在兩個（非）FIPS相容版本之間升級EFOS的步驟
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
使用方法1安裝新的EFOS映像）會保留組態與授權資訊



 a| 
3.4.4.6（或更新版本3.4.x.x）
 a| 
3.7.x.x或更新版本不符合FIPS標準
 a| 
使用方法1升級EFOS。將交換器重設為原廠預設值、並套用EFOS 3.7.x.x或更新版本的RCF檔案



.2+| 3.7.x.x或更新版本不符合FIPS標準  a| 
3.4.4.6（或更新版本3.4.x.x）
 a| 
使用方法1降級EFOS。將交換器重設為原廠預設值、並套用EFOS 3.4.x.x的RCF檔案



 a| 
3.7.x.x或更新版本不符合FIPS標準
 a| 
使用方法1安裝新的EFOS映像。系統會保留組態與授權資訊



 a| 
3.7.x.x或更新版本符合FIPS標準
 a| 
3.7.x.x或更新版本符合FIPS標準
 a| 
使用方法1安裝新的EFOS映像。系統會保留組態與授權資訊



 a| 
從FIPS相容EFOS版本升級至/升級的步驟
 a| 
不符合FIPS標準
 a| 
符合FIPS標準
 a| 
使用方法2安裝EFOS映像。交換器組態和授權資訊將會遺失。



 a| 
符合FIPS標準
 a| 
不符合FIPS標準

|===
+
** 方法1： <<將軟體映像下載到備份開機分割區、以升級EFOS的步驟>>
** 方法2： <<使用ONIE OS安裝來升級EFOS的步驟>>






=== 將軟體映像下載到備份開機分割區、以升級EFOS的步驟

只有在兩個EFOS版本皆不相容於FIPS或兩個EFOS版本皆符合FIPS標準時、您才能執行下列步驟。


NOTE: 如果某個版本符合FIPS標準、而另一個版本不符合FIPS標準、請勿使用這些步驟。

.步驟
. 將交換器軟體複製到交換器：「+複製sftp：//user@50.50.50.50 /交換器軟體/EFOS-3.4.6.stk備份+」
+
在此範例中、EFOS -3.4.6.stk作業系統檔案會從SFTP伺服器複製到備份分割區、檔位為50.50.50。您需要使用TFTP/SFTP伺服器的IP位址、以及需要安裝的RCF檔案名稱。

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/switchsoftware/efos-3.4.4.6.stk backup
Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /switchsoftware/
Filename....................................... efos-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
SFTP Code transfer starting...


File transfer operation completed successfully.

(IP_switch_A_1) #
----
. 在下一次交換器重新開機時、將交換器設定為從備份分割區開機：
+
「開機系統備份」

+
[listing]
----
(IP_switch_A_1) #boot system backup
Activating image backup ..

(IP_switch_A_1) #
----
. 確認新的開機映像在下一次開機時會處於作用中狀態：
+
「如何啟動bootvar

+
[listing]
----
(IP_switch_A_1) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

 ----  -----------  --------  ---------------  ------------
 unit       active    backup   current-active   next-active
 ----  -----------  --------  ---------------  ------------

	1       3.4.4.2    3.4.4.6      3.4.4.2        3.4.4.6

(IP_switch_A_1) #
----
. 儲存組態：
+
寫入記憶體

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
. 重新啟動交換器：
+
"重裝"

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
. 等待交換器重新開機。
+

NOTE: 在極少數情況下、交換器可能無法開機。請依照 <<使用ONIE OS安裝來升級EFOS的步驟>> 以安裝新映像。

. 如果您將交換器從EFOS 3.4.x.x變更為EFOS 3.7.x.x或反之、請遵循下列兩個程序來套用正確的組態（RCF）：
+
.. <<將Broadcom IP交換器重設為原廠預設值>>
.. <<下載並安裝Broadcom RCF檔案>>


. 在靜態IP組態的其餘三個IP交換器上重複上述步驟MetroCluster 。




=== 使用ONIE OS安裝來升級EFOS的步驟

如果其中一個EFOS版本符合FIPS標準、而另一個EFOS版本不符合FIPS標準、您可以執行下列步驟。這些步驟可用於在交換器無法開機時、從ONIE安裝非FIPS或FIPS相容的EFOS 3.7.x.x映像。

.步驟
. 將交換器開機至ONIE安裝模式。
+
在開機期間、當下列畫面出現時、請選取ONIE：

+
[listing]
----
 +--------------------------------------------------------------------+
 |EFOS                                                                |
 |*ONIE                                                               |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
選取「ONIE」之後、交換器就會載入並顯示下列選項：

+
[listing]
----
 +--------------------------------------------------------------------+
 |*ONIE: Install OS                                                   |
 | ONIE: Rescue                                                       |
 | ONIE: Uninstall OS                                                 |
 | ONIE: Update ONIE                                                  |
 | ONIE: Embed ONIE                                                   |
 | DIAG: Diagnostic Mode                                              |
 | DIAG: Burn-In Mode                                                 |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
現在、交換器將會開機進入ONIE安裝模式。

. 停止ONIE探索並設定乙太網路介面
+
出現下列訊息後、按下<enter>以叫用ONIE主控台：

+
[listing]
----
 Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE探索將會繼續、訊息將會列印到主控台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 設定乙太網路介面、然後使用「ifconfigeth0 <ipaddress> netmask> up」和「route add default gW <gatewayAddress>」新增路由
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 確認裝載ONIE安裝檔案的伺服器可連線：
+
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
. 安裝新的交換器軟體
+
[listing]
----

ONIE:/ # onie-nos-install http:// 50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http:// 50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http:// 50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
+
軟體將會安裝、然後重新啟動交換器。讓交換器正常重新開機至新的EFOS版本。

. 確認已安裝新的交換器軟體
+
*「show bootvar*」

+
[listing]
----

(Routing) #show bootvar
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	   backup   current-active  next-active
---- 	----------- -------- --------------- ------------
1 	3.7.0.4     3.7.0.4  3.7.0.4         3.7.0.4
(Routing) #
----
. 完成安裝
+
交換器將在未套用組態的情況下重新開機、然後重設為原廠預設值。請依照下列兩份文件所述的兩個程序來設定交換器基本設定並套用RCF檔案：

+
.. 設定交換器基本設定。請遵循步驟4及更新版本： <<將Broadcom IP交換器重設為原廠預設值>>
.. 建立並套用RCF檔案、如所述 <<下載並安裝Broadcom RCF檔案>>






== 下載並安裝Broadcom RCF檔案

您必須將交換器RCF檔案下載並安裝到MetroCluster 各個交換器、以供採用此功能的介面IP組態。

.開始之前
此工作需要檔案傳輸軟體、例如FTP、TFTP、SFTP或scp。 將檔案複製到交換器。

.關於這項工作
這些步驟必須重複執行MetroCluster 於各個採用EIP組態的IP交換器上。

共有四個RCF檔案、MetroCluster 每個檔案分別對應於整個EIP組態中的四個交換器。您必須針對所使用的交換器機型使用正確的RCF檔案。

|===


| 交換器 | RCF檔案 


 a| 
ip_switch_a_1.
 a| 
v1.32_Switch-A1.txt



 a| 
ip_switch_a_2
 a| 
v1.32_Switch-A2.txt



 a| 
IP交換器_B_1
 a| 
v1.32_Switch-B1.txt



 a| 
IP交換器_B_2
 a| 
v1.32_Switch-B2.txt

|===

NOTE: EFOS 3.4.4.6版或更新版本3.4.x.x的RCF檔案版本與EFOS版本3.7.0.4不同。您必須確定已針對交換器執行的EFOS版本建立正確的RCF檔案。

|===


| EFOS版本 | RCF檔案版本 


| 3.4.x.x | v1.3x、v1.4x 


| 3.7.x.x | v2.x 
|===
.步驟
. 產生Broadcom RCF檔案MetroCluster 以利知識IP。
+
.. 下載 https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGeneratorfor MetroCluster EfIP"]
.. 使用RcfFileGeneratorfor MetroCluster EIP、為您的組態產生RCF檔案。
+

NOTE: 不支援下載後修改RCF檔案。



. 將RCF檔案複製到交換器：
+
.. 將RCF檔案複製到第一個交換器：「copy sftp：//user@ft-server_ip-address/rcfFiles/switch-specific -rCF/BES-53248_v1.32_Switch-A1.txt nvRAv:script bes-53241_v1.32_switch-a1.scr」
+
在此範例中、「Bes-53241_v1.32_Switch-a1.txt」RCF檔案會從SFTP伺服器複製到本機BootFlash、路徑為「50.50.50.50」。您需要使用TFTP/SFTP伺服器的IP位址、以及需要安裝的RCF檔案名稱。

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/RcfFiles/BES-53248_v1.32_Switch-A1.txt nvram:script BES-53248_v1.32_Switch-A1.scr

Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /RcfFiles/
Filename....................................... BES-53248_v1.32_Switch-A1.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_v1.32_Switch-A1.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
File transfer operation completed successfully.


Validating configuration script...

config

set clibanner "***************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248


...
The downloaded RCF is validated. Some output is being logged here.
...


Configuration script validated.
File transfer operation completed successfully.

(IP_switch_A_1) #
----
.. 確認RCF檔案已儲存為指令碼：
+
《記錄清單》

+
[listing]
----
(IP_switch_A_1) #script list

Configuration Script Name        Size(Bytes)  Date of Modification
-------------------------------  -----------  --------------------
BES-53248_v1.32_Switch-A1.scr             852   2019 01 29 18:41:25

1 configuration script(s) found.
2046 Kbytes free.
(IP_switch_A_1) #
----
.. 套用RCF指令碼：
+
「說明」套用B2-53241_v1.32_Switch-A1.scr

+
[listing]
----
(IP_switch_A_1) #script apply BES-53248_v1.32_Switch-A1.scr

Are you sure you want to apply the configuration script? (y/n) y


config

set clibanner "********************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248

...
The downloaded RCF is validated. Some output is being logged here.
...

Configuration script 'BES-53248_v1.32_Switch-A1.scr' applied.

(IP_switch_A_1) #
----
.. 儲存組態：
+
寫入記憶體

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
.. 重新啟動交換器：
+
"重裝"

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
.. 對其他三個交換器重複上述步驟、請務必將相符的RCF檔案複製到對應的交換器。


. 重新載入交換器：
+
"重裝"

+
[listing]
----
IP_switch_A_1# reload
----
. 在其他三個MetroCluster 交換器上重複上述步驟、以進行REIP組態設定。




== 停用未使用的 ISL 連接埠和連接埠通道

NetApp 建議停用未使用的 ISL 連接埠和連接埠通道、以避免不必要的健全狀況警示。

. 使用 RCF 檔案橫幅識別未使用的 ISL 連接埠和連接埠通道：
+

NOTE: 如果連接埠處於中斷連線模式、則您在命令中指定的連接埠名稱可能與 RCF 橫幅中指定的名稱不同。您也可以使用 RCF 纜線檔案來尋找連接埠名稱。

+
[role="tabbed-block"]
====
.以取得 ISL 連接埠詳細資料
--
執行命令 `show port all`。

--
.以取得連接埠通道詳細資料
--
執行命令 `show port-channel all`。

--
====
. 停用未使用的 ISL 連接埠和連接埠通道。
+
您必須針對每個識別出的未使用連接埠或連接埠通道執行下列命令。

+
[listing]
----
(SwtichA_1)> enable
(SwtichA_1)# configure
(SwtichA_1)(Config)# <port_name>
(SwtichA_1)(Interface 0/15)# shutdown
(SwtichA_1)(Interface 0/15)# end
(SwtichA_1)# write memory
----

