---
permalink: install-ip/task_sw_config_configure_mediator.html 
sidebar: sidebar 
keywords: metrocluster ip, ontap, mediator, tiebreaker 
summary: 您可以下載並安裝在第三個站台MetroCluster 上、也可以下載或安裝《斷位器》軟體、或是從ONTAP 《讚賞9.7》開始、ONTAP 即「《不知道如何使用」。 
---
= 設定MetroCluster 斷功能器或ONTAP 不含資料的資訊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以下載並安裝在第三個站台MetroCluster 上、也可以下載或安裝《斷位器》軟體、或是從ONTAP 《讚賞9.7》開始、ONTAP 即「《不知道如何使用」。

.開始之前
您必須有一個Linux主機、可以透過網路連線到MetroCluster 位在整個過程中的兩個叢集。具體要求請參閱MetroCluster 《斷器》ONTAP 或《資訊系統》文件。

如果您要連線到現有的 Tiebreaker 或 ONTAP Mediator 實例，則需要 Tiebreaker 或 Mediator 的使用者名稱、密碼和 IP 位址。

如果您必須安裝ONTAP 全新的《不景不景》執行個體、請依照指示安裝及設定軟體。

link:concept_mediator_requirements.html["配置 ONTAP 調解器以實現計劃外自動切換"]

如果您必須安裝新的Tiebreaker軟體執行個體、請遵循 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["安裝及設定軟體的指示"]。

.關於這項工作
您無法同時使用MetroCluster 相同ONTAP 的ESITireaker軟體和ESITERator MetroCluster 、以及相同的ESITESE組態。

link:../install-ip/concept_considerations_mediator.html["使用ONTAP 《不知道如何使用》或MetroCluster 《斷邊器》的考量"]

.步驟
. 配置 ONTAP Mediator 或 Tiebreaker 軟體：
+
** 如果您正在使用 ONTAP 調解器的現有實例，請將 ONTAP 調解器新增至 ONTAP：
+
《支援組態設定的中介者新增-中介者位址IP位址-中介者主機」MetroCluster

** 如果您使用的是Tiebreaker軟體、請參閱 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Tiebreaker文件"]。



