---
settings:
  name: ONTAP MetroCluster
  harmony_integration: maestro
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: 文件MetroCluster
    url: "/index.html"
  - section: releasenotes
  - section: install-fc
  - section: install-ip
  - section: install-stretch
  - section: tiebreaker
  - title: 瞭MetroCluster 解資料保護與災難恢復
    entries:
    - title: 如何保護資料並提供災難恢復MetroCluster
      url: "/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html"
  - section: manage
  - section: maintain
  - section: transition
  - section: upgrade
  - section: disaster-recovery
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
