---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: 從 ONTAP 9.13.1 開始、您可以將工作負載和資料從現有的八節點 MetroCluster FC 組態、無中斷地移轉至新的 MetroCluster IP 組態。 
---
= 不中斷地從MetroCluster 一個不中斷的支援FC移轉至MetroCluster 一個支援功能性的IP組態ONTAP （版本號：9.8及更新版本）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在不中斷營運的情況下、將工作負載和資料從現有的 MetroCluster FC 組態轉換為新的 MetroCluster IP 組態。

從 ONTAP 9.13.1 開始、此程序在 MetroCluster 和磁碟機櫃連接至相同 IP 交換器（共享儲存交換器組態）的 MetroCluster IP 組態中受到支援。

從 ONTAP 9.13.1 開始、您可以將工作負載和資料從現有的八節點 MetroCluster FC 組態、無中斷地移轉至新的 MetroCluster IP 組態。

從 ONTAP 9.8 開始、您可以將工作負載和資料從現有的四節點 MetroCluster FC 組態、無中斷地移轉至新的 MetroCluster IP 組態。

* 此程序不中斷營運。
+
在作業期間、可繼續提供資料的功能。MetroCluster

* 此程序僅適用於四節點和八節點 MetroCluster FC 組態。
+
如果您有雙節點MetroCluster 的不含功能的FC組態、請參閱 link:concept_choosing_your_transition_procedure_mcc_transition.html["選擇您的轉換程序"]。

* 本程序說明轉換一個四節點 FC DR 群組所需的步驟。如果您有八節點組態（兩個 FC DR 群組）、則必須針對每個 FC DR 群組重複整個程序。
* 您必須符合所有要求、並遵循程序中的所有步驟。




== 啟用主控台記錄

NetApp 強烈建議您在使用的裝置上啟用主控台記錄功能、並在執行此程序時採取下列動作：

* 在維護期間保持啟用 AutoSupport 。
* 在維護之前和之後觸發維護 AutoSupport 訊息、以在維護活動期間停用案例建立。
+
請參閱知識庫文章 link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["如何在排程的維護期間、隱藏自動建立個案"^]。

* 啟用任何 CLI 工作階段的工作階段記錄。有關如何啓用會話日誌記錄的說明，請查看知識庫文章中的“日誌記錄會話輸出”部分 link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何設定 Putty 以最佳化連線至 ONTAP 系統"^]。

