---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: 從 ONTAP 9.13.1 開始、您可以將工作負載和資料從現有的八節點 MetroCluster FC 組態、無中斷地移轉至新的 MetroCluster IP 組態。 
---
= 不中斷地從MetroCluster 一個不中斷的支援FC移轉至MetroCluster 一個支援功能性的IP組態ONTAP （版本號：9.8及更新版本）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在不中斷營運的情況下、將工作負載和資料從現有的 MetroCluster FC 組態轉換為新的 MetroCluster IP 組態。

從 ONTAP 9.13.1 開始、此程序在 MetroCluster 和磁碟機櫃連接至相同 IP 交換器（共享儲存交換器組態）的 MetroCluster IP 組態中受到支援。

從ONTAP 9.13.1 開始，您可以將工作負載和資料從現有的八節點MetroCluster FC 設定無中斷地遷移到新的八節點MetroCluster IP 設定。您可以使用此程序轉換四節點 FC DR 群組，刪除空的 FC DR 群組，然後對第二個 FC DR 群組重複此程序。 

從ONTAP 9.8 開始，您可以將工作負載和資料從現有的四節點MetroCluster FC 配置無中斷地遷移到新的四節點MetroCluster IP 配置。完成過渡後，如果需要，您可以擴展到八節點MetroCluster IP 配置。看link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["展開 MetroCluster IP 組態"]。

* 此程序不中斷營運。
+
在作業期間、可繼續提供資料的功能。MetroCluster

* 此程序僅適用於四節點和八節點 MetroCluster FC 組態。
+
如果您有雙節點MetroCluster 的不含功能的FC組態、請參閱 link:concept_choosing_your_transition_procedure_mcc_transition.html["選擇您的轉換程序"]。

* 本程序說明轉換一個四節點 FC DR 群組所需的步驟。如果您有八節點組態（兩個 FC DR 群組）、則必須針對每個 FC DR 群組重複整個程序。
+

NOTE: 當您依照此流程新增或刪除 DR 群組時，必須先驗證 DR 群組的新增或刪除是否成功，然後再新增或刪除另一個 DR 群組。

* 您必須符合所有要求、並遵循程序中的所有步驟。




[[transition-scenarios-supported-by-this-procedure]]
== 本程序支援的轉換情境

請查看下表，以了解此程序支援的過渡方案。


NOTE: 在所有過渡場景中，每次只能新增或移除一個災難復原群組。災難復原群組新增或移除成功後，需要驗證 MetroCluster 運作狀況良好且正常，然後再繼續下一步。

[cols="2*"]
|===
| 針對這種過渡方案…… | 執行以下操作…… 


 a| 
四節點 FC 至四節點 IP 組態
 a| 
請依照以下步驟操作。



 a| 
四節點 FC 到八節點 IP 配置
 a| 
需要新增一個 MetroCluster IP DR 組。新增第一個 MetroCluster IP DR 組後，檢查叢集的整體運作狀況，然後對第二個 MetroCluster IP DR 組重複上述步驟。



 a| 
八節點 FC 到四節點 IP 配置
 a| 
請依照以下步驟操作。過渡期間，MetroCluster 配置將從八個節點擴展到十二個節點。過渡完成後，所有 MetroCluster FC 節點都將取消加入，最終配置將是四節點 MetroCluster IP 配置。



 a| 
八節點 FC 至八節點 IP 組態
 a| 
此過渡需要在叢集中新增一個 MetroCluster IP DR 群組。

確認十二節點配置運作狀況正常後，將資料和 LIF（如有需要）從其中一個 MetroCluster FC DR 群組遷移到 MetroCluster IP DR 群組。當某個 MetroCluster FC DR 群組為空時，移除該 DR 群組並取消其節點加入叢集。最終配置為一個由一個 MetroCluster FC DR 群組和一個 MetroCluster IP DR 群組組成的八節點叢集。

然後，將第二個 MetroCluster IP DR 群組新增至叢集，並視需要轉換資料和 LIF。當最後一個 MetroCluster FC DR 群組為空時，將其移除並取消相關節點的加入。

在過渡期間的任何時刻，MetroCluster 配置中的節點數都不會超過十二個節點。

|===
如需更多資訊、請參閱 link:concept_transition_workflow_fc_to_ip_transition.html["不中斷MetroCluster 營運的流程無法進行不中斷的移轉"] 。



[[important-information-when-adding-an-older-platform-model]]
== 添加舊平台模型時的重要訊息

以下指導針對一種不常見的情況，即您需要將較舊的平台模型（ ONTAP 9.15.1 之前發布的平台）添加到包含較新平台模型（ ONTAP 9.15.1 或更高版本中發布的平台）的現有MetroCluster配置中。對於八節點 FC 到 IP 的過渡，如果您已將第一個 FC DR 組過渡到ONTAP 9.15.1 或更高版本中引入的平台模型，併計劃將第二個 DR 組過渡到ONTAP 9.15.1 之前引入的平台，則本指南適用。

如果您現有的MetroCluster配置包含使用 *共用叢集/HA 連接埠* 的平台（ ONTAP 9.15.1 或更高版本中發布的平台） ，則如果未將配置中的所有節點升級至ONTAP 9.15.1P11 或ONTAP 9.16.1P4 或更高版本，則無法新增使用 195.16.1P4ONTAP之前發布的平台）。

請使用下表驗證您的組合是否受到影響。如果您的現有平台列於第一列，而您要新增至組態的平台列於第二列，則組態中的所有節點都必須執行 ONTAP 9.15.1P11 或 ONTAP 9.16.1P4 或更高版本（取決於平台支援的 ONTAP 版本），才能新增新的 DR 群組。

[CAUTION]
====
* 將使用 *共享的 MetroCluster/HA 連接埠* 的舊平台模型新增至包含使用 *共享的叢集/HA 連接埠* 的新平台模型的 MetroCluster 中是一種不常見的情況，大多數組合都不會受到影響。
* 表格列出了所有使用共享的 MetroCluster/HA 連接埠和共享的叢集/HA 連接埠的平台型號。並非所有組合都受此程序支援。請參閱 link:concept_choosing_your_transition_procedure_mcc_transition.html#supported-platform-combinations["支援的平台組合"] 以確認您的過渡組合是否受支援。


====
[cols="20,20,20,20,20"]
|===
2+| 如果您現有的 MetroCluster 包含... 2+| 您要新增的平台是... | 然後... 


 a| 
使用*共享集群/HA 連接埠*的 AFF 系統：

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
使用*共享集群/HA 連接埠*的 FAS 系統：

* FAS50
* FAS70
* FAS90

 a| 
使用*共用 MetroCluster/HA 連接埠*的 AFF 系統：

* AFF A150 、 ASA A150
* VA220 AFF
* AFF C250 、 ASA C250
* AFF A250 、 ASA A250
* 部分A300 AFF
* 解答320 AFF
* AFF C400 、 ASA C400
* AFF A400 、 ASA A400
* 部分A700 AFF
* AFF C800 、 ASA C800
* AFF A800 、 ASA A800
* AFF A900 、 ASA A900

 a| 
使用*共用 MetroCluster/HA 連接埠*的 FAS 系統：

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| 在將新平台新增至現有 MetroCluster 配置之前，請將現有配置和新配置中的所有節點升級至 ONTAP 9.15.1P11 或 ONTAP 9.16.1P4 或更高版本。 
|===