---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: 從 ONTAP 9.13.1 開始、您可以將工作負載和資料從現有的八節點 MetroCluster FC 組態、無中斷地移轉至新的 MetroCluster IP 組態。 
---
= 不中斷地從MetroCluster 一個不中斷的支援FC移轉至MetroCluster 一個支援功能性的IP組態ONTAP （版本號：9.8及更新版本）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在不中斷營運的情況下、將工作負載和資料從現有的 MetroCluster FC 組態轉換為新的 MetroCluster IP 組態。

從 ONTAP 9.13.1 開始、此程序在 MetroCluster 和磁碟機櫃連接至相同 IP 交換器（共享儲存交換器組態）的 MetroCluster IP 組態中受到支援。

從 ONTAP 9.13.1 開始、您可以將工作負載和資料從現有的八節點 MetroCluster FC 組態、無中斷地移轉至新的 MetroCluster IP 組態。

從 ONTAP 9.8 開始、您可以將工作負載和資料從現有的四節點 MetroCluster FC 組態、無中斷地移轉至新的 MetroCluster IP 組態。

* 此程序不中斷營運。
+
在作業期間、可繼續提供資料的功能。MetroCluster

* 此程序僅適用於四節點和八節點 MetroCluster FC 組態。
+
如果您有雙節點MetroCluster 的不含功能的FC組態、請參閱 link:concept_choosing_your_transition_procedure_mcc_transition.html["選擇您的轉換程序"]。

* 本程序說明轉換一個四節點 FC DR 群組所需的步驟。如果您有八節點組態（兩個 FC DR 群組）、則必須針對每個 FC DR 群組重複整個程序。
* 您必須符合所有要求、並遵循程序中的所有步驟。


.重要資訊
在過渡、刷新和擴展過程中，您可能會為 MetroCluster 配置添加新的平台模型。在這些流程的任何階段，如果現有 MetroCluster 配置包含使用 *共用叢集/HA 連接埠* 的平台，則您必須將 ONTAP 版本升級至 ONTAP 9.15.1P11 或 ONTAP 9.16.1P4 或更高版本，才能將使用 *共用 MetroCluster/HA 連接埠* 的平台新增至設定中。

在決定使用此流程之前，請仔細查看下表中的資訊。如果第一列列出了您現有的平台，而第二列列出了要新增至配置中的平台，則配置中的所有節點都必須執行 ONTAP 9.15.1P11 或 ONTAP 9.16.1P4 或更高版本才能支援此流程。


CAUTION: 現有平台和要新增到配置中的平台必須都執行 ONTAP 9.15.1P11 或 ONTAP 9.16.1P4 或更高版本。

[cols="20,20,20,20,20"]
|===
2+| 如果您現有的 MetroCluster 包含... 2+| 您要新增的平台是... | 然後... 


 a| 
使用*共享集群/HA 連接埠*的 AFF 系統：

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
使用*共享集群/HA 連接埠*的 FAS 系統：

* FAS50
* FAS70
* FAS90

 a| 
使用*共用 MetroCluster/HA 連接埠*的 AFF 系統：

* AFF A150 、 ASA A150
* VA220 AFF
* AFF C250 、 ASA C250
* AFF A250 、 ASA A250
* 部分A300 AFF
* 解答320 AFF
* AFF C400 、 ASA C400
* AFF A400 、 ASA A400
* 部分A700 AFF
* AFF C800 、 ASA C800
* AFF A800 、 ASA A800
* AFF A900 、 ASA A900

 a| 
使用*共用 MetroCluster/HA 連接埠*的 FAS 系統：

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| 在將新平台新增至現有 MetroCluster 配置之前，請將現有配置和新配置中的所有節點升級至 ONTAP 9.15.1P11 或 ONTAP 9.16.1P4 或更高版本。 
|===