---
permalink: upgrade/task_assign_disk_ownership_in_aff_systems_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, assign, disk, ownership, aff, systems 
summary: 如果AFF 您在組態中使用鏡射Aggregate、但節點未正確指派磁碟（SSD）、則應將每個機櫃上的一半磁碟指派給一個本機節點、另一半磁碟指派給HA合作夥伴節點。您應該建立一個組態、讓每個節點在其本機和遠端磁碟集區中擁有相同數量的磁碟。 
---
= 指派AFF 對系統的磁碟擁有權
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果AFF 您在組態中使用鏡射Aggregate、但節點未正確指派磁碟（SSD）、則應將每個機櫃上的一半磁碟指派給一個本機節點、另一半磁碟指派給HA合作夥伴節點。您應該建立一個組態、讓每個節點在其本機和遠端磁碟集區中擁有相同數量的磁碟。

儲存控制器必須處於維護模式。

這不適用於具有無鏡射集合體、主動/被動組態、或在本機和遠端集區中磁碟數目不相等的組態。

如果從原廠收到磁碟時已正確指派磁碟、則不需要執行此工作。


NOTE: Pool 0一律包含與擁有磁碟的儲存系統位於同一站台的磁碟、而Pool 1則永遠包含遠端磁碟、而這些磁碟位於擁有這些磁碟的儲存系統。

.步驟
. 如果您尚未啟動、請將每個系統開機至維護模式。
. 將磁碟指派給位於第一個站台（站台A）的節點：
+
您應該為每個集區指派相同數量的磁碟。

+
.. 在第一個節點上、系統地將每個機櫃上的一半磁碟指派給資源池0、另一半指派給HA合作夥伴的資源池0：+「磁碟指派-disk _disk-name_-p _pool _-n _number-of磁碟_」
+
如果儲存控制器Controller_a_1有四個磁碟櫃、每個磁碟櫃各有8個SSD、您會發出下列命令：

+
[listing]
----
*> disk assign -shelf FC_switch_A_1:1-4.shelf1 -p 0 -n 4
*> disk assign -shelf FC_switch_A_1:1-4.shelf2 -p 0 -n 4

*> disk assign -shelf FC_switch_B_1:1-4.shelf1 -p 1 -n 4
*> disk assign -shelf FC_switch_B_1:1-4.shelf2 -p 1 -n 4
----
.. 對本機站台的第二個節點重複此程序、系統地將每個機櫃上的一半磁碟指派給資源池1、另一半指派給HA合作夥伴的資源池1：+「磁碟指派磁碟_disk-name_-p _pool」
+
如果儲存控制器Controller_a_1有四個磁碟櫃、每個磁碟櫃各有8個SSD、您會發出下列命令：

+
[listing]
----
*> disk assign -shelf FC_switch_A_1:1-4.shelf3 -p 0 -n 4
*> disk assign -shelf FC_switch_B_1:1-4.shelf4 -p 1 -n 4

*> disk assign -shelf FC_switch_A_1:1-4.shelf3 -p 0 -n 4
*> disk assign -shelf FC_switch_B_1:1-4.shelf4 -p 1 -n 4
----


. 將磁碟指派給位於第二站台（站台B）的節點：
+
您應該為每個集區指派相同數量的磁碟。

+
.. 在遠端站台的第一個節點上、系統地將每個磁碟櫃上的一半磁碟指派給資源池0、另一半指派給HA合作夥伴的資源池0：+「disk assign -disk _disk-name_-p _pool」
+
如果儲存控制器Controller_B_1有四個磁碟櫃、每個磁碟櫃有8個SSD、您會發出下列命令：

+
[listing]
----
*> disk assign -shelf FC_switch_B_1:1-5.shelf1 -p 0 -n 4
*> disk assign -shelf FC_switch_B_1:1-5.shelf2 -p 0 -n 4

*> disk assign -shelf FC_switch_A_1:1-5.shelf1 -p 1 -n 4
*> disk assign -shelf FC_switch_A_1:1-5.shelf2 -p 1 -n 4
----
.. 針對遠端站台的第二個節點重複此程序、系統地將每個機櫃上的一半磁碟指派給資源池1、另一半指派給HA合作夥伴的資源池1：
+
「磁碟指派-disk _disk-name_-p _pool」

+
如果儲存控制器Controller_B_2有四個磁碟櫃、每個磁碟櫃有8個SSD、您會發出下列命令：

+
[listing]
----
*> disk assign -shelf FC_switch_B_1:1-5.shelf3 -p 0 -n 4
*> disk assign -shelf FC_switch_B_1:1-5.shelf4 -p 0 -n 4

*> disk assign -shelf FC_switch_A_1:1-5.shelf3 -p 1 -n 4
*> disk assign -shelf FC_switch_A_1:1-5.shelf4 -p 1 -n 4
----


. 確認磁碟指派：
+
「torage show disk」

. 結束維護模式：
+
《停止》

. 顯示開機功能表：
+
Boot_ONTAP功能表

. 在每個節點上、選取選項* 4*以初始化所有磁碟。

