---
permalink: upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 您可以使用這項引導式自動化 MetroCluster 轉換作業、針對四節點 MetroCluster IP 組態執行不中斷運作的控制器升級。 
---
= 在四節點 MetroCluster IP 組態中升級控制器、使用切換功能、並使用「系統控制器更換」命令（ ONTAP 9.13.1 及更新版本）切換回控制器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此引導式自動化 MetroCluster 轉換作業、在四節點 MetroCluster IP 組態上執行不中斷的控制器升級。其他元件（例如儲存櫃或交換器）無法在此程序中進行升級。



== 支援的平台組合

此程序支援在執行 ONTAP 9.13.1 及更新版本的系統上進行下列控制器升級。

|===


| 舊控制器 | 更換控制器 


| 部分A300 AFF | 解答900 AFF 


| FAS8200 | FAS9500 
|===

NOTE: 您可以使用上述手動升級程序、在執行 ONTAP 9.12.1 或 9.11.1 的系統上執行上表所列的控制器升級 link:task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html["請按這裡"]。

如需平台升級組合的詳細資訊、請參閱中的 MetroCluster IP 升級表 link:concept_choosing_controller_upgrade_mcc.html#supported-metrocluster-ip-controller-upgrades["選擇控制器升級程序"]。

請參閱 link:https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["選擇升級或重新整理方法"] 以瞭解其他程序。



== 關於這項工作

* 您只能將此程序用於控制器升級。
+
組態中的其他元件（例如儲存櫃或交換器）無法同時升級。

* 此程序適用於執行 ONTAP 9.13.1 或更新版本的四節點 MetroCluster IP 組態中的控制器模組。
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

* MetroCluster 系統必須在兩個站台上執行相同的 ONTAP 版本。
* 您可以使用此程序來升級四節點 MetroCluster IP 組態中的控制器、使用 NSO 型自動切換和切換。
+

NOTE: 四節點 MetroCluster IP 組態不支援使用 Aggregate 重定位（ ARL ）和「系統控制器置換」命令來執行升級。

* 如果您的系統已啟用、 link:../maintain/task-configure-encryption.html#disable-end-to-end-encryption["停用端點對端點加密"] 執行升級之前。
* 您必須使用自動 NSO 控制器升級程序、以連續升級兩個站台的控制器。
* 這項自動化的NSO型控制器升級程序可讓您將控制器更換至MetroCluster 還原災難恢復（DR）站台。您一次只能在一個站台啟動控制器更換。
* 若要在站台A開始更換控制器、您需要從站台B執行控制器更換啟動命令此作業只會引導您更換站台A上兩個節點的控制器。若要更換站台B的控制器、您必須從站台A執行控制器更換啟動命令此時會顯示一則訊息、指出要更換控制器的站台。


本程序使用下列範例名稱：

* 站台_A
+
** 升級前：
+
*** node_a_1-old
*** node_a_2-old


** 升級後：
+
*** node_a_1-new
*** node_a_2-new




* 站台_B
+
** 升級前：
+
*** node_B_1-old
*** node_B_2-old


** 升級後：
+
*** node_B_1-new
*** node_B_2-new








== 準備升級

若要準備控制器升級、您必須執行系統預先檢查並收集組態資訊。

在預先檢查開始之前、如果已安裝 ONTAP Mediator 、系統會自動偵測並移除它。若要確認移除、系統會提示您輸入使用者名稱和密碼。當您完成升級、或預先檢查失敗、或您選擇不繼續升級時、您必須執行 <<man_reconfig_mediator,手動重新設定 ONTAP Mediator>>。

在升級期間的任何階段、您都可以從站台A執行「系統控制器置換show」或「系統控制器置換show-details」命令、以檢查狀態。如果命令傳回空白輸出、請等待幾分鐘、然後重新執行命令。

.步驟
. 從站台A開始自動化控制器更換程序、以更換站台B的控制器：
+
`system controller replace start -nso true`

+
自動化作業會執行預先檢查。如果找不到問題、作業會暫停、以便您手動收集組態相關資訊。

+
[NOTE]
====
** 如果您未執行 `system controller replace start -nso true` 命令、控制器升級程序會選擇 NSO 型自動切換和切換、作為 MetroCluster IP 系統的預設程序。
** 畫面會顯示目前的來源系統和所有相容的目標系統。如果您已將來源控制器更換為具有不同ONTAP 版本的控制器或不相容平台、則在新節點開機後、自動化作業會停止並報告錯誤。若要使叢集恢復正常狀態、您必須遵循手動還原程序。
+
「系統控制器更換start」命令可能會報告下列預先檢查錯誤：

+
[listing]
----
Cluster-A::*>system controller replace show
Node        Status         Error-Action
----------- -------------- ------------------------------------
Node-A-1    Failed         MetroCluster check failed. Reason : MCC check showed errors in component aggregates
----
+
檢查此錯誤是否是因為您有未鏡射的Aggregate或是因為另一個Aggregate問題而發生。確認所有鏡射Aggregate均正常運作、且未降級或鏡射降級。如果此錯誤僅由未鏡射的Aggregate所造成、您可以在「系統控制器更換開始」命令上選取「skip -MetroCluster-check true」選項來覆寫此錯誤。如果可以存取遠端儲存設備、則無鏡射的集合體會在切換後上線。如果遠端儲存連結失敗、則未鏡射的集合體將無法上線。



====
. 在站台B登入、然後依照主控台訊息「系統控制器更換show」或「系統控制器更換show-details」命令中所列的命令、手動收集組態資訊。




=== 在升級之前收集資訊

在升級之前、如果根磁碟區已加密、您必須先收集備份金鑰和其他資訊、才能以舊的加密根磁碟區來啟動新的控制器。

.關於這項工作
此工作是在現有的 MetroCluster IP 組態上執行。

.步驟
. 標示現有控制器的纜線、以便在設定新控制器時輕鬆識別纜線。
. 顯示命令以擷取備份金鑰及其他資訊：
+
「System Controller replace show」（系統控制器更換顯示）

+
從合作夥伴叢集執行「show」命令下所列的命令。

+
。 `show` 命令輸出會顯示三個表格、其中包含 MetroCluster 介面 IP 、系統 ID 和系統 UUID 。稍後在引導新節點時設置 bootargs 的過程中需要此信息。

. 收集MetroCluster 節點的系統ID（以「Sof the Sof the Sof the nodes in the Sof the S
+
--
「MetroCluster 這個節點顯示欄位節點系統ID、DR-Partner SystemID」

在升級過程中、您將以新控制器模組的系統 ID 來取代這些舊系統 ID 。

在此四節點 MetroCluster IP 組態範例中、會擷取下列舊系統 ID ：

** node_a_1-old：40687441258
** node_a_2-old：4068741260
** node_B_1-old：40687441254
** node_B_2-old：40687441256


[listing]
----
metrocluster-siteA::> metrocluster node show -fields node-systemid,ha-partner-systemid,dr-partner-systemid,dr-auxiliary-systemid
dr-group-id        cluster           node            node-systemid     ha-partner-systemid     dr-partner-systemid    dr-auxiliary-systemid
-----------        ---------------   ----------      -------------     -------------------     -------------------    ---------------------
1                    Cluster_A       Node_A_1-old    4068741258        4068741260              4068741256             4068741256
1                    Cluster_A       Node_A_2-old    4068741260        4068741258              4068741254             4068741254
1                    Cluster_B       Node_B_1-old    4068741254        4068741256              4068741258             4068741260
1                    Cluster_B       Node_B_2-old    4068741256        4068741254              4068741260             4068741258
4 entries were displayed.
----
在此雙節點 MetroCluster IP 組態範例中、會擷取下列舊系統 ID ：

** 節點_a_1：40687441258
** 節點_B_1：40687441254


[listing]
----
metrocluster node show -fields node-systemid,dr-partner-systemid

dr-group-id cluster    node          node-systemid dr-partner-systemid
----------- ---------- --------      ------------- ------------
1           Cluster_A  Node_A_1-old  4068741258    4068741254
1           Cluster_B  node_B_1-old  -             -
2 entries were displayed.
----
--
. 收集每個舊節點的連接埠和 LIF 資訊。
+
您應該為每個節點收集下列命令的輸出：

+
** 「網路介面show -role叢集、node-mgmt」
** 「網路連接埠show -node-name_-type Physical」
** 「網路連接埠VLAN show -node-name_」
** 「網路連接埠ifgrp show -node_node_name_-instance」
** 「網路連接埠廣播網域節目」
** 「網路連接埠連線能力顯示-詳細資料」
** 「網路IPSpace節目」
** 「Volume show」
** 《集合體展》
** 「系統節點執行節點_norme-name_ sysconfig -A」


. 如果MetroCluster 支援SAN組態、請收集相關資訊。
+
您應該收集下列命令的輸出：

+
** 「FCP介面卡顯示-instance」
** 「FCP介面show -instance」
** 「iSCSI介面展示」
** 「ucadmin show」


. 如果根磁碟區已加密、請收集並儲存用於金鑰管理程式的通關密碼：
+
「安全金鑰管理程式備份展示」

. 如果MetroCluster 這個節點正在使用磁碟區或集合體的加密功能、請複製金鑰和複製密碼的相關資訊。
+
如需其他資訊、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-1677AE0A-FEF7-45FA-8616-885AA3283BCF.html["手動備份內建金鑰管理資訊"^]。

+
.. 如果已設定Onboard Key Manager：
+
「安全金鑰管理程式內建show Backup」

+
稍後在升級程序中、您將需要密碼。

.. 如果已設定企業金鑰管理（KMIP）、請發出下列命令：
+
「安全金鑰管理程式外部show -instance」

+
「安全金鑰管理程式金鑰查詢」



. 完成組態資訊的收集之後、請繼續作業：
+
「系統控制器更換恢復」





=== 從斷路器或其他監控軟體移除現有組態

如果現有的組態是以MetroCluster 可啟動切換的ESITTiebreaker組態或其他協力廠商應用程式（例如ClusterLion）來監控、您必須先從MetroCluster 斷路器或其他軟體移除此類組態、才能更換舊的控制器。

.步驟
. link:../tiebreaker/concept_configuring_the_tiebreaker_software.html#removing-metrocluster-configurations["移除現有MetroCluster 的版本資訊"] 透過Tiebreaker軟體。
. 從MetroCluster 任何可啟動切換的第三方應用程式移除現有的功能。
+
請參閱應用程式的文件。





== 更換舊控制器並啟動新的控制器

收集資訊並恢復作業之後、自動化會繼續進行切換作業。

.關於這項工作
自動化作業會啟動「跨操作」。這些作業完成後、操作會暫停於 * 暫停以供使用者介入 * 、以便您可以使用從 Flash 備份將控制器機架安裝、開機合作夥伴控制器、以及將根 Aggregate 磁碟重新指派給新的控制器模組 `sysids` 早些時候收集到。

.開始之前
在啟動切換之前、自動化作業會暫停、以便您手動確認站台B的所有生命都是「up」如有必要、請將任何「'down」的lifs移至「up」、然後使用「system controller replace resume」命令恢復自動化作業。



=== 準備舊控制器的網路組態

為了確保新控制器上的網路能正常恢復、您必須將LIF移至通用連接埠、然後移除舊控制器的網路組態。

.關於這項工作
* 此工作必須在每個舊節點上執行。
* 您將使用中收集的資訊 <<準備升級>>。


.步驟
. 開機舊節點、然後登入節點：
+
Boot_ONTAP

. 將舊控制器上所有資料LIF的主連接埠指派給舊控制器模組和新控制器模組上相同的通用連接埠。
+
.. 顯示生命：
+
「網路介面展示」

+
SAN和NAS等所有資料生命量都是管理員「up」（啟動）和作業「down」（保留）、因為這些資料都是在切換站台（叢集_A）上啟動。

.. 檢閱輸出、找出舊控制器和新控制器上相同的通用實體網路連接埠、而這些控制器並未用作叢集連接埠。
+
例如、「'e0d'」是舊控制器上的實體連接埠、也存在於新的控制器上。「e0d」不做為叢集連接埠、也不做為新控制器上的其他連接埠。

+
如需平台機型的連接埠使用量、請參閱 link:https://hwu.netapp.com/["NetApp Hardware Universe"^]

.. 修改所有資料生命期、以使用通用連接埠作為主連接埠：
+
「網路介面修改-vserver _svm-name_-lif_data-lif_-home-port _port-id_」

+
在下列範例中、這是「e0d」。

+
例如：

+
[listing]
----
network interface modify -vserver vs0 -lif datalif1 -home-port e0d
----


. 修改廣播網域以移除需要刪除的VLAN和實體連接埠：
+
「廣播網域移除連接埠-broadcast網域_broadcast網域名稱_-ports _norme-name:port-id_」

+
對所有VLAN和實體連接埠重複此步驟。

. 使用叢集連接埠作為成員連接埠、使用叢集連接埠作為成員連接埠和介面群組、移除任何VLAN連接埠。
+
.. 刪除VLAN連接埠：
+
「網路連接埠VLAN刪除-node-name_-vlan-name _portID-vlanid_'

+
例如：

+
[listing]
----
network port vlan delete -node node1 -vlan-name e1c-80
----
.. 從介面群組移除實體連接埠：
+
「網路連接埠ifgrp remove-port -node-name_-ifgrp _interface-group-name_-port _portID_」

+
例如：

+
[listing]
----
network port ifgrp remove-port -node node1 -ifgrp a1a -port e0d
----
.. 從廣播網域移除VLAN和介面群組連接埠：
+
「網路連接埠廣播網域移除連接埠-IPSpace _IPspacity_-broadcast網域_broadcast網域名稱_-連接埠_nodename：連接埠名稱、節點名稱：連接埠名稱_、...」

.. 根據需要修改介面群組連接埠、以使用其他實體連接埠作為成員：
+
"ifgrp add-port -node-name_-ifgrp _interface-group名稱_-port _port-id_"



. 停止節點：
+
「halt -distrake-takeover true -node-name_」

+
此步驟必須在兩個節點上執行。





=== 設定新的控制器

您必須將新的控制器裝入機架並連接纜線。

.步驟
. 視需要規劃新控制器模組和儲存櫃的定位。
+
機架空間取決於控制器模組的平台模式、交換器類型、以及組態中的儲存櫃數量。

. 請妥善接地。
. 在機架或機櫃中安裝控制器模組。
+
https://docs.netapp.com/us-en/ontap-systems/index.html["ONTAP 硬體系統文件"^]

. 如果新的控制器模組未隨附本身的FC-VI卡、且舊控制器的FC-VI卡與新的控制器相容、請交換FC-VI卡、並將其安裝在正確的插槽中。
+
請參閱 link:https://hwu.netapp.com["NetApp Hardware Universe"^] 以取得FC-VI卡的插槽資訊。

. 如《_ MetroCluster 》《安裝與組態指南_》所述、連接控制器的電源、序列主控台和管理連線。
+
此時請勿連接任何其他與舊控制器中斷連線的纜線。

+
https://docs.netapp.com/us-en/ontap-systems/index.html["ONTAP 硬體系統文件"^]

. 開啟新節點的電源、並在系統提示顯示載入器提示時按Ctrl-C。




=== 新控制器的Netbooting

安裝新節點之後、您需要netboot才能確保新節點執行的ONTAP 版本與原始節點相同。「netboot」一詞是指您從ONTAP 儲存在遠端伺服器上的不實映像進行開機。準備網路開機時、您必須將ONTAP 一份《支援》9開機映像複本放到系統可以存取的網路伺服器上。

此工作會在每個新的控制器模組上執行。

.步驟
. 存取 link:https://mysupport.netapp.com/site/["NetApp 支援網站"^] 可下載用於執行系統netboot的文件。
. 從ONTAP NetApp支援網站的軟體下載區段下載適當的支援軟體、並將ONTAP-VERSION _image.tgz檔案儲存在可從網路存取的目錄中。
. 移至網路存取目錄、確認您所需的檔案可用。
+
您的目錄列表應包含內核文件 netboot 文件夾： ontap － version － image ． tgz

+
您不需要解壓縮 ONTAP 版本映像 .tgz 檔案。

. 在載入程式提示下、設定管理LIF的netboot連線：
+
** 如果IP定址為DHCP、請設定自動連線：
+
「ifconfige0M -auto」

** 如果IP定址為靜態、請設定手動連線：
+
"ifconfige0M -addr=ip_addr -mask=netmask"'-gateway=gateway"



. 執行netboot。
+
** 如果平台是80xx系列系統、請使用下列命令：
+
“netboot \http://web_server_ip/path_to_web-accessible_directory/netboot/kernel`

** 如果平台是任何其他系統、請使用下列命令：
+
“netboot \http://web_server_ip/path_to_web-accessible_directory/ontap-version_image.tgz`



. 從開機功能表中、選取選項*（7）Install new software first*（先安裝新軟體*）、將新的軟體映像下載並安裝至開機裝置。
+
 Disregard the following message: "This procedure is not supported for Non-Disruptive Upgrade on an HA pair". It applies to nondisruptive upgrades of software, not to upgrades of controllers.
. 如果系統提示您繼續此程序、請輸入「y」、並在系統提示您輸入套件時、輸入映像檔的URL：「http://web_server_ip/path_to_web-accessible_directory/ontap-version_image.tgz`」
+
....
Enter username/password if applicable, or press Enter to continue.
....
. 當您看到類似下列的提示時、請務必輸入「n」以跳過備份恢復：
+
....
Do you want to restore the backup configuration now? {y|n}
....
. 當您看到類似於以下內容的提示時、輸入「y」重新開機：
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....




=== 清除控制器模組上的組態

[role="lead"]
在使用全新的控制器模組MetroCluster 進行整個過程之前、您必須先清除現有的組態。

.步驟
. 如有必要、請停止節點以顯示載入程式提示：
+
《停止》

. 在載入程式提示下、將環境變數設定為預設值：
+
「預設值」

. 儲存環境：
+
「aveenv」

. 在載入程式提示下、啟動開機功能表：
+
Boot_ONTAP功能表

. 在開機功能表提示字元中、清除組態：
+
《無花果》

+
請對確認提示回應「是」。

+
節點會重新開機、並再次顯示開機功能表。

. 在開機功能表中、選取選項* 5*以將系統開機至維護模式。
+
請對確認提示回應「是」。





=== 還原HBA組態

視控制器模組中是否有HBA卡及其組態而定、您必須針對站台的使用狀況正確設定這些卡。

.步驟
. 在維護模式中、設定系統中任何HBA的設定：
+
.. 檢查連接埠的目前設定：「ucadmin show」
.. 視需要更新連接埠設定。


+
|===


| 如果您有此類型的HBA和所需模式... | 使用此命令... 


 a| 
CNA FC
 a| 
「ucadmin modify -m光纖信道-t啟動器_adapter-name_」



 a| 
CNA乙太網路
 a| 
「ucadmin modify -mode cna _adapter-name_」



 a| 
FC目標
 a| 
「fcadmin config -t target _adapter-name_」



 a| 
FC啟動器
 a| 
「fcadmin config -t啟動器_adapter-name_」

|===
. 結束維護模式：
+
《停止》

+
執行命令之後、請等到節點停止在載入程式提示字元。

. 將節點開機回「維護」模式、使組態變更生效：
+
Boot_ONTAP maint

. 驗證您所做的變更：
+
|===


| 如果您有這種HBA類型... | 使用此命令... 


 a| 
CNA
 a| 
「ucadmin show」



 a| 
FC
 a| 
「fcadmin show」

|===




=== 在新的控制器和機箱上設定HA狀態

您必須驗證控制器和機箱的HA狀態、並視需要更新狀態以符合您的系統組態。

.步驟
. 在維護模式中、顯示控制器模組和機箱的HA狀態：
+
《ha-config show》

+
所有元件的HA狀態都應該是「mCCIP」。

. 如果顯示的控制器或機箱系統狀態不正確、請設定HA狀態：
+
「ha-config modify控制器mccip」

+
「ha-config modify機箱mccip」

. 停止節點：「halt」
+
節點應在「loader>」提示字元停止。

. 在每個節點上、檢查系統日期、時間和時區：「顯示日期」
. 如有必要、請以UTC或格林尼治標準時間：「et date <mm/dd/ed/yed>'（設定日期<mm/dd/ym/西元年>）」設定日期
. 請在開機環境提示字元中使用下列命令檢查時間：「How Time」（顯示時間）
. 如有必要、請以UTC或格林尼治標準時間設定時間：「設定時間<hh：mm：ss>」
. 儲存設定：「aveenv」
. 收集環境變數：「prontenv」




=== 更新交換器RCF檔案以容納新平台

您必須將交換器更新為支援新平台機型的組態。

.關於這項工作
您可以在包含目前正在升級之控制器的站台上執行此工作。在本程序所示的範例中、我們會先升級se_B。

站台A的交換器將在站台A上的控制器升級時升級。

.步驟
. 準備IP交換器以應用新的RCF檔案。
+
請依照「_EIP MetroCluster 安裝與組態_」一節中有關交換器廠商的步驟進行。

+
link:../install-ip/index.html["安裝與組態MetroCluster"]

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["將Broadcom IP交換器重設為原廠預設值"]
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-cisco-ip-switch-to-factory-defaults["將Cisco IP交換器重設為原廠預設值"]


. 下載並安裝RCF檔案。
+
請依照中交換器廠商的一節中的步驟操作 link:../install-ip/index.html["安裝與組態MetroCluster"]。

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["下載並安裝Broadcom RCF檔案"]
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-cisco-ip-rcf-files["下載並安裝Cisco IP RCF檔案"]






=== 設定MetroCluster 靜態IP bootarg變數

必須MetroCluster 在新的控制器模組上設定特定的靜態IP bootarg值。這些值必須與舊控制器模組上設定的值相符。

.關於這項工作
在此工作中、您將使用先前在升級程序中所識別的UUID和系統ID link:task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html#gathering-information-before-the-upgrade["在升級之前收集資訊"]。

.步驟
. 在「loader>」提示字元中、在s加 載點B的新節點上設定下列bootargs：
+
「etenv bootarg.mC.port_a_ip_config _local-ip-address/local-ip-mask,0、HA合作夥伴-ip-address、DR-partner-ip-address,DR-aux-partnersip-address,vlan-id_」

+
「etenv bootarg.mC.port_b_ip_config _local-ip-address/local-ip-mask,0、HA合作夥伴-ip-address,DR-partner-ip-address,DR-aux-partnersip-address,vlan-id_'」

+
下列範例設定節點 B_1 的值、第一個網路使用 VLAN 120 、第二個網路使用 VLAN 130 ：

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,172.17.26.11,172.17.26.13,172.17.26.12,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,172.17.27.11,172.17.27.13,172.17.27.12,130
----
+
下列範例設定節點 B_2 的值、第一個網路使用 VLAN 120 、第二個網路使用 VLAN 130 ：

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.11/23,0,172.17.26.10,172.17.26.12,172.17.26.13,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.11/23,0,172.17.27.10,172.17.27.12,172.17.27.13,130
----
. 在新節點的「載入器」提示下、設定UUID：
+
"etenv bootarg.mgwd.PARTNER_叢 集_uuid _PARTNER-叢 集-UUID_"

+
「etenv bootarg.mgwd.cluster _uuid _local-cluster -UUID」

+
「etenv bootarg.mCpr_PARTNER_uuid _DR-PARTNER-node-UUUID_」

+
「bootarg.mcc.aux_partner_uuid _DR-aux-合作 夥伴節點-UUUID_」

+
「bootarg.mcc_iscsi.node_uuid _local-node-UUID」

+
.. 在 node_B_1 上設定 UUID 。
+
下列範例顯示在 node_B_1 上設定 UUID 的命令：

+
[listing]
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.aux_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc_iscsi.node_uuid f03cb63c-9a7e-11e7-b68b-00a098908039
----
.. 在 node_B_2 上設定 UUID ：
+
下列範例顯示在 node_B_2 上設定 UUID 的命令：

+
[listing]
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc.aux_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc_iscsi.node_uuid aa9a7a7a-9a81-11e7-a4e9-00a098908c35
----


. 如果原始系統已設定為ADP、請在每個替換節點的載入器提示字元中、啟用ADP：
+
「etenv bootarg.mCa.adp_enabledtrue」

. 設定下列變數：
+
「etenv bootarg.mCs.local_config_id _entite-sys-id_」

+
「etenv bootarg.mCd.dr_PARTNER_DR-PARTNER-sys-id_」

+

NOTE: 。 `setenv bootarg.mcc.local_config_id` 變數必須設為 * 原始 * 控制器模組 node_B_1 的 sys-id 。

+
.. 在 node_B_1 上設定變數。
+
下列範例顯示在 node_B_1 上設定值的命令：

+
[listing]
----
setenv bootarg.mcc.local_config_id 537403322
setenv bootarg.mcc.dr_partner 537403324
----
.. 在 node_B_2 上設定變數。
+
下列範例顯示在 node_B_2 上設定值的命令：

+
[listing]
----
setenv bootarg.mcc.local_config_id 537403321
setenv bootarg.mcc.dr_partner 537403323
----


. 如果使用加密搭配外部金鑰管理程式、請設定所需的bootargs：
+
bootarg.kmip.init.ipaddr`

+
bootarg.kmip.kmip.init.netmask`

+
bootarg.kmip.kmip.init.gateway`

+
bootarg.kmip.kmip.init.interface`





=== 重新指派根Aggregate磁碟

使用先前收集的「sids」、將根Aggregate磁碟重新指派給新的控制器模組

.關於這項工作
此工作會在維護模式中執行。

舊系統ID已在中識別 link:task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html#gathering-information-before-the-upgrade["在升級之前收集資訊"]。

本程序中的範例使用具有下列系統ID的控制器：

|===


| 節點 | 舊系統ID | 新系統ID 


 a| 
節點_B_1
 a| 
4068741254
 a| 
1574774970

|===
.步驟
. 將所有其他連線連接至新的控制器模組（FC-VI、儲存設備、叢集互連等）。
. 停止系統、並從載入程式提示字元開機至維護模式：
+
Boot_ONTAP maint

. 顯示node_B_1-old擁有的磁碟：
+
「展示-A'」

+
命令輸出顯示新控制器模組的系統ID（1574774970）。不過、根Aggregate磁碟仍為舊系統ID（40687441254）所有。此範例並未顯示MetroCluster 由其他節點所擁有的磁碟機、以供使用。

+
[listing]
----
*> disk show -a
Local System ID: 1574774970

  DISK         OWNER                     POOL   SERIAL NUMBER    HOME                      DR HOME
------------   -------------             -----  -------------    -------------             -------------
...
rr18:9.126L44 node_B_1-old(4068741254)   Pool1  PZHYN0MD         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:9.126L49 node_B_1-old(4068741254)   Pool1  PPG3J5HA         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L21 node_B_1-old(4068741254)   Pool1  PZHTDSZD         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L2  node_B_1-old(4068741254)   Pool0  S0M1J2CF         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L3  node_B_1-old(4068741254)   Pool0  S0M0CQM5         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:9.126L27 node_B_1-old(4068741254)   Pool0  S0M1PSDW         node_B_1-old(4068741254)  node_B_1-old(4068741254)
...
----
. 將磁碟機櫃上的根Aggregate磁碟重新指派給新的控制器：
+
"Disk reassign-s _old-sysid_-d _new－sysid_"

+

NOTE: 如果您的 MetroCluster IP 系統已設定進階磁碟分割、則必須執行以納入 DR 合作夥伴系統 ID `disk reassign -s old-sysid -d new-sysid -r dr-partner-sysid` 命令。

+
以下範例顯示磁碟機的重新指派：

+
[listing]
----
*> disk reassign -s 4068741254 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? Jul 14 19:23:49 [localhost:config.bridge.extra.port:error]: Both FC ports of FC-to-SAS bridge rtp-fc02-41-rr18:9.126L0 S/N [FB7500N107692] are attached to this controller.
y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 4068741254.
Do you want to continue (y/n)? y
----
. 檢查是否已按照預期重新指派所有磁碟：
+
「尖碑秀」

+
[listing]
----
*> disk show
Local System ID: 1574774970

  DISK        OWNER                      POOL   SERIAL NUMBER   HOME                      DR HOME
------------  -------------              -----  -------------   -------------             -------------
rr18:8.126L18 node_B_1-new(1574774970)   Pool1  PZHYN0MD        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:9.126L49 node_B_1-new(1574774970)   Pool1  PPG3J5HA        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L21 node_B_1-new(1574774970)   Pool1  PZHTDSZD        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L2  node_B_1-new(1574774970)   Pool0  S0M1J2CF        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:9.126L29 node_B_1-new(1574774970)   Pool0  S0M0CQM5        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L1  node_B_1-new(1574774970)   Pool0  S0M1PSDW        node_B_1-new(1574774970)  node_B_1-new(1574774970)
*>
----
. 顯示Aggregate狀態：
+
「aggr狀態」

+
[listing]
----
*> aggr status
           Aggr            State       Status           Options
aggr0_node_b_1-root        online      raid_dp, aggr    root, nosnap=on,
                           mirrored                     mirror_resync_priority=high(fixed)
                           fast zeroed
                           64-bit
----
. 在合作夥伴節點（node_B_2-new）上重複上述步驟。




=== 啟動新的控制器

您必須從開機功能表重新啟動控制器、才能更新控制器Flash映像。如果已設定加密、則需要執行其他步驟。

您可以重新設定VLAN和介面群組。如有必要、請先手動修改叢集lifs的連接埠和廣播網域詳細資料、再使用「系統控制器置換resume」命令繼續作業。

.關於這項工作
此工作必須在所有新控制器上執行。

.步驟
. 停止節點：
+
《停止》

. 如果已設定外部金鑰管理程式、請設定相關的bootargs：
+
「bootarg.kmip.init.ipaddr _ip-address_」

+
「bootarg.kmip.init.netmask網路遮罩_」

+
「bootarg.kmip.init.gateway gateway-address_」

+
"etenv bootarg.kmip.init.interface _interface-id_"

. 顯示開機功能表：
+
Boot_ONTAP功能表

. 如果使用root加密、請選取金鑰管理組態的開機功能表選項。
+
|===


| 如果您使用... | 選取此開機功能表選項... 


 a| 
內建金鑰管理
 a| 
選項「'10'」

依照提示提供必要的輸入、以恢復及還原金鑰管理程式組態。



 a| 
外部金鑰管理
 a| 
選項「'11'」

依照提示提供必要的輸入、以恢復及還原金鑰管理程式組態。

|===
. 從開機功能表中、執行選項「'6'」。
+

NOTE: 選項「'6'」會在完成之前重新啟動節點兩次。

+
對系統ID變更提示回應「y」。等待第二個重新開機訊息：

+
[listing]
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
+
在選項 "`6" 之後的其中一次重新開機期間、會出現確認提示 `Override system ID? {y|n}` 出現。輸入 `y`。

. 如果使用root加密、請針對金鑰管理組態再次選取開機功能表選項。
+
|===


| 如果您使用... | 選取此開機功能表選項... 


 a| 
內建金鑰管理
 a| 
選項「'10'」

依照提示提供必要的輸入、以恢復及還原金鑰管理程式組態。



 a| 
外部金鑰管理
 a| 
選項「'11'」

依照提示提供必要的輸入、以恢復及還原金鑰管理程式組態。

|===
+
視金鑰管理程式設定而定、請在第一個開機功能表提示字元中選取選項「10」或選項「11」、然後選取選項「6」、以執行還原程序。若要完全開機節點、您可能需要重複選項「1」（正常開機）的恢復程序。

. 開機節點：
+
Boot_ONTAP

. 等待替換的節點開機。
+
如果任一節點處於接管模式、請使用「儲存容錯移轉恢復」命令執行恢復。

. 確認所有連接埠都位於廣播網域中：
+
.. 檢視廣播網域：
+
「網路連接埠廣播網域節目」

.. 視需要將任何連接埠新增至廣播網域。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["從廣播網域新增或移除連接埠"^]

.. 將將叢集間生命體所在的實體連接埠新增至對應的廣播網域。
.. 修改叢集間的LIF、將新的實體連接埠當作主連接埠使用。
.. 在叢集間生命體啟動之後、請檢查叢集對等端點狀態、並視需要重新建立叢集對等端點。
+
您可能需要重新設定叢集對等關係。

+
link:../install-ip/task_sw_config_configure_clusters.html#peering-the-clusters["建立叢集對等關係"]

.. 視需要重新建立VLAN和介面群組。
+
VLAN和介面群組成員資格可能與舊節點不同。

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["建立VLAN"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["結合實體連接埠以建立介面群組"^]

.. 確認合作夥伴叢集可連線、且組態已在合作夥伴叢集上成功重新同步：
+
`metrocluster switchback -simulate true`



. 如果使用加密、請使用適用於金鑰管理組態的正確命令來還原金鑰。
+
|===


| 如果您使用... | 使用此命令... 


 a| 
內建金鑰管理
 a| 
「安全金鑰管理程式內建同步」

如需詳細資訊、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html["還原內建金鑰管理加密金鑰"^]。



 a| 
外部金鑰管理
 a| 
「安全金鑰管理程式外部還原-vserver _svm_-node_node_-key-server _host_name | ip_address: port_-key-id key_id -key-tag key_tag _node-name_」

如需詳細資訊、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html["還原外部金鑰管理加密金鑰"^]。

|===
. 在您恢復作業之前、請確認MetroCluster 已正確設定好功能。檢查節點狀態：
+
「不一樣的秀」MetroCluster

+
確認新節點（站台B）處於*等待站台A的切換狀態*

. 恢復作業：
+
「系統控制器更換恢復」





== 完成升級

自動化作業會執行驗證系統檢查、然後暫停、以便您驗證網路連線能力。驗證之後、資源重新取得階段便會啟動、自動化作業會在站台A切換回、並在升級後檢查時暫停。在您恢復自動化作業之後、它會執行升級後檢查、如果未偵測到錯誤、則會將升級標示為完成。

.步驟
. 請依照主控台訊息來驗證網路連線能力。
. 完成驗證後、請繼續操作：
+
「系統控制器更換恢復」

. 自動化作業會執行 `heal-aggregate`、 `heal-root-aggregate`以及在站台 A 切換作業、以及升級後檢查。當作業暫停時、請手動檢查SAN LIF狀態、並依照主控台訊息來驗證網路組態。
. 完成驗證後、請繼續操作：
+
「系統控制器更換恢復」

. 檢查升級後檢查狀態：
+
「System Controller replace show」（系統控制器更換顯示）

+
如果升級後檢查未報告任何錯誤、則表示升級已完成。

. 完成控制器升級之後、請登入站台B、確認已正確設定更換的控制器。




=== 重新設定 ONTAP Mediator

手動設定 ONTAP Mediator 、此程式會在您開始升級之前自動移除。

. 請執行中的步驟 link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["從ONTAP 一套不實的IP組態設定「不實不作」MetroCluster 服務"]。




=== 還原斷路器監控

如果MetroCluster 先前已將此組態設定為由斷路器軟體進行監控、您可以還原斷路器連線。

. 請執行中的步驟 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/GUID-7259BCA4-104C-49C6-BAD0-1068CA2A3DA5.html["新增MetroCluster 功能"]。




=== 設定端點對端點加密

如果您的系統支援此功能、您可以在 MetroCluster IP 站台之間加密後端流量、例如 NVlog 和儲存複寫資料。請參閱 link:../maintain/task-configure-encryption.html["設定端點對端點加密"] 以取得更多資訊。
