---
permalink: upgrade/task-configure-intercluster-lifs.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, configure, intercluster, lif, dedicated, ports, shared 
summary: 您可以在專用或共享連接埠上設定叢集間的生命體。 
---
= 設定叢集間LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解如何在專用和共享連接埠上設定叢集間的生命體。

[role="tabbed-block"]
====
.在專用連接埠上設定叢集間LIF
--
您可以在專用連接埠上設定叢集間的生命負載、以增加複寫流量的可用頻寬。

.步驟
. 列出叢集中的連接埠：
+
「網路連接埠展示」

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例顯示cluster01中的網路連接埠：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
----
. 判斷哪些連接埠可用於叢集間通訊：
+
「網路介面show -field home-port、curr-port」

+
如需完整的命令語法、請參閱手冊頁。

+
下列範例顯示連接埠「e0e」和「e0f」尚未指派生命區：

+
[listing]
----

cluster01::> network interface show -fields home-port,curr-port
vserver lif                  home-port curr-port
------- -------------------- --------- ---------
Cluster cluster01-01_clus1   e0a       e0a
Cluster cluster01-01_clus2   e0b       e0b
Cluster cluster01-02_clus1   e0a       e0a
Cluster cluster01-02_clus2   e0b       e0b
cluster01
        cluster_mgmt         e0c       e0c
cluster01
        cluster01-01_mgmt1   e0c       e0c
cluster01
        cluster01-02_mgmt1   e0c       e0c
----
. 為專用連接埠建立容錯移轉群組：
+
`network interface failover-groups create -vserver <system_SVM> -failover-group <failover_group> -targets <physical_or_logical_ports>`

+
下列範例將連接埠「e0e」和「e0f」指派給系統SVM「cluster01」上的容錯移轉群組「intercluster01」：

+
[listing]
----
cluster01::> network interface failover-groups create -vserver cluster01 -failover-group
intercluster01 -targets
cluster01-01:e0e,cluster01-01:e0f,cluster01-02:e0e,cluster01-02:e0f
----
. 確認已建立容錯移轉群組：
+
「網路介面容錯移轉群組顯示」

+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster01::> network interface failover-groups show
                                  Failover
Vserver          Group            Targets
---------------- ---------------- --------------------------------------------
Cluster
                 Cluster
                                  cluster01-01:e0a, cluster01-01:e0b,
                                  cluster01-02:e0a, cluster01-02:e0b
cluster01
                 Default
                                  cluster01-01:e0c, cluster01-01:e0d,
                                  cluster01-02:e0c, cluster01-02:e0d,
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
                 intercluster01
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
----
. 在系統SVM上建立叢集間LIF、並將它們指派給容錯移轉群組。
+
[cols="1,3"]
|===


| 版本ONTAP | 命令 


 a| 
9.6及更新版本
 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -service-policy default-intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask> -failover-group <failover_group>`



 a| 
9.5及更早版本
 a| 
`network interface create -vserver system_SVM -lif <LIF_name> -role intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask> -failover-group <failover_group>`

|===
+
如需完整的命令語法、請參閱手冊頁。

+
下列範例會在容錯移轉群組「intercluster01」中建立叢集間LIF「cluster01_icl01」和「cluster01_icl02」：

+
[listing]
----
cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0e -address 192.168.1.201
-netmask 255.255.255.0 -failover-group intercluster01

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0e -address 192.168.1.202
-netmask 255.255.255.0 -failover-group intercluster01
----
. 驗證是否已建立叢集間的LIF：
+
|===


| * ONTAP 在S69.6及更新版本中：* 


 a| 
「網路介面show -service-policy default-intercluster」



| * ONTAP 在《S19.5及更早版本》中：* 


 a| 
「網路介面show -role intercluster」

|===
+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0e     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0f     true
----
. 驗證叢集間的LIF是否為備援：
+
|===


| * ONTAP 在S69.6及更新版本中：* 


 a| 
「網路介面show -service-policy default-intercluster -容 錯移轉」



| * ONTAP 在《S19.5及更早版本》中：* 


 a| 
「網路介面show -role intercluster -容 錯移轉」

|===
+
如需完整的命令語法、請參閱手冊頁。

+
下列範例顯示、SVM「e0e」連接埠上的叢集間LIF「cluster01_icl01」和「cluster01_icl02」將容錯移轉至「e0f」連接埠。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-01:e0e,
                                               cluster01-01:e0f
         cluster01_icl02 cluster01-02:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-02:e0e,
                                               cluster01-02:e0f
----


--
.在共享的資料連接埠上設定叢集間LIF
--
您可以在與資料網路共用的連接埠上設定叢集間的生命體、以減少叢集間網路所需的連接埠數量。

.步驟
. 列出叢集中的連接埠：
+
「網路連接埠展示」

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例顯示cluster01中的網路連接埠：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. 在系統SVM上建立叢集間LIF：
+
|===


| * ONTAP 在S69.6及更新版本中：* 


 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -service-policy default-intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask>`



| * ONTAP 在《S19.5及更早版本》中：* 


 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -role intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask>`

|===
+
如需完整的命令語法、請參閱手冊頁。

+
以下範例建立叢集間的lifs「cluster01_icl01」和「cluster01_icl02」：

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. 驗證是否已建立叢集間的LIF：
+
|===


| * ONTAP 在S69.6及更新版本中：* 


 a| 
「網路介面show -service-policy default-intercluster」



| * ONTAP 在《S19.5及更早版本》中：* 


 a| 
「網路介面show -role intercluster」

|===
+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. 驗證叢集間的LIF是否為備援：
+
|===


| * ONTAP 在S69.6及更新版本中：* 


 a| 
「網路介面show–service-policy default-intercluster -faulty」



| * ONTAP 在《S19.5及更早版本》中：* 


 a| 
「網路介面show -role intercluster -容 錯移轉」

|===
+
如需完整的命令語法、請參閱手冊頁。

+
下列範例顯示、「e0c」連接埠上的叢集間lifs「cluster01_icl01」和「cluster01_icl02」將容錯移轉至「e0d」連接埠。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----


--
====