---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-boot-new-controllers.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 從開機功能表重新啟動控制器，以更新控制器 Flash 映像。如果已設定加密、則需要執行其他步驟。 
---
= 啟動新的 MetroCluster IP 控制器並還原 LIF 組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用命令恢復作業之前，請先開機新控制器，並確認救生裝置裝載於適當的節點和連接埠上 `system controller replace resume`。



== 啟動新控制器

啟動新控制器，確認 bootarg 變數正確無誤，並視需要執行加密還原步驟。

.關於這項工作
此工作必須在所有新控制器上執行。

.步驟
. 停止節點：
+
《停止》

. 如果已設定外部金鑰管理程式、請設定相關的bootargs：
+
`setenv bootarg.kmip.init.ipaddr <ip-address>`

+
`setenv bootarg.kmip.init.netmask <netmask>`

+
`setenv bootarg.kmip.init.gateway <gateway-address>`

+
`setenv bootarg.kmip.init.interface <interface-id>`

. 顯示開機功能表：
+
Boot_ONTAP功能表

. 如果使用root加密、請選取金鑰管理組態的開機功能表選項。
+
|===


| 如果您使用... | 選取此開機功能表選項... 


 a| 
內建金鑰管理
 a| 
選項「'10'」

依照提示提供必要的輸入、以恢復及還原金鑰管理程式組態。



 a| 
外部金鑰管理
 a| 
選項「'11'」

依照提示提供必要的輸入、以恢復及還原金鑰管理程式組態。

|===
. 從開機功能表中、執行選項「'6'」。
+

NOTE: 選項 "'6" 會在程序完成之前重新啟動節點兩次。

+
請以「 y 」回應系統 ID 變更提示。等待第二個重新開機訊息：

+
[listing]
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
+
在選項 "`6" 之後的其中一次重新開機期間、會出現確認提示 `Override system ID? {y|n}` 出現。輸入 `y`。

. 如果使用root加密、請針對金鑰管理組態再次選取開機功能表選項。
+
|===


| 如果您使用... | 選取此開機功能表選項... 


 a| 
內建金鑰管理
 a| 
選項「'10'」

依照提示提供必要的輸入、以恢復及還原金鑰管理程式組態。



 a| 
外部金鑰管理
 a| 
選項「'11'」

依照提示提供必要的輸入、以恢復及還原金鑰管理程式組態。

|===
+
視金鑰管理程式設定而定、請在第一個開機功能表提示字元中選取選項「10」或選項「11」、然後選取選項「6」、以執行還原程序。若要完全開機節點、您可能需要重複選項「1」（正常開機）的恢復程序。

. 開機節點：
+
Boot_ONTAP

. 等待替換的節點開機。
+
如果任一節點處於接管模式、請使用「儲存容錯移轉恢復」命令執行恢復。

. 確認所有連接埠都位於廣播網域中：
+
.. 檢視廣播網域：
+
「網路連接埠廣播網域節目」

.. 如果為新升級的控制器上的資料連接埠建立新的廣播網域、請刪除廣播網域：
+

NOTE: 只刪除新的廣播網域。開始升級之前、請勿刪除任何已存在的廣播網域。

+
`broadcast-domain delete -broadcast-domain <broadcast_domain_name>`

.. 視需要將任何連接埠新增至廣播網域。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["新增或移除廣播網域中的連接埠"^]

.. 將將叢集間生命體所在的實體連接埠新增至對應的廣播網域。
.. 修改叢集間的LIF、將新的實體連接埠當作主連接埠使用。
.. 在叢集間生命體啟動之後、請檢查叢集對等端點狀態、並視需要重新建立叢集對等端點。
+
您可能需要重新設定叢集對等關係。

+
link:../install-ip/task_sw_config_configure_clusters.html#peering-the-clusters["建立叢集對等關係"]

.. 視需要重新建立VLAN和介面群組。
+
VLAN和介面群組成員資格可能與舊節點不同。

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["建立 VLAN"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["結合實體連接埠以建立介面群組"^]

.. 確認合作夥伴叢集可連線、且組態已在合作夥伴叢集上成功重新同步：
+
`metrocluster switchback -simulate true`



. 如果使用加密、請使用適用於金鑰管理組態的正確命令來還原金鑰。
+
|===


| 如果您使用... | 使用此命令... 


 a| 
內建金鑰管理
 a| 
「安全金鑰管理程式內建同步」

如需更多資訊、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html["還原內建金鑰管理加密金鑰"^]。



 a| 
外部金鑰管理
 a| 
`security key-manager external restore -vserver <svm-name> -node <node-name> -key-server <host_name|IP_address:port> -key-id <key_id> -key-tag key_tag <node-name>`

如需更多資訊、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html["還原外部金鑰管理加密金鑰"^]。

|===
. 確認 MetroCluster 設定正確。檢查節點狀態：
+
「不一樣的秀」MetroCluster

+
確認新節點（站台B）處於*等待站台A的切換狀態*





== 驗證並還原LIF組態

在您繼續執行自動切換作業之前，請先確認已在適當的節點上裝載了生命。

.關於這項工作
* 此工作是在ssite B上執行



CAUTION: 在執行切換之前，您必須確認新節點上的資料生命負載位置正確。當您切換組態時， ONTAP 會嘗試恢復由生命所使用的主連接埠上的流量。當主連接埠連線至交換器連接埠和 VLAN 不正確時，可能會發生 I/O 故障。

.步驟
. 在切換之前，請先確認已在適當的節點和連接埠上裝載了生命負載。
+
.. 變更為進階權限層級：
+
"進階權限"

.. 顯示生命，並確認每個資料 LIF 使用正確的主連接埠：
+
「網路介面展示」

.. 修改任何未使用正確主連接埠的生命：
+
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`

+
如果命令傳回錯誤，您可以覆寫連接埠組態：

+
`vserver config override -command "network interface modify -vserver <svm-name> -home-port <active_port_after_upgrade> -lif <lif_name> -home-node <new_node_name>"`

+
在「vserver config override」命令中輸入network interface modify命令時、您無法使用分頁自動完成功能。您可以使用autosplete建立網路「介面修改」、然後將其括在「vserver config override」命令中。

.. 確認所有資料生命現在都位於正確的主連接埠：
+
「網路介面展示」

.. 返回管理權限層級：
+
「et -priv. admin」



. 將介面還原至其主節點：
+
`network interface revert * -vserver <svm-name>`

+
視需要在所有SVM上執行此步驟。

. 恢復作業：
+
「系統控制器更換恢復」



.接下來呢？
link:upgrade-mcc-ip-system-controller-replace-complete-upgrade.html["完成控制器升級"]。
