---
permalink: upgrade/upgrade-mcc-ip-manual-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc, bootarg 
summary: 升級至 ONTAP 9.15.1 或更新版本所推出的系統時，您必須先設定引導程序，才能繼續進行控制器升級。 
---
= 設定所需的 bootarg （用於將 MetroCluster IP 升級至 ONTAP 9.15.1 或更新版本所推出的系統）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要升級到ONTAP 9.15.1 或更高版本中引入的系統，通常需要在舊控制器上設定啟動參數，然後才能開始升級。


NOTE: 如果您的升級組合受到影響，則需要在所有舊控制器上設定啟動參數才能成功升級。仔細閱讀本節中的信息，檢查您的升級組合是否要求您設定啟動參數，以及如何為您的組合設定正確的啟動參數。



== 步驟 1：確定是否需要在舊控制器上設定 bootarg

使用以下資訊檢查在開始升級之前是否需要設定所需的 bootarg：

* 除非另有說明，否則您*必須*在舊控制器上設定啟動參數才能支援以下系統的升級：
+
** AFF A70 、 AFF A90 、 AFF A1K
** FAS70 、 FAS90
** AFF C80
** AFF A50 、 AFF A20 、 AFF A30
** AFF C30 、 AFF C60
** FAS50


* 如果您的升級是以下組合之一，則您不需要在舊控制器上設定任何啟動參數：
+
** 從AFF A70系統到AFF A90系統
** 從 FAS70 系統到 FAS90 系統





CAUTION: 如果你的升級不需要設定任何啟動參數，你可以跳過此任務並直接前往link:upgrade-mcc-ip-prepare-system.html["準備系統以進行升級"]。



== 步驟 2：確定需要在舊控制器上設定的啟動參數

大多數受影響的升級需要您設置 `hw.cxgbe.toe_keepalive_disable`舊控制器上的 bootarg。但是，某些升級路徑要求您設定 `bootarg.siw.interop_enabled`而是使用 bootarg。

請使用下表來判斷您需要為特定升級組合設定哪些 bootarg 。

[cols="2*"]
|===
| 針對此升級 ... | 設定 bootarg... 


| 從 AFF A250 到 AFF A30 | `bootarg.siw.interop_enabled` 


| 從 AFF C250 到 AFF C30 | `bootarg.siw.interop_enabled` 


| 從 AFF A150 到 AFF A20 | `bootarg.siw.interop_enabled` 


| 從 AFF A220 到 AFF A20 | `bootarg.siw.interop_enabled` 


 a| 
對AFF A70、 AFF A90、 AFF A1K、FAS70、FAS90、 AFF C80、 AFF A50、 AFF A30、 AFF C30、 AFF C60 或 FAS50 系統的所有其他升級

*注意：*如果從AFF A70升級到AFF A90系統或從 FAS70 升級到 FAS90 系統，則無需設定任何引導參數。
| `hw.cxgbe.toe_keepalive_disable` 
|===


== 步驟 3：在舊控制器上設定所需的啟動參數

確定升級組合所需的 bootarg 後，請依照步驟在舊控制器上設定 bootarg。此任務*僅*適用於受影響的升級。


NOTE: 在開始升級之前，必須在兩個網站的所有舊節點上設定 bootarg。

.步驟
. 在兩個站台停止一個節點，並允許其 HA 合作夥伴對節點執行儲存接管：
+
`halt  -node <node_name>`

. 為您的升級組合設定所需的 bootarg 。您已經確定了需要使用中的表設置的 bootarg <<upgrade_paths_bootarg_manual,判斷您需要設定的 bootarg>>。
+
[role="tabbed-block"]
====
.HW.cxgbe 。 Toe_keepalive_disable
--
.. 在 `LOADER` 停止節點的提示下、輸入下列內容：
+
`setenv hw.cxgbe.toe_keepalive_disable 1`

+
「aveenv」

+
`printenv hw.cxgbe.toe_keepalive_disable`



--
.bootarg.siw.interop_enabled
--
.. 在 `LOADER` 停止節點的提示下、輸入下列內容：
+
`setenv bootarg.siw.interop_enabled 1`

+
「aveenv」

+
`printenv bootarg.siw.interop_enabled`



--
====
. 開機節點：
+
Boot_ONTAP

. 當節點開機時、請在提示下執行節點的恢復：
+
`storage failover giveback -ofnode <node_name>`

. 在要升級的 DR 群組或 DR 群組中的所有節點上重複這些步驟。


.接下來呢？
link:upgrade-mcc-ip-prepare-system.html["準備系統以進行升級"]。
