---
permalink: upgrade/upgrade-mcc-ip-prepare-system.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 在對現有MetroCluster 的版本進行任何變更之前、您必須檢查組態的健全狀況、準備新平台、以及執行其他雜項工作。 
---
= 準備 MetroCluster IP 系統以進行升級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在對現有 MetroCluster 組態進行任何變更之前，請先檢查組態的健全狀況，準備新平台，並執行其他雜項工作。



== 在升級控制器之前，請先更新 MetroCluster 交換器 RCFs

視舊版與新版平台機型而定，您可能需要在升級控制器之前更新 MetroCluster 交換器參考組態檔（ RCFs ）。

.關於這項工作
在下列情況下執行此工作：

* 交換器 RCF 組態並非最低版本。
* 您需要變更後端 MetroCluster 連線所使用的 VLAN ID 。


.開始之前
在升級控制器之前，判斷是否需要更新 RCFs ：

* 如果交換器組態未設定支援的最小 RCF 版本，則您必須在升級控制器之前更新 RCF ：
+
|===


| 交換器模式 | 必要的 RCF 版本 


 a| 
Cisco 3132Q-V
 a| 
1.7或更新版本



 a| 
Cisco 3232C
 a| 
1.7或更新版本



 a| 
Broadcom Bes - 53248
 a| 
1.3或更新版本



 a| 
NVIDIA SN2100
 a| 
2.0 或更新版本

|===
* 如果您的舊平台和新平台機型都列在下列清單中，則在升級控制器之前 * 不 * 需要更新 VLAN ID ：
+
** FAS8200 或 AFF A300
** 解答320 AFF
** FAS9000 或 AFF A700
** AFF A800 ， AFF C800 ， ASA A800 或 ASA C800
+
如果您的舊版或新版平台機型未列於上方，您必須確認 MetroCluster 介面使用的是支援的 VLAN ID 。MetroCluster 介面支援的 VLAN ID 為： 10 ， 20 或介於 101 到 4096 之間。

+
[CAUTION]
====
*** 如果 VLAN ID 不是 10 ， 20 或介於 101 到 4096 之間，則必須在升級控制器之前升級交換器 RCF 。
*** 本機叢集連線可以使用任何 VLAN ，不需要位於指定範圍內。
*** 您要升級的新 RCF 必須使用 VLAN 10 ， 20 或介於 101 到 4096 之間。除非需要，否則請勿變更本機叢集的 VLAN 。


====




.步驟
. 準備 IP 交換器以應用新的 RCFs 。
+
請依照您的交換器廠商章節中的步驟進行：

+

NOTE: 您應該依照下列順序更新交換器： switch_a_1 ， switch_B_1 ， switch_a_2 ， switch_B_2 。

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["將Broadcom IP交換器重設為原廠預設值"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["將 Cisco IP 交換器重設為原廠預設值"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["將NVIDIA IP SN2100交換器重設為原廠預設值"]


. 下載並安裝 RCFs 。
+
請依照您的交換器廠商章節中的步驟進行：

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["下載並安裝 Broadcom RCFs"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["下載並安裝 Cisco IP RCFs"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["下載並安裝 NVIDIA IP RCFs"]






== 將舊節點的連接埠對應至新節點

您必須驗證 node_a_1-old 上的實體連接埠是否正確對應至 node_a_1-new 上的實體連接埠。這可讓 node_a_1-new 在升級後與叢集中的其他節點和網路進行通訊。

.關於這項工作
當新節點在升級程序期間首次開機時，它會重新執行其所取代的舊節點的最新組態。當您開機node_a_1-new時ONTAP 、支援功能會嘗試在節點_a_1-old上使用的相同連接埠上裝載lifs。這表示您必須在升級過程中調整連接埠和 LIF 組態，使其與舊節點的組態相容。在升級程序期間，您可以在舊節點和新節點上執行步驟，以確保叢集，管理和資料生命體的組態正確

下表顯示與新節點的連接埠需求相關的組態變更範例。

|===


3+| 叢集互連實體連接埠 


| 舊控制器 | 新控制器 | 必要行動 


 a| 
e0a、e0b
 a| 
E3A、e3b
 a| 
無相符的連接埠。升級後，您必須重新建立叢集連接埠。



 a| 
e0c、e0d
 a| 
e0a、e0b、e0c、e0d
 a| 
e0c和e0d是相符的連接埠。您不需要變更組態，但在升級之後，您可以將叢集的生命分散到可用的叢集連接埠。

|===
.步驟
. 確定新控制器上可用的實體連接埠、以及連接埠上可裝載的LIF。
+
控制器的連接埠使用量取決於平台模組、以及MetroCluster 您將使用哪些交換器來進行靜態IP組態。您可以從收集新平台的連接埠使用量link:https://hwu.netapp.com["Hardware Universe"^]。

. 規劃連接埠使用量、並填寫下列表格、以供每個新節點參考。
+
執行升級程序時、請參閱表格。

+
|===


|  3+| node_a_1-old 3+| node_a_1-new 


| LIF | 連接埠 | IPspaces | 廣播網域 | 連接埠 | IPspaces | 廣播網域 


 a| 
叢集1
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
叢集2
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
叢集3
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
叢集4.
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
節點管理
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
叢集管理
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
資料1.
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
資料2.
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
資料3.
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
資料4.
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
SAN
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
叢集間連接埠
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 

|===




== 以網路開機新的控制器

安裝新節點之後、您需要netboot才能確保新節點執行的ONTAP 版本與原始節點相同。「netboot」一詞是指您從ONTAP 儲存在遠端伺服器上的不實映像進行開機。準備網路開機時、您必須將ONTAP 一份《支援》9開機映像複本放到系統可以存取的網路伺服器上。

.步驟
. 新控制器的網路開機：
+
.. 存取 link:https://mysupport.netapp.com/site/["NetApp 支援網站"^] 可下載用於執行系統netboot的文件。
.. 請ONTAP 從NetApp支援網站的軟體下載區段下載適當的支援軟體、並將「ONTAP-VERW_image.tgz」檔案儲存在可從網路存取的目錄中。
.. 切換至網路存取目錄、並確認您所需的檔案可用。
+
您的目錄清單應包含一個含有核心檔案的netboot資料夾：

+
點選「ONTAP版本映像」

+
您不需要解壓縮 `_ontap-version_image.tgz`檔案。

.. 在 `LOADER` 提示字元下、設定管理 LIF 的 netboot 連線：
+
|===


| 如果IP定址是... | 然後... 


 a| 
DHCP
 a| 
設定自動連線：

「ifconfige0M -auto」



 a| 
靜態
 a| 
設定手動連線：

「ifconfige0M -addr=_ip_addr_-mask=_netmask_-gateway_`

|===
.. 執行netboot。
+
“netboot \http://_web_server_ip/path_to_web-accessible_directory/ontap-version_image.tgz`

.. 從開機功能表中、選取選項「*（7）先安裝新軟體*」、將新的軟體映像下載並安裝到開機裝置。
+
請忽略下列訊息：

+
「此程序不支援HA配對上的不中斷升級」。它適用於軟體的不中斷升級、而非控制器的升級。

.. 如果系統提示您繼續此程序、請輸入「y」、並在系統提示您輸入套件時、輸入映像檔的URL：
+
http://__web_server_ip/path_to_web-accessible_directory/ontap-version___image.tgz`

.. 輸入使用者名稱和密碼（若適用）、或按Enter繼續。
.. 當您看到類似下列的提示時、請務必輸入「n」以跳過備份恢復：
+
[listing]
----
Do you want to restore the backup configuration now? {y|n} n
----
.. 當您看到類似於以下內容的提示時、請輸入「* y *」重新開機：
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----






== 清除控制器模組上的組態

在使用全新的控制器模組MetroCluster 進行整個過程之前、您必須先清除現有的組態。

.步驟
. 如有必要，請停止節點以顯示 `LOADER`提示：
+
《停止》

. 在 `LOADER`提示字元下，將環境變數設為預設值：
+
「預設值」

. 儲存環境：
+
「aveenv」

. 在 `LOADER`提示字元下，啟動開機功能表：
+
Boot_ONTAP功能表

. 在開機功能表提示字元中、清除組態：
+
《無花果》

+
請對確認提示回應「是」。

+
節點會重新開機、並再次顯示開機功能表。

. 在開機功能表中、選取選項* 5*以將系統開機至維護模式。
+
請對確認提示回應「是」。





== 在現場升級之前、請先驗MetroCluster 證其健全狀況

在執行升級之前、您必須先驗證MetroCluster 整個過程的健全狀況和連線能力。

.步驟
. 驗證MetroCluster 下列項目中的功能：ONTAP
+
.. 檢查節點是否為多路徑： +
`node run -node <node_name> sysconfig -a`
+
為 MetroCluster 組態中的每個節點發出此命令。

.. 驗證組態中沒有損壞的磁碟：+「磁碟顯示-中斷」
+
在 MetroCluster 組態中的每個節點上發出此命令。

.. 檢查是否有任何健全狀況警示：
+
「系統健全狀況警示顯示」

+
在每個叢集上發出此命令。

.. 驗證叢集上的授權：
+
「系統授權展示」

+
在每個叢集上發出此命令。

.. 驗證連接至節點的裝置：
+
「網路裝置探索秀」

+
在每個叢集上發出此命令。

.. 確認兩個站台的時區和時間設定正確：
+
「叢集日期顯示」

+
在每個叢集上發出此命令。您可以使用 `cluster date`命令來設定時間和時區。



. 確認MetroCluster 執行功能不正常的操作模式、並執行MetroCluster 功能不實的檢查。
+
.. 確認MetroCluster 此功能的組態、操作模式為「正常」：+ MetroCluster 「show」
.. 確認所有預期的節點均顯示：+「MetroCluster 不實節點顯示」
.. 發出下列命令：
+
《不一樣的跑程》MetroCluster

.. 顯示MetroCluster 檢查結果：
+
《不一樣的表演》MetroCluster



. 使用MetroCluster 「資訊工具」檢查「資訊系統」的纜線。Config Advisor
+
.. 下載並執行Config Advisor 更新。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"]

.. 執行Config Advisor 完功能後、請檢閱工具的輸出結果、並依照輸出中的建議來解決發現的任何問題。






== 在升級之前收集資訊

在升級之前、您必須先收集每個節點的資訊、並視需要調整網路廣播網域、移除任何VLAN和介面群組、以及收集加密資訊。

.步驟
. 記錄每個節點的實體纜線、視需要標示纜線、以便正確連接新節點。
. 收集每個節點的互連，連接埠和 LIF 資訊。
+
收集每個節點的下列命令輸出：

+
** 《不互連秀》MetroCluster
** 「組態設定連線顯示」MetroCluster
** 「網路介面show -role叢集、node-mgmt」
** `network port show -node <node_name> -type physical`
** `network port vlan show -node <node_name>`
** `network port ifgrp show -node <node_name> -instance`
** 「網路連接埠廣播網域節目」
** 「網路連接埠連線能力顯示-詳細資料」
** 「網路IPSpace節目」
** 「Volume show」
** 《集合體展》
** `system node run -node <node_name> sysconfig -a`
** `aggr show -r`
** 「尖碑秀」
** `system node run <node-name> disk show`
** `vol show -fields type`
** `vol show -fields type , space-guarantee`
** 「Vserver FCP啟動器顯示」
** 「磁碟展示」
** 「顯示組態設定介面」MetroCluster


. 收集站台B（目前正在升級其平台的站台）的UUID：
+
「MetroCluster 節點show -功能 變數node-叢 集-uuid、node-uuid」

+
這些值必須在新的站台控制器模組上正確設定、以確保成功升級。將這些值複製到檔案中，以便稍後在升級程序中複製到命令中。

+
下列範例顯示含有UUID的命令輸出：

+
[listing]
----
cluster_B::> metrocluster node show -fields node-cluster-uuid, node-uuid
  (metrocluster node show)
dr-group-id cluster     node   node-uuid                            node-cluster-uuid
----------- --------- -------- ------------------------------------ ------------------------------
1           cluster_A node_A_1 f03cb63c-9a7e-11e7-b68b-00a098908039 ee7db9d5-9a82-11e7-b68b-00a098908039
1           cluster_A node_A_2 aa9a7a7a-9a81-11e7-a4e9-00a098908c35 ee7db9d5-9a82-11e7-b68b-00a098908039
1           cluster_B node_B_1 f37b240b-9ac1-11e7-9b42-00a098c9e55d 07958819-9ac6-11e7-9b42-00a098c9e55d
1           cluster_B node_B_2 bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f 07958819-9ac6-11e7-9b42-00a098c9e55d
4 entries were displayed.
cluster_B::*
----
+
NetApp 建議您將 UUID 記錄在類似下列的表格中：

+
|===


| 叢集或節點 | UUID 


 a| 
叢集_B
 a| 
07958819-9ac6-11e7-9b42-00a098c9e55d



 a| 
節點_B_1
 a| 
f37b240b-9ac1-11e7-9b42-00a098c9e55d



 a| 
節點_B_2
 a| 
bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f



 a| 
叢集_A
 a| 
ee7db9d5-9a82-11e7-b68b-00a098908039



 a| 
node_a_1
 a| 
f03cb63c-9a7e-11e7-b68b-00a098908039



 a| 
節點_a_2
 a| 
aa9a7a7a-9a81-11e7-a4e9-00a098908c35

|===
. 如果MetroCluster 支援SAN組態、請收集相關資訊。
+
收集下列命令的輸出：

+
** 「FCP介面卡顯示-instance」
** 「FCP介面show -instance」
** 「iSCSI介面展示」
** 「ucadmin show」


. 如果根磁碟區已加密，請收集並儲存金鑰管理員使用的密碼：
+
「安全金鑰管理程式備份展示」

. 如果MetroCluster 這個節點正在使用磁碟區或集合體的加密功能、請複製金鑰和複製密碼的相關資訊。
+
如需更多資訊、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-1677AE0A-FEF7-45FA-8616-885AA3283BCF.html["手動備份內建金鑰管理資訊"]。

+
.. 如果已設定Onboard Key Manager：+「安全金鑰管理程式內建show-Backup」
+
您需要在升級程序稍後的複雜密碼。

.. 如果已設定企業金鑰管理（KMIP）、請發出下列命令：
+
「安全金鑰管理程式外部show -instance」「安全金鑰管理程式金鑰查詢」



. 收集現有節點的系統ID：
+
「MetroCluster 這個節點顯示欄位節點系統ID、ha-合作 夥伴系統ID、dr-Partner SystemID、dr輔助系統ID」

+
下列輸出顯示重新指派的磁碟機。

+
[listing]
----
::> metrocluster node show -fields node-systemid,ha-partner-systemid,dr-partner-systemid,dr-auxiliary-systemid

dr-group-id cluster     node     node-systemid ha-partner-systemid dr-partner-systemid dr-auxiliary-systemid
----------- ----------- -------- ------------- ------------------- ------------------- ---------------------
1           cluster_A node_A_1   537403324     537403323           537403321           537403322
1           cluster_A node_A_2   537403323     537403324           537403322           537403321
1           cluster_B node_B_1   537403322     537403321           537403323           537403324
1           cluster_B node_B_2   537403321     537403322           537403324           537403323
4 entries were displayed.
----




== 移除內管或斷路器監控

在升級平台之前、如果MetroCluster 使用斷路器或調解器公用程式監控了該組態、您必須先移除監控。

.步驟
. 收集下列命令的輸出：
+
「iSCSI啟動器展示」

. 移除MetroCluster 可啟動切換功能的斷路器、調解器或其他軟體中現有的物件組態。
+
|===


| 如果您使用... | 使用此程序... 


 a| 
Tiebreaker
 a| 
link:../tiebreaker/concept_configuring_the_tiebreaker_software.html#removing-metrocluster-configurations["移除MetroCluster 部分組態"]



 a| 
中介者
 a| 
從資訊提示字元發出下列命令ONTAP ：

「取消組態設定中介程式」MetroCluster



 a| 
第三方應用程式
 a| 
請參閱產品文件。

|===




== 在維護前傳送自訂AutoSupport 的支援訊息

在執行維護之前、您應發出AutoSupport 一份不知所知的訊息、通知NetApp技術支援部門正在進行維護。告知技術支援部門正在進行維護、可防止他們假設發生中斷、而開啟案例。

.關於這項工作
此工作必須在每MetroCluster 個站台上執行。

.步驟
. 登入叢集。
. 叫出AutoSupport 指示維護開始的消息：
+
「系統節點AutoSupport 不支援節點*-type all -most maints=_maintening-window-in-thing__」

+
"maintenance window-in-hours（維護時間間隔）"參數指定維護時間的長度、最長可達72小時。如果維護作業在時間結束之前完成、您可以叫用AutoSupport 指示維護期間結束的資訊消息：

+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」

. 在合作夥伴網站上重複這些步驟。


.接下來呢？
link:upgrade-mcc-ip-manual-switchover.html["切換MetroCluster 整個過程"]。
