---
permalink: tiebreaker/concept_configuring_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: installation, tiebreaker, software, add, modify, metrocluster, configuration, remove, configuring, configure, launch, cli, add, command, modify, removing 
summary: 安裝了Tiebreaker軟體之後、您可以新增或修改MetroCluster 任何版本的物件組態、或是從Tiebreaker軟體中移除這些組態。 
---
= 配置MetroCluster決勝軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝了Tiebreaker軟體之後、您可以新增或修改MetroCluster 任何版本的物件組態、或是從Tiebreaker軟體中移除這些組態。



== 啟動 Tiebreaker 軟體 CLI

安裝Tiebreaker軟體之後、您必須啟動其CLI來設定軟體。

. 從安裝軟體的主機提示字元啟動CLI：
+
《NetApp-MetroCluster-tiebreer-software-cli》

. 安裝完成後、第一次啟動時、請輸入密碼、讓Tiebreaker使用者存取資料庫。這是您在安裝期間為資料庫使用者指定的密碼。




== 新增MetroCluster 功能

安裝完NetApp MetroCluster 斷點器軟體之後、您可以一MetroCluster 次新增更多的一套功能。

.關於這項工作
* 您必須已在MetroCluster 一個不支援的環境中安裝了這個支援功能、ONTAP 並啟用軟體中的設定。
* 具體步驟和預期命令輸出取決於您執行的 Tiebreaker 版本。


[role="tabbed-block"]
====
.決勝局 1.5 或更早
--
.步驟
. 使用tiebreaker命令列介面（CLI）監控器add命令來新增MetroCluster 物件組態。
+
如果您使用的是主機名稱、則必須是完整網域名稱（FQDN）。

+
下列範例顯示叢集A的組態：

+
.範例
[%collapsible]
=====
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter monitor Name: <monitor_name>
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
----
=====
. 使用MetroCluster tiebreaker CLI "monitorer show -STATUS"命令、確認已正確新增此功能。
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. 停用斷路器軟體的觀察模式、以便在偵測到站台故障後自動啟動切換：
+
`monitor modify -monitor-name <monitor_name> -observer-mode false`

+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name 8pack -observer-mode false
Warning: If you are turning observer-mode to false, make sure to review the 'risks and limitations'
as described in the MetroCluster Tiebreaker installation and configuration.
Are you sure you want to enable automatic switchover capability for monitor "8pack"? [Y/N]: y
----


--
.Tiebreaker 1.6 或更新版本
--
.步驟
. 使用tiebreaker命令列介面（CLI）監控器add命令來新增MetroCluster 物件組態。
+
如果您使用的是主機名稱、則必須是完整網域名稱（FQDN）。

+
下列範例顯示叢集A的組態：

+
.範例
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter Monitor Name: cluster_A
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Peer Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:

 NOTE: Before enabling automatic switchover capability, make sure to review the 'risks and limitations' as described in the MetroCluster Tiebreaker Installation and Configuration Guide.

Do you want to enable automatic switchover capability for monitor(Y/N): y
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
Verifying SSL certificate chain from cluster_A...

===============================================
Warning missing SSL certificates
===============================================

Cluster: cluster_A

IP Address: <cluster_ip_value>

Result:

The MetroCluster Tiebreaker is unable to verify the SSL certificate chain.

Recommended Actions:

Run the following command to identify missing certificates:

monitor switchover-simulate

Import any missing certificates as indicated by the command output.

For detailed instructions, please refer to the MetroCluster Tiebreaker documentation, or contact NetApp Support for assistance.

Note:

Missing certificates will prevent the MetroCluster Tiebreaker from issuing a switchover request in the event of a site failure.

================================================================================================================================
Verifying SSL certificate chain from cluster_B...

SSL certificate chain is valid
----
=====
. 使用MetroCluster tiebreaker CLI "monitorer show -STATUS"命令、確認已正確新增此功能。
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. 請依照適用於您的 Tiebreaker 版本的步驟匯入缺少的憑證。<<import-certificates-tb17,進口證書>> 。


--
====
.相關資訊
link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["在MetroCluster 作用中模式中使用ESITirepreaker的風險和限制"]



== 進口證書

若要在 Tiebreaker 1.6 或更高版本中啟用無縫監控，您需要將伺服器安全通訊端層 (SSL) 憑證、中間憑證（如果存在）和根憑證從ONTAP匯入到 Java 虛擬機器 (JVM) 中的金鑰庫。

.關於這項工作
* 此任務在 Tiebreaker 1.6 或更高版本中是必需的。
* 成功將MetroCluster配置新增至 Tiebreaker 後，或在憑證過期後，您需要執行此任務。
* 在 Tiebreaker 1.7 或更高版本中，您可以執行切換模擬來檢查是否需要匯入憑證。如果切換模擬失敗，則需要將憑證從ONTAP匯入到 Java 虛擬機器 (JVM) 中的金鑰庫。


[role="tabbed-block"]
====
.決勝規則 1.7 或更高版本
--
.步驟
. 執行切換模擬以檢查是否需要導入憑證。
+
.. 查看決勝局監控狀態：
`monitor show -status`
+
.範例
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. 觸發切換模擬：
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
如果需要將憑證匯入 JVM，則該命令將傳回下列輸出：

+
[listing]
----
Failed to trigger Switchover Simulation. Please check Metrocluster Tiebreaker logs for further information or contact NetApp support.
----


. 對需要匯入的每個憑證（SSL 伺服器憑證、中間憑證或根憑證）執行以下命令。
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** 這 `<certificate_file_name>` value 指定要匯入的憑證的檔案名稱。
** 這 `-alias <certificate>` value 指定將憑證匯入 JVM 後要儲存的名稱。
+
以下範例展示如何匯入檔案名為「root certificate」的根憑證。 `root.crt` 以及檔案名稱 `ssl_cert.crt`：

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. 重啟決勝程式軟體：
+
`systemctl restart netapp-metrocluster-tiebreaker-software`

. 再次執行切換模擬檢查：
+
.. 查看決勝局監控狀態：
`monitor show -status`
+
.範例
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. 觸發切換模擬：
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
[listing]
----
Successfully triggered Switchover Simulation. Please check the status of the Switchover Simulation on the ONTAP cluster using command "metrocluster operation history show"
----




--
.平手決勝 1.6 或 1.6P1
--
.步驟
. 從ONTAP導入所有憑證。對需要匯入的每個憑證（SSL 伺服器憑證、中間憑證或根憑證）執行以下命令。
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** 這 `<certificate_file_name>` value 指定要匯入的憑證的檔案名稱。
** 這 `-alias <certificate>` value 指定將憑證匯入 JVM 後要儲存的名稱。
+
以下範例展示如何匯入檔案名為「root certificate」的根憑證。 `root.crt` 以及檔案名稱 `ssl_cert.crt`：

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. 重啟決勝程式軟體：
+
`systemctl restart netapp-metrocluster-tiebreaker-software`



--
====


== 修改MetroCluster 斷點器組態的命令

您可以在MetroCluster 需要變更設定時修改此功能的組態。

Tiebreaker CLI監控修改命令可搭配下列任一選項使用。您可以使用監控show -STATUS命令來確認變更。

[cols="30,70"]
|===


| 選項 | 說明 


 a| 
-監 控名稱
 a| 
系統名稱MetroCluster



 a| 
-enable監控
 a| 
啟用和停用MetroCluster 監控功能



 a| 
無訊息期間
 a| 
在偵測到站台故障後、由斷位器軟體等待確認的期間（以秒為單位）MetroCluster



 a| 
觀察者模式
 a| 
觀察者模式（true）僅提供監控功能、不會在站台發生災難時觸發切換。線上模式（假）會在站台發生災難時觸發切換。

* link:concept_overview_of_the_tiebreaker_software.html["Tiebreaker軟體如何偵測站台故障"]
* link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["在MetroCluster 作用中模式中使用ESITirepreaker的風險和限制"]


|===
下列範例會變更組態的無訊息期間。

[listing]
----

NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name cluster_A -silent-period 15
Successfully modified monitor in NetApp MetroCluster Tiebreaker
software.
----
tiebreaker CLI的「debug」命令可用來變更記錄模式。

[cols="30,70"]
|===


| 命令 | 說明 


 a| 
偵錯狀態
 a| 
顯示偵錯模式的狀態



 a| 
啟用偵錯
 a| 
啟用記錄的偵錯模式



 a| 
停用偵錯
 a| 
停用記錄的偵錯模式

|===
在執行tiebreaker 1.4及更早版本的系統中、tiebreaker CLI `update-mcctb-password` 命令可用於更新使用者密碼。此命令已在tiebreaker 1.5及更新版本中過時。

[cols="30,70"]
|===


| 命令 | 說明 


 a| 
update-mcctb-password
 a| 
使用者密碼已成功更新

|===


== 移除MetroCluster 不完整的組態

當MetroCluster 您不想再監控MetroCluster 某個非重複組態時、可以移除正在由斷路器軟體監控的非重複組態。

. 使用tiebreaker CLI "monitor" remove"命令來移除MetroCluster 該組態。
+
在下列範例中、「叢集_a'」會從軟體中移除：

+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor remove -monitor-name cluster_A
Successfully removed monitor from NetApp MetroCluster Tiebreaker
software.
----
. 使用tiebreaker CLI "monitorer show -STATUS"命令、確認MetroCluster 已正確移除該組態。
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----

