---
permalink: tiebreaker/install_tiebreaker_package.html 
sidebar: sidebar 
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database 
summary: 在主機 Linux 作業系統上執行新的安裝或升級至 tiebreaker 1.5 、以監控 MetroCluster 組態。 
---
= 安裝或升級至 tiebreaker 1.5
:allow-uri-read: 


[role="lead"]
在主機 Linux 作業系統上執行新的安裝或升級至 tiebreaker 1.5 、以監控 MetroCluster 組態。

.關於這項工作
* 您的儲存系統必須執行支援的 ONTAP 版本。請參閱 link:install_prepare.html#software-requirements["軟體需求"] 詳細資料請見下表。
* 您必須使用安裝OpenJDK `yum install java-x.x.x-openjdk` 命令。Tiebreaker 1.5 及更新版本支援 OpenJDK 17 、 18 或 19 。
* 您可以將 MetroCluster tiebreaker 安裝為非 root 使用者、並擁有足夠的管理權限來執行 tiebreaker 安裝、建立表格和使用者、以及設定使用者密碼。


.步驟
. 下載 MetroCluster tiebreaker 軟體和 MetroCluster 的 tiebreaker 、 RPM_GPG 金鑰。
+

NOTE: MetroCluster_tiebreer_RPM_GPG 金鑰可從您在 NetApp 支援網站 下載 tiebreaker 1.5 軟體套件的同一頁下載。

+
https://mysupport.netapp.com/site/products/all/details/metrocluster-tiebreaker/downloads-tab["MetroCluster Tiebreaker （下載） - NetApp 支援網站"^]

. 以root使用者身分登入主機。
. 建立非 root 使用者和 `mcctbgrp` 群組：
+
.. 建立非 root 使用者並設定密碼。
+
下列命令範例可建立名為的非 root 使用者 `mcctbuser1`：

+
[listing]
----
[root@mcctb ~]# useradd mcctbuser1
[root@mcctb ~]# passwd mcctbuser1
Changing password for user mcctbuser1.
New password:
Retype new password:
passwd: all authentication tokens updated successfully.
----
.. 建立名為的群組 `mcctbgrp`：
+
`[root@mcctb ~~]# groupadd mcctbgrp`

.. 將您建立的非 root 使用者新增至 `mcctbgrp` 群組：
+
下列命令會新增 `mcctbuser1` 至 `mcctbgrp` 群組：

+
`[root@mcctb ~]# usermod -a -G mcctbgrp mcctbuser1`



. 驗證RPM檔案。
+
從包含 RPM 金鑰的目錄執行下列子步驟。

+
.. 下載並匯入RPM金鑰檔：
+
[listing]
----
[root@mcctb ~]# rpm --import MetroCluster_Tiebreaker_RPM_GPG.key
----
.. 檢查指紋、確認已匯入正確的金鑰。
+
下列範例顯示正確的金鑰指紋：

+
[listing]
----
root@mcctb:~/signing/mcctb-rpms# gpg --show-keys --with-fingerprint MetroCluster_Tiebreaker_RPM_GPG.key
pub   rsa3072 2022-11-17 [SCEA] [expires: 2025-11-16]
      65AC 1562 E28A 1497 7BBD  7251 2855 EB02 3E77 FAE5
uid                      MCCTB-RPM (mcctb RPM production signing) <mcctb-rpm@netapp.com>
----
.. 驗證簽名： `rpm --checksig NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm`
+
[listing]
----
NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm: digests OK
----
+

NOTE: 您必須在成功驗證簽名之後、才能繼續安裝。



. [[install-tiebreaker）]安裝或升級Tiebreaker軟體：
+

NOTE: 從Tiebreaker 1.4版升級時、您只能升級至Tiebreaker 1.5版。不支援從舊版升級至Tiebreaker 1.5。

+
根據您是執行新安裝還是升級現有安裝、選擇正確的程序。

+
[role="tabbed-block"]
====
.執行新安裝
--
.. 擷取並記錄 Java 的絕對路徑：
+
[listing]
----
[root@mcctb ~]# readlink -f /usr/bin/java
/usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
----
.. 執行下列命令：
`rpm -ivh NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm`
+
系統會顯示下列輸出、以利成功安裝：

+

NOTE: 在安裝期間出現提示時、請提供您先前建立並指派給的非 root 使用者 `mcctbgrp` 群組：

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [100%]
Enter the absolute path for Java : /usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
Verifying if Java exists...
Found Java. Proceeding with the installation.
Enter host user account to use for the installation:
mcctbuser1
User account mcctbuser1 found. Proceeding with the installation
Enter database user name:
root
Please enter database password for root
Enter password:
Sealed          false
Do you wish to auto unseal vault(y/n)?y
Enter the key1:
Enter the key2:
Enter the key3:
Success! Uploaded policy: mcctb-policy
Error enabling approle auth: Error making API request.
URL: POST http://127.0.0.1:8200/v1/sys/auth/approle
Code: 400. Errors:
* path is already in use at approle/
Success! Enabled the kv secrets engine at: mcctb/
Success! Data written to: auth/approle/role/mcctb-app
Password updated successfully in the vault.
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Created symlink /etc/systemd/system/multi-user.target.wants/netapp-metrocluster-tiebreaker-software.service → /etc/systemd/system/netapp-metrocluster-tiebreaker-software.service.
Attempting to start NetApp MetroCluster Tiebreaker software services
Started NetApp MetroCluster Tiebreaker software services
Successfully installed NetApp MetroCluster Tiebreaker software version 1.5.

----


--
.升級現有的安裝
--
.. 確認已安裝受支援版本的OpenJDK、而且是主機上目前的Java版本。
+

NOTE: 若要升級至Tiebreaker 1.5、您必須安裝OpenJDK 17、18或19版。

+
[listing]
----
[root@mcctb ~]# readlink -f /usr/bin/java
/usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
----
.. 確認Vault服務未密封且正在執行： `vault status`
+
[listing]
----
[root@mcctb ~]# vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.12.2
Build Date      2022-11-23T12:53:46Z
Storage Type    file
Cluster Name    vault
Cluster ID      <cluster_id>
HA Enabled      false
----
.. 升級Tiebreaker軟體。
+
[listing]
----
[root@mcctb ~]# rpm -Uvh NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm
----
+
系統會顯示下列輸出以成功升級：

+
[listing]
----

Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [ 50%]

Enter the absolute path for Java : /usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
Verifying if Java exists...
Found Java. Proceeding with the installation.
Enter host user account to use for the installation:
mcctbuser1
User account mcctbuser1 found. Proceeding with the installation
Sealed          false
Do you wish to auto unseal vault(y/n)?y
Enter the key1:
Enter the key2:
Enter the key3:
Success! Uploaded policy: mcctb-policy
Error enabling approle auth: Error making API request.
URL: POST http://127.0.0.1:8200/v1/sys/auth/approle
Code: 400. Errors:
* path is already in use at approle/
Success! Enabled the kv secrets engine at: mcctb/
Success! Data written to: auth/approle/role/mcctb-app
Enter database user name : root
Please enter database password for root
Enter password:
Password updated successfully in the database.
Password updated successfully in the vault.
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Attempting to start NetApp MetroCluster Tiebreaker software services
Started NetApp MetroCluster Tiebreaker software services
Successfully upgraded NetApp MetroCluster Tiebreaker software to version 1.5.
Cleaning up / removing...
   2:NetApp-MetroCluster-Tiebreaker-So################################# [100%]
----


--
====
+

NOTE: 如果您輸入錯誤的MySQL根密碼、則Tiebreaker軟體會指出已成功安裝、但會顯示「拒絕存取」訊息。若要解決此問題、您必須使用「rpm -e」命令解除安裝Tiebreaker軟體、然後使用正確的MySQL root密碼重新安裝軟體。

. 開啟從斷路器主機到每個節點管理生命期和叢集管理生命期的SSH連線、以檢查斷路器與MetroCluster 該軟件的連線。


.相關資訊
https://mysupport.netapp.com/site/["NetApp支援"^]
