---
permalink: tiebreaker/task_install_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database 
summary: Tiebreaker軟體提供叢集式儲存環境的監控功能。當節點連線問題和站台災難發生時、也會傳送SNMP通知。 
---
= 安裝Tiebreaker軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tiebreaker軟體提供叢集式儲存環境的監控功能。當節點連線問題和站台災難發生時、也會傳送SNMP通知。

必須安裝並設定此軟件。MetroCluster



== 安裝或升級斷路器軟體的系統需求

Tiebreaker軟體安裝在第三個站台、可讓軟體區分交換器間連結（ISL）故障（站台間連結中斷時）與站台故障。您的主機系統必須符合特定要求、才能在本機電腦上安裝或升級斷路器軟體、以監控MetroCluster 此功能組態。

本產品具備下列監控功能與需求：MetroCluster

* 不需要針對不同MetroCluster 的不含資訊的組態進行特殊組態設定。
* 監控功能MetroCluster 可同時執行多達15個的不同步組態。
+

NOTE: 每個版本的每個版本組態應只有一MetroCluster 部ESIT斷路 器監控器MetroCluster 、以避免與多部斷路器監控器發生衝突。

* 支援MetroCluster 結合使用各種不同的知識、包括知識、MetroCluster 知識、技術、MetroCluster 技術及彈性等組態。
* 硬體與軟體：
+
** 版本8.3.x、9.0、9.1、9.2、9.3、ONTAP 9.4、9.5、9.6、9.7、9.8、 9.9.1、9.10.1或9.11.1。


* Red Hat Enterprise Linux 7至7.9、或CentOS 7至7.9 64位元（實體安裝或虛擬機器）
+
** MariaDB 5.5.52 x / MySQL Server 5.6x
** 4 GB RAM
** 開啟Java執行時間環境8.


* Red Hat Enterprise Linux 8.1至8.5
+
** MariaDB 10.x（使用使用「yum install MariaDB-server.x86_64」安裝的預設版本）
** 4 GB RAM
** 開啟Java執行時間環境8.




* 磁碟容量：8 GB
* 使用者：root存取權
* 防火牆：
+
** 直接存取以設定AutoSupport 資訊訊息
** SSH（連接埠22/TCP）、HTTPS（連接埠443/TCP）及ping（ICMP）


* 不支援在啟用FIPS的主機上安裝。




== 安裝MetroCluster 相依的斷點器

安裝或升級tiebreaker軟體之前、您必須先安裝MySQL或MariaDB伺服器、視主機所在的Linux作業系統而定。

.步驟
. 安裝Java執行時間環境。
+
<<install-java-1-8,安裝Java執行時間環境1.8>>

. 安裝MySQL或MariaDB伺服器：
+
[cols="30,70"]
|===


| 如果Linux主機是 | 然後... 


 a| 
Red Hat Enterprise Linux 7/CentOS 7.
 a| 
安裝MySQL

<<install-mysql-redhat,在Red Hat Enterprise Linux 7或CentOS 7上安裝MySQL Server 5.5.30或更新版本及5.6.x版本>>



 a| 
Red Hat Enterprise Linux 8
 a| 
安裝MariaDB

<<install-mariadb,在Red Hat Enterprise Linux 8上安裝MariaDB伺服器>>

|===




=== 安裝Java執行時間環境1.8

在安裝或升級Tiebreaker軟體之前、您必須先在主機系統上安裝Java執行時間環境1.8。

.步驟
. 以「root」身分登入主機系統。
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
----
. 安裝Java執行時間環境1.8：
+
[root@mcctb ~]# yum install Java-1.8.0-OpenJDK.x86_64

+
....
[root@mcctb ~]# yum install java-1.8.0-openjdk.x86_64
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
... shortened....
Dependencies Resolved

=======================================================================
Package               Arch   Version                 Repository    Size
=======================================================================
Installing:
 java-1.8.0-openjdk  x86_64  1:1.8.0.144-0.b01.el7_4 updates      238 k
 ..
 ..
Transaction Summary
=======================================================================
Install  1 Package  (+ 4 Dependent packages)

Total download size: 34 M
Is this ok [y/d/N]: y

Installed:
java-1.8.0-openjdk.x86_64 1:1.8.0.144-0.b01.el7_4
Complete!
....




=== 在Red Hat Enterprise Linux 7或CentOS 7上安裝MySQL Server 5.5.30或更新版本及5.6.x版本

安裝或升級Tiebreaker軟體之前、您必須先在主機系統上安裝MySQL Server 5.5.30或更新版本及5.6.x版本。

.步驟
. 以「root」身分登入主機系統。
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2016 from host.domain.com
----
. 將MySQL儲存庫新增至主機系統：
+
[root@mcctb ~]# yum localinstall \https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm`

+
....

Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
Setting up Local Package Process
Examining /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm: mysql-community-release-el6-5.noarch
Marking /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package mysql-community-release.noarch 0:el6-5 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
Package               Arch   Version
                                    Repository                             Size
================================================================================
Installing:
mysql-community-release
                       noarch el6-5 /mysql-community-release-el6-5.noarch 4.3 k
Transaction Summary
================================================================================
Install       1 Package(s)
Total size: 4.3 k
Installed size: 4.3 k
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-release-el6-5.noarch                         1/1
  Verifying  : mysql-community-release-el6-5.noarch                         1/1
Installed:
  mysql-community-release.noarch 0:el6-5
Complete!
....
. 停用mySQL 57儲存庫：
+
[root@mcctb ~]# yum-config-manager -disablemysql57-community

. 啟用mySQL 56儲存庫：
+
[root@mcctb ~]# yum-config-manager --enable mysql56-community

. 啟用儲存庫：
+
[root@mcctb ~]# yum repolist enabled| grep "mysql.*-community.*

+
....

mysql-connectors-community           MySQL Connectors Community            21
mysql-tools-community                MySQL Tools Community                 35
mysql56-community                    MySQL 5.6 Community Server           231
....
. 安裝MySQL社群伺服器：
+
[root@mcctb ~]# yum install mysql-community-server'

+
[listing]
----

Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager
to register.
Setting up Install Process
Resolving Dependencies
--> Running transaction check
.....Output truncated.....
---> Package mysql-community-libs-compat.x86_64 0:5.6.29-2.el6 will be obsoleting
--> Finished Dependency Resolution
Dependencies Resolved
==============================================================================
Package                          Arch   Version       Repository          Size
==============================================================================
Installing:
 mysql-community-client         x86_64  5.6.29-2.el6  mysql56-community  18  M
     replacing  mysql.x86_64 5.1.71-1.el6
 mysql-community-libs           x86_64  5.6.29-2.el6  mysql56-community  1.9 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-libs-compat    x86_64  5.6.29-2.el6  mysql56-community  1.6 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-server         x86_64  5.6.29-2.el6  mysql56-community  53  M
     replacing  mysql-server.x86_64 5.1.71-1.el6
Installing for dependencies:
mysql-community-common          x86_64  5.6.29-2.el6  mysql56-community   308 k

Transaction Summary
===============================================================================
Install       5 Package(s)
Total download size: 74 M
Is this ok [y/N]: y
Downloading Packages:
(1/5): mysql-community-client-5.6.29-2.el6.x86_64.rpm       |  18 MB     00:28
(2/5): mysql-community-common-5.6.29-2.el6.x86_64.rpm       | 308 kB     00:01
(3/5): mysql-community-libs-5.6.29-2.el6.x86_64.rpm         | 1.9 MB     00:05
(4/5): mysql-community-libs-compat-5.6.29-2.el6.x86_64.rpm  | 1.6 MB     00:05
(5/5): mysql-community-server-5.6.29-2.el6.x86_64.rpm       |  53 MB     03:42
-------------------------------------------------------------------------------
Total                                              289 kB/s |  74 MB     04:24
warning: rpmts_HdrFromFdno: Header V3 DSA/SHA1 Signature, key ID 5072e1f5: NOKEY
Retrieving key from file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
Importing GPG key 0x5072E1F5:
 Userid : MySQL Release Engineering <mysql-build@oss.oracle.com>
Package: mysql-community-release-el6-5.noarch
         (@/mysql-community-release-el6-5.noarch)
 From   : file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
Is this ok [y/N]: y
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-common-5.6.29-2.el6.x86_64
....Output truncated....
1.el6.x86_64                                                               7/8
  Verifying  : mysql-5.1.71-1.el6.x86_64                       	           8/8
Installed:
  mysql-community-client.x86_64 0:5.6.29-2.el6
  mysql-community-libs.x86_64 0:5.6.29-2.el6
  mysql-community-libs-compat.x86_64 0:5.6.29-2.el6
  mysql-community-server.x86_64 0:5.6.29-2.el6

Dependency Installed:
  mysql-community-common.x86_64 0:5.6.29-2.el6

Replaced:
  mysql.x86_64 0:5.1.71-1.el6 mysql-libs.x86_64 0:5.1.71-1.el6
  mysql-server.x86_64 0:5.1.71-1.el6
Complete!
----
. 啟動MySQL伺服器：
+
[root@mcctb ~]#服務mysqLD start]

+
....

Initializing MySQL database:  2016-04-05 19:44:38 0 [Warning] TIMESTAMP
with implicit DEFAULT value is deprecated. Please use
--explicit_defaults_for_timestamp server option (see documentation
for more details).
2016-04-05 19:44:38 0 [Note] /usr/sbin/mysqld (mysqld 5.6.29)
        starting as process 2487 ...
2016-04-05 19:44:38 2487 [Note] InnoDB: Using atomics to ref count
        buffer pool pages
2016-04-05 19:44:38 2487 [Note] InnoDB: The InnoDB memory heap is disabled
....Output truncated....
2016-04-05 19:44:42 2509 [Note] InnoDB: Shutdown completed; log sequence
       number 1625987

PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER!
To do so, start the server, then issue the following commands:

  /usr/bin/mysqladmin -u root password 'new-password'
  /usr/bin/mysqladmin -u root -h mcctb password 'new-password'

Alternatively, you can run:
  /usr/bin/mysql_secure_installation

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.
.....Output truncated.....
WARNING: Default config file /etc/my.cnf exists on the system
This file will be read by default by the MySQL server
If you do not want to use this, either remove it, or use the
--defaults-file argument to mysqld_safe when starting the server

                                                           [  OK  ]
Starting mysqld:                                           [  OK  ]
....
. 確認MySQL伺服器正在執行：
+
[root@mcctb ~]#服務mysqLD狀態

+
[listing]
----

mysqld (pid  2739) is running...
----
. 設定安全性和密碼設定：
+
[root@mcctb ~]# mysql_secure_installation]

+
....

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MySQL
       SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

 In order to log into MySQL to secure it, we'll need the current
 password for the root user.  If you've just installed MySQL, and
 you haven't set the root password yet, the password will be blank,
 so you should just press enter here.

 Enter current password for root (enter for none):   <== on default install
                                                         hit enter here
 OK, successfully used password, moving on...

 Setting the root password ensures that nobody can log into the MySQL
 root user without the proper authorization.

 Set root password? [Y/n] y
 New password:
 Re-enter new password:
 Password updated successfully!
 Reloading privilege tables..
  ... Success!

 By default, a MySQL installation has an anonymous user, allowing anyone
 to log into MySQL without having to have a user account created for
 them.  This is intended only for testing, and to make the installation
 go a bit smoother.  You should remove them before moving into a
 production environment.

 Remove anonymous users? [Y/n] y
  ... Success!

 Normally, root should only be allowed to connect from 'localhost'.  This
 ensures that someone cannot guess at the root password from the network.

 Disallow root login remotely? [Y/n] y
  ... Success!

 By default, MySQL comes with a database named 'test' that anyone can
 access.  This is also intended only for testing, and should be removed
 before moving into a production environment.

 Remove test database and access to it? [Y/n] y
  - Dropping test database...
 ERROR 1008 (HY000) at line 1: Can't drop database 'test';
 database doesn't exist
  ... Failed!  Not critical, keep moving...
  - Removing privileges on test database...
  ... Success!

 Reloading the privilege tables will ensure that all changes made so far
 will take effect immediately.

 Reload privilege tables now? [Y/n] y
  ... Success!

 All done!  If you've completed all of the above steps, your MySQL
 installation should now be secure.

 Thanks for using MySQL!

 Cleaning up...
....
. 驗證MySQL登入是否正常運作：
+
[root@mcctb ~]# mySQL -u root–p]

+
....

Enter password: <configured_password>
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 5.6.29 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql>
....
+
如果MySQL登入正常運作、輸出將在「mysql>」提示字元結束。





==== 啟用MySQL自動啟動設定

您應該確定MySQL deamon的自動啟動功能已開啟。開啟MySQL精靈會在MetroCluster 系統重新開機時、自動重新啟動MySQL。如果MySQL精靈未執行、則tiebreaker軟體會繼續執行、但無法重新啟動、也無法進行組態變更。

.步驟
. 驗證MySQL在開機時是否已啟用自動啟動：
+
[root@mcctb ~]# systemctl list-unit-filesmysqld.service`

+
....
UNIT FILE          State
------------------ ----------
mysqld.service     enabled

....
+
如果MySQL在開機時未啟用自動啟動、請參閱MySQL文件、以啟用安裝的自動啟動功能。





=== 在Red Hat Enterprise Linux 8上安裝MariaDB伺服器

您必須先在主機系統上安裝MariaDB伺服器、才能安裝或升級tiebreaker軟體。

.開始之前
您的主機系統必須在Red Hat Enterprise Linux（RHEL）8上執行。

.步驟
. 以「root」身分登入主機系統。
+
....

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
....
. 安裝MariaDB伺服器：
+
[root@mcctb ~]# yum install MariaDB-server.x86_64

+
....
 [root@mcctb ~]# yum install mariadb-server.x86_64
Loaded plugins: fastestmirror, langpacks
...
...

===========================================================================
 Package                      Arch   Version         Repository        Size
===========================================================================
Installing:
mariadb-server               x86_64   1:5.5.56-2.el7   base            11 M
Installing for dependencies:

Transaction Summary
===========================================================================
Install  1 Package  (+8 Dependent packages)
Upgrade             ( 1 Dependent package)

Total download size: 22 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for base warning:
/var/cache/yum/x86_64/7/base/packages/mariadb-libs-5.5.56-2.el7.x86_64.rpm:
Header V3 RSA/SHA256 Signature,
key ID f4a80eb5: NOKEY] 1.4 MB/s | 3.3 MB  00:00:13 ETA
Public key for mariadb-libs-5.5.56-2.el7.x86_64.rpm is not installed
(1/10): mariadb-libs-5.5.56-2.el7.x86_64.rpm  | 757 kB  00:00:01
..
..
(10/10): perl-Net-Daemon-0.48-5.el7.noarch.rpm|  51 kB  00:00:01
-----------------------------------------------------------------------------------------
Installed:
  mariadb-server.x86_64 1:5.5.56-2.el7

Dependency Installed:
mariadb.x86_64 1:5.5.56-2.el7
perl-Compress-Raw-Bzip2.x86_64 0:2.061-3.el7
perl-Compress-Raw-Zlib.x86_64 1:2.061-4.el7
perl-DBD-MySQL.x86_64 0:4.023-5.el7
perl-DBI.x86_64 0:1.627-4.el7
perl-IO-Compress.noarch 0:2.061-2.el7
perl-Net-Daemon.noarch 0:0.48-5.el7
perl-PlRPC.noarch 0:0.2020-14.el7

Dependency Updated:
  mariadb-libs.x86_64 1:5.5.56-2.el7
Complete!
....
. 啟動MariaDB伺服器：
+
[root@mcctb ~]# systemcl start MariaDB

. 確認MariaDB伺服器已啟動：
+
[root@mcctb ~]# systemctl狀態MariaDB

+
....

[root@mcctb ~]# systemctl status mariadb
mariadb.service - MariaDB database server
...
Nov 08 21:28:59 mcctb systemd[1]: Starting MariaDB database server...
...
Nov 08 21:29:01 scspr0523972001 systemd[1]: Started MariaDB database server.
....
+

NOTE: 確認MariaDB的「啟用自動啟動」設定已開啟。請參閱 <<mariadb-autostart>>。

. 設定安全性和密碼設定：
+
[root@mcctb ~]# mysql_secure_installation]

+
....

[root@mcctb ~]# mysql_secure_installation
NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
SERVERS IN PRODUCTION USE! PLEASE READ EACH STEP CAREFULLY!
Set root password? [Y/n] y
New password:
Re-enter new password:
Password updated successfully!
Remove anonymous users? [Y/n] y
... Success!
Normally, root should only be allowed to connect from 'localhost'. This
ensures that someone cannot guess at the root password from the network.
Disallow root login remotely? [Y/n] y
... Success!
Remove test database and access to it? [Y/n] y
- Dropping test database...
... Success!
- Removing privileges on test database...
... Success!
Reload privilege tables now? [Y/n]
... Success!
Cleaning up...
All done! If you've completed all of the above steps, your MariaDB
installation should now be secure.
Thanks for using MariaDB!
....




==== 啟用MariaDB的自動啟動設定

您應該確定MariaDB的自動啟動功能已開啟。如果您未啟用自動啟動功能、MetroCluster 且駐留的系統必須重新開機、則tiebreaker軟體會繼續執行、但無法重新啟動MariaDB服務、也無法進行組態變更。

.步驟
. 啟用自動啟動服務：
+
[root@mcctb ~]# systemctl enable mariadb.service`

. 確認已啟用MariaDB、以便在開機時自動啟動：
+
[root@mcctb ~]# systemctl list-unit-filesmariadb.service`

+
....
UNIT FILE          State
------------------ ----------
mariadb.service    enabled

....




== 安裝或升級軟體套件

您必須在MetroCluster 本機電腦上安裝或升級ESITirepreaker軟體、才能監控MetroCluster 各種組態。

* 您的儲存系統必須執行ONTAP 不含更新版本的資訊。
* 您必須使用「yum install Java-1.8.0-OpenJDK'」命令來安裝OpenJDK.


.步驟
. 下載MetroCluster 最新版的Eetirepreaker軟體。此範例使用1.21P3-1版。
+
https://mysupport.netapp.com/site/["NetApp支援"]

. 以root使用者身分登入主機。
. 安裝或升級Tiebreaker軟體：
+
[cols="20,80"]
|===


| 如果您... | 發出此命令... 


 a| 
執行新安裝
 a| 
「rpm -ivh NetApp-MetroCluster-tiebreer-Software-1.21P3-1x86_64。rpm」

系統會顯示下列輸出、以利成功安裝：

....
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [100%]
Post installation start Wed Oct 20 09:59:19 EDT 2021
Enter MetroCluster Tiebreaker user password:

Please enter mysql root password when prompted
Enter password:
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Created symlink /etc/systemd/system/multi-user.target.wants/netapp-metrocluster-tiebreaker-software.service → /etc/systemd/system/netapp-metrocluster-tiebreaker-software.service.
Attempting to start NetApp MetroCluster Tiebreaker software services
Started NetApp MetroCluster Tiebreaker software services
Enabled autostart of NetApp MetroCluster Tiebreaker software daemon during boot
Created symbolic link for NetApp MetroCluster Tiebreaker software CLI
Post installation end Wed Oct 20 09:59:28 EDT 2021
Successfully installed NetApp MetroCluster Tiebreaker software version 1.21P3.
....


 a| 
升級現有的安裝
 a| 
「rpm -Uvh NetApp-MetroCluster-tiebreer-Software-1.21P3-1.x86_64。rpm」

系統會顯示下列輸出以成功升級：

....

MetroCluster-Tiebreaker-Software-1.21P3-1.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Upgrading NetApp MetroCluster Tiebreaker software....
Stopping NetApp MetroCluster Tiebreaker software services before upgrade.
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [ 50%]
Post installation start Wed Oct 20 09:57:49 EDT 2021
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Created symlink /etc/systemd/system/multi-user.target.wants/netapp-metrocluster-tiebreaker-software.service → /etc/systemd/system/netapp-metrocluster-tiebreaker-software.service.
Attempting to start NetApp MetroCluster Tiebreaker software services
Starting NetApp MetroCluster Tiebreaker software services. Retry: 1
Started NetApp MetroCluster Tiebreaker software services
Enabled autostart of NetApp MetroCluster Tiebreaker software daemon during boot
Created symbolic link for NetApp MetroCluster Tiebreaker software CLI
Post upgrade end Wed Oct 20 09:57:52 EDT 2021
Successfully upgraded NetApp MetroCluster Tiebreaker software to version 1.21P3.
Cleaning up / removing...
   2:NetApp-MetroCluster-Tiebreaker-So################################# [100%]

....
|===
+

NOTE: 如果您輸入錯誤的MySQL根密碼、則Tiebreaker軟體會指出已成功安裝、但會顯示「拒絕存取」訊息。若要解決此問題、您必須使用「rpm -e」命令解除安裝Tiebreaker軟體、然後使用正確的MySQL root密碼重新安裝軟體。

. 開啟從斷路器主機到每個節點管理生命期和叢集管理生命期的SSH連線、以驗證與MetroCluster 該軟件的斷路器連線。


.相關資訊
https://mysupport.netapp.com/site/["NetApp支援"]



== 升級執行Tiebreaker監控的主機

如果您在升級前將監視器置於觀察者模式、則可在執行斷路器監視器的主機上進行升級、而不會造成中斷。

.步驟
. 確認監視器處於觀察者模式：
+
「監視者顯示–狀態」

+
....
NetApp MetroCluster Tiebreaker:> monitor show -status
MetroCluster: cluster_A
    Disaster: false
    Monitor State: Normal
    Observer Mode: true
    Silent Period: 15
    Override Vetoes: false
    Cluster: cluster_Ba(UUID:4d9ccf24-080f-11e4-9df2-00a098168e7c)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-a1(UUID:78b44707-0809-11e4-9be1-e50dab9e83e1)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-a2(UUID:9a8b1059-0809-11e4-9f5e-8d97cdec7102)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
    Cluster: cluster_B(UUID:70dacd3b-0823-11e4-a7b9-00a0981693c4)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-b1(UUID:961fce7d-081d-11e4-9ebf-2f295df8fcb3)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-b2(UUID:9393262d-081d-11e4-80d5-6b30884058dc)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
....
. 將所有監視器變更為觀察者模式。
+
....
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name _monitor_name_ -observer-mode true
....
. 若要升級Tiebreaker主機、請依照下列程序中的所有步驟進行：
+
<<install-upgrade-sw-pkg,安裝或升級軟體套件>>

. 停用觀察者模式、將所有監視器移回線上模式。
+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name _monitor_name_ -observer-mode false
----




== 選取Tiebreaker軟體的NTP來源

您應該使用本地網路時間傳輸協定（NTP）來源來執行Tiebreaker軟體。它不應使用MetroCluster 與斷路器軟體所監控的不相同來源。
