---
permalink: tiebreaker/task_configure_snmp_setts_for_tiebreaker_software.html 
sidebar: sidebar 
keywords: snmp, tiebreaker, software, configure, setting 
summary: 若要將SNMP與Tiebreaker軟體搭配使用、您必須設定SNMP設定。 
---
= 設定斷路器軟體的SNMP設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要將SNMP搭配Tiebreaker軟體使用、您必須設定SNMP設定。

. 使用tiebreaker CLI `snmp config wizard` 命令以新增MetroCluster 功能。
+

NOTE: 目前僅支援一個SNMP設陷主機。

+
以下範例顯示支援SNMP V3的SNMP接收器組態、IP位址為10.240.45.66、而設陷訊息則為連接埠號碼162。Tiebreaker軟體已準備好傳送設陷到您指定的SNMP接收器。

+
....

NetApp MetroCluster Tiebreaker :> snmp config wizard
Enter SNMP Version[V1/V3]: v3
Enter SNMP Host: 10.240.45.66
Enter SNMP Port: 162
Enter SNMP V3 Security Name: v3sec
Enter SNMP V3 Authentication password:
Enter SNMP V3 Privacy password:
Engine ID : 8000031504932eff571825192a6f1193b265e24593
Successfully added SNMP properties to NetApp MetroCluster Tiebreaker software.
....
+

NOTE: 您應該設定v3、因為SNMPv1不安全。請確定預設的社群字串*不是*設為公用。

. 確認已設定SNMP設定：
+
"NMP組態測試"

+
下列範例顯示、Tiebreaker軟體可傳送事件test_SNMP設陷的SNMP：

+
....

NetApp MetroCluster Tiebreaker :> snmp config test
Sending SNMP trap to localhost. Version : V1.
Successfully sent SNMP trap for event TEST_SNMP_CONFIG
NetApp MetroCluster Tiebreaker :>
....

