---
permalink: tiebreaker/task_configure_snmp_setts_for_tiebreaker_software.html 
sidebar: sidebar 
keywords: snmp, tiebreaker, software, configure, setting 
summary: 若要將SNMP與Tiebreaker軟體搭配使用、您必須設定SNMP設定。 
---
= 設定斷路器軟體的SNMP設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要將SNMP搭配Tiebreaker軟體使用、您必須設定SNMP設定。

.關於這項工作
* Tiebreaker 1.6 僅支援 SNMPv3 。
* 雖然 tiebreaker 1.5 和 1.4 支援 SNMPv1 和 SNMPv3 、但 NetApp 強烈建議您設定 SNMPv3 以獲得最佳安全性。


.步驟
. 使用tiebreaker CLI `snmp config wizard` 命令以新增MetroCluster 功能。
+

NOTE: 目前僅支援一個SNMP設陷主機。

+
 `snmp config wizard`命令回應取決於您所執行的 tiebreaker 版本。

+
[role="tabbed-block"]
====
.斷路器 1.6.
--
以下範例顯示 SNMP 接收器的組態、該接收器支援 IP 位址為 192.0.2.255 的 SNMPv3 、以及設陷訊息的連接埠編號 162 。Tiebreaker軟體已準備好傳送設陷到您指定的SNMP接收器。


NOTE: Tiebreaker 1.6 僅支援 SNMPv3

[listing]
----
NetApp MetroCluster Tiebreaker :> snmp config wizard
Enter SNMP Host: 192.0.2.255
Enter SNMP Port: 162
Enter SNMP V3 Security Name: v3sec
Enter SNMP V3 Authentication password:
----
--
.斷路器 1.5 和 1.4
--
以下範例顯示 SNMP 接收器的組態、該接收器支援 IP 位址為 192.0.2.255 的 SNMPv3 、以及設陷訊息的連接埠編號 162 。Tiebreaker軟體已準備好傳送設陷到您指定的SNMP接收器。

....

NetApp MetroCluster Tiebreaker :> snmp config wizard
Enter SNMP Version[V1/V3]: v3
Enter SNMP Host: 192.0.2.255
Enter SNMP Port: 162
Enter SNMP V3 Security Name: v3sec
Enter SNMP V3 Authentication password:
Enter SNMP V3 Privacy password:
Engine ID : 8000031504932eff571825192a6f1193b265e24593
Successfully added SNMP properties to NetApp MetroCluster Tiebreaker software.
....

NOTE: 您應該設定v3、因為SNMPv1不安全。驗證預設社群字串是否設定為 * 非 * 公開。

--
====
. 確認已設定SNMP設定：
+
"NMP組態測試"

+
下列範例顯示、Tiebreaker軟體可傳送事件test_SNMP設陷的SNMP：

+
....

NetApp MetroCluster Tiebreaker :> snmp config test
Sending SNMP trap to localhost. Version : V3.
Successfully sent SNMP trap for event TEST_SNMP_CONFIG
NetApp MetroCluster Tiebreaker :>
....

