---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: 您可以使用AFF 單一啟動器連接埠來設定FAS8020、AFF8020、FAS8200和E4A300系統、並為每個光纖配置兩個啟動器連接埠。 
---
= 使用兩個啟動器連接埠的系統連接埠指派
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用AFF 單一啟動器連接埠來設定FAS8020、AFF8020、FAS8200和E4A300系統、並為每個光纖配置兩個啟動器連接埠。

您只需使用一個FC連接埠（FC1或FC2）、就能遵循光纖橋接器6500N橋接器或光纖橋接器7500N或7600N橋接器的纜線。與其使用四個啟動器、只連接兩個啟動器、並將連接至交換器連接埠的其他兩個啟動器保留為空白。

您必須針對FIBRABridge 6500N橋接器的組態套用正確的RCF檔案。

如果是手動執行分區、請使用一個FC連接埠（FC1或FC2）、遵循用於Fibre Bridge 6500N或Fibre Bridge 7500N或7600N橋接器的分區。在此案例中、每個架構的每個區域成員都會新增一個啟動器連接埠、而非兩個。

您可以使用下列程序來變更分區或執行從FIBEBridge 6500升級至FIBEBridge 7500：請從進行下列程序_熱插拔使用FIBEBridge 7500N或7600N bridge_的FIBEIBER__橋接器 https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html["維護MetroCluster 這些元件"]。

下表顯示使用ONTAP 更新版本的功能時、FC交換器的連接埠指派。

|===


4+| 使用Fibre Bridge 6500N橋接器或使用單一FC連接埠（FC1或FC2）的Fibre Bridge 7500N或7600N的組態 


4+| *支援1或DR群組1* MetroCluster 


.2+| *元件* .2+| *連接埠* 2+| * Brocade交換器機型6505、6510、6520、7840、G620、 G610和DCX 8510-8* 


| *連接至FC交換器...* | *連接至交換器連接埠...* 


.8+| 控制器_x_1  a| 
FC-VI連接埠A
 a| 
1.
 a| 
0



 a| 
FC-VI連接埠b
 a| 
2.
 a| 
0



 a| 
FC-VI連接埠c
 a| 
1.
 a| 
1.



 a| 
FC-VI連接埠d
 a| 
2.
 a| 
1.



 a| 
HBA連接埠A
 a| 
1.
 a| 
2.



 a| 
HBA連接埠b
 a| 
2.
 a| 
2.



 a| 
HBA連接埠c
 a| 
-
 a| 
-



 a| 
HBA連接埠d
 a| 
-
 a| 
-



 a| 
堆疊1
 a| 
bride_x_1a.
 a| 
1.
 a| 
8.



 a| 
bride_x_1b.
 a| 
2.
 a| 
8.



 a| 
堆疊y
 a| 
bride_x_ya
 a| 
1.
 a| 
11.



 a| 
bride_x_yb
 a| 
2.
 a| 
11.

|===
下表顯示使用ONTAP NETAPP 9.0時FC交換器的連接埠指派。

|===


4+| *不含雙節點組態* MetroCluster 


.2+| *元件* .2+| *連接埠* 2+| * Brocade 6505、6510或DCX 8510-8* 


| * FC_SWIT_x_1* | * FC_SWIT_x_2* 


 a| 
控制器_x_1
 a| 
FC-VI連接埠A
 a| 
0
 a| 
-



 a| 
FC-VI連接埠b
 a| 
-
 a| 
0



 a| 
HBA連接埠A
 a| 
1.
 a| 
-



 a| 
HBA連接埠b
 a| 
-
 a| 
1.



 a| 
HBA連接埠c
 a| 
2.
 a| 
-



 a| 
HBA連接埠d
 a| 
-
 a| 
2.

|===