---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: 您可以使用AFF 單一啟動器連接埠來設定FAS8020、AFF8020、FAS8200和E4A300系統、並為每個光纖配置兩個啟動器連接埠。 
---
= 使用兩個啟動器連接埠的系統連接埠指派
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用AFF 單一啟動器連接埠來設定FAS8020、AFF8020、FAS8200和E4A300系統、並為每個光纖配置兩個啟動器連接埠。

您只需使用一個 FC 連接埠（ FC1 或 FC2 ）、即可遵循 FiberBridge 7500N 或 7600N 橋接器的纜線。與其使用四個啟動器、只連接兩個啟動器、並將連接至交換器連接埠的其他兩個啟動器保留為空白。

如果手動執行分區、請遵循使用一個 FC 連接埠（ FC1 或 FC2 ）的 FiberBridge 7500N 或 7600N 橋接器分區。在此案例中、每個架構的每個區域成員都會新增一個啟動器連接埠、而非兩個。

您可以使用中的程序、將分區變更或從 FiberBridge 6500N 升級至 FiberBridge 7500N link:../maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["使用光纖橋接器7600N或7500N橋接器熱交換光纖橋接器6500N"]。

下表顯示使用ONTAP 更新版本的功能時、FC交換器的連接埠指派。

|===


4+| 僅使用一個 FC 連接埠（ FC1 或 FC2 ）、使用 FiberBridge 7500N 或 7600N 的組態 


4+| *支援1或DR群組1* MetroCluster 


.2+| *元件* .2+| *連接埠* 2+| * Brocade交換器機型6505、6510、6520、7840、G620、 G610和DCX 8510-8* 


| *連接至FC交換器...* | *連接至交換器連接埠...* 


.8+| 控制器_x_1  a| 
FC-VI連接埠A
 a| 
1.
 a| 
0



 a| 
FC-VI連接埠b
 a| 
2.
 a| 
0



 a| 
FC-VI連接埠c
 a| 
1.
 a| 
1.



 a| 
FC-VI連接埠d
 a| 
2.
 a| 
1.



 a| 
HBA連接埠A
 a| 
1.
 a| 
2.



 a| 
HBA連接埠b
 a| 
2.
 a| 
2.



 a| 
HBA連接埠c
 a| 
-
 a| 
-



 a| 
HBA連接埠d
 a| 
-
 a| 
-



 a| 
堆疊1
 a| 
bride_x_1a.
 a| 
1.
 a| 
8.



 a| 
bride_x_1b.
 a| 
2.
 a| 
8.



 a| 
堆疊y
 a| 
bride_x_ya
 a| 
1.
 a| 
11.



 a| 
bride_x_yb
 a| 
2.
 a| 
11.

|===
下表顯示使用ONTAP NETAPP 9.0時FC交換器的連接埠指派。

|===


4+| *不含雙節點組態* MetroCluster 


.2+| *元件* .2+| *連接埠* 2+| * Brocade 6505、6510或DCX 8510-8* 


| * FC_SWIT_x_1* | * FC_SWIT_x_2* 


 a| 
控制器_x_1
 a| 
FC-VI連接埠A
 a| 
0
 a| 
-



 a| 
FC-VI連接埠b
 a| 
-
 a| 
0



 a| 
HBA連接埠A
 a| 
1.
 a| 
-



 a| 
HBA連接埠b
 a| 
-
 a| 
1.



 a| 
HBA連接埠c
 a| 
2.
 a| 
-



 a| 
HBA連接埠d
 a| 
-
 a| 
2.

|===