---
permalink: install-fc/concept_considerations_differences.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: 各種MetroCluster 版本的不二組態在必要的元件上有主要差異。 
---
= 各個不相同的地方ONTAP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


各種MetroCluster 版本的不二組態在必要的元件上有主要差異。

在所有組態中、這兩MetroCluster 個「不完整」站台均設定為ONTAP 一個「叢集」。在雙節點MetroCluster 的「效能不全」組態中、每個節點都會設定為單節點叢集。

|===


| 功能 | IP組態 2+| 網路附加組態 2+| 延伸組態 


|  |  | *四節點或八節點* | *雙節點* | *雙節點橋接* | *雙節點直接附加* 


 a| 
控制器數量
 a| 
四或八*
 a| 
四或八個
 a| 
二
 a| 
二
 a| 
二



 a| 
使用FC交換器儲存網路
 a| 
否
 a| 
是的
 a| 
是的
 a| 
否
 a| 
否



 a| 
使用IP交換器儲存網路
 a| 
是的
 a| 
否
 a| 
否
 a| 
否
 a| 
否



 a| 
使用FC至SAS橋接器
 a| 
否
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
否



 a| 
使用直接附加的SAS儲存設備
 a| 
是（僅限本機附加）
 a| 
否
 a| 
否
 a| 
否
 a| 
是的



 a| 
支援ADP
 a| 
有（從ONTAP 2019 9.4開始）
 a| 
否
 a| 
否
 a| 
否
 a| 
否



 a| 
支援本機HA
 a| 
是的
 a| 
是的
 a| 
否
 a| 
否
 a| 
否



 a| 
支援ONTAP 非計畫性自動切換（AUSO）
 a| 
否
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
支援無鏡射Aggregate
 a| 
是（從ONTAP NetApp 9.8開始）
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
支援陣列LUN
 a| 
否
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
支援ONTAP 《支援》
 a| 
是（從ONTAP NetApp 9.7開始）
 a| 
否
 a| 
否
 a| 
否
 a| 
否



 a| 
支援MetroCluster 斷點器
 a| 
是（不搭配ONTAP 使用「資訊媒體」）
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



| 支援 <<支援MetroCluster 所有的SAN Array系統、採用各種不完整的組態,所有SAN陣列>>  a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的

|===
*重要*

請注意以下八節點MetroCluster 的「靜態IP組態設定考量事項：

* 從支援的範圍ONTAP 從支援的範圍從支援的範圍從支援的範圍從
* 僅支援經NetApp驗證MetroCluster 的功能性交換器（向NetApp訂購）。
* 不支援使用IP路由（第3層）後端連線的組態。
* 不支援使用共享私有第2層網路的組態。
* 不支援使用Cisco 9336C-FX2共用交換器的組態。




== 支援MetroCluster 所有的SAN Array系統、採用各種不完整的組態

部分All SAN Array（ASA）在MetroCluster 各種組態中均受到支援。在本文件中、有關不適用的功能的資訊適用於相應的功能表系統。MetroCluster AFF ASA例如AFF 、所有的纜線和其他有關的資訊、也適用於ASA AFF 該系統。

支援的平台組態列於 https://["NetApp Hardware Universe"]。
