---
permalink: install-fc/concept_considerations_8510.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: 當您準備MetroCluster 進行此版本的安裝時、您應該瞭解MetroCluster 到該系統的硬體架構和必要元件。 
---
= 使用Brocade DCX 8510-8交換器的需求
:allow-uri-read: 


* 若要使用DCX 8510-8交換器MetroCluster 進行非必要的組態設定、必須向NetApp購買。
* 為了擴充性、MetroCluster 如果在4個48埠模組中只佈線兩個MetroCluster、則應在各個支援區組態之間保留一個連接埠區塊。這可讓您在MetroCluster 不重新啟用的情況下、在不啟用的情況下、擴充以支援支援的情況下使用連接埠
* 必須為ISL連接埠和儲存連線正確設定每個MetroCluster 採用「EWITCH」組態的Brocade DCX 8510-8交換器。如需連接埠使用量、請參閱下節： link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["FC交換器的連接埠指派（使用ONTAP 版本不含更新版本）"]。
* ISL無法共享、每MetroCluster 個功能需要兩個ISL才能用於每個架構。
* DCX 8510-8交換器用於後端MetroCluster 的不應用於任何其他連線。
+
非MetroCluster裝置不應連接至這些交換器、而非MetroCluster流量不應流經DCX 8510-8交換器。

* 一線卡可連接ONTAP 至《S基 維網叢集*》或《ONTAP *》《7模式MetroCluster》。



NOTE: 此交換器無法使用RCF檔案。

以下是使用兩個Brocade DCX 8510-8交換器的需求：

* 每個站台必須有一個DCX 8510-8交換器。
* 您必須在每個交換器中使用至少兩個含有16GB SFP的48埠刀鋒伺服器。


以下是MetroCluster 在每個站台上使用四個DCX 8510-8交換器的需求、這些交換器採用的是一套整合的功能：

* 每個站台必須有兩個DCX 8510-8交換器。
* 每個DCX 8510-8交換器必須至少使用一個48埠刀鋒。
* 每個刀鋒均設定為使用虛擬架構的虛擬交換器。


Brocade DCX 8510-8交換器不支援下列NetApp產品：

* Config Advisor
* Fabric健全狀況監視器
* MyAutoSupport（系統風險可能顯示誤報）
* （前身為《統一化管理程式》）Active IQ Unified Manager OnCommand



NOTE: 請確定此組態所需的所有元件均位於中 https://["NetApp 互通性對照表工具"]。請參閱互通性對照表工具中的附註一節、以取得支援組態的相關資訊。
