---
permalink: install-fc/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: 如果您的組態包含無鏡射的Aggregate、則必須注意切換作業後可能發生的存取問題。 
---
= 使用無鏡射Aggregate時的考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== 使用無鏡射Aggregate時的考量

如果您的組態包含無鏡射的Aggregate、則必須注意切換作業之後可能發生的存取問題。



== 進行需要關機的維護時、需要考慮無鏡射的集合體

如果您因為維護理由而執行協調式切換、需要全站台關機、則應先手動將災難站台擁有的任何未鏡射集合體離線。

如果您沒有將任何未鏡射的Aggregate離線、則仍在運作中的站台節點可能會因為多磁碟出現問題而關閉。如果切換到無鏡射的Aggregate離線或遺失、可能會發生這種情況、因為災難站台的儲存設備連線中斷。這是因為關閉電源或遺失ISL所致。



== 無鏡射集合體和階層式命名空間的考量

如果您使用階層式命名空間、則應設定交會路徑、使該路徑中的所有磁碟區僅位於鏡射Aggregate上、或僅位於無鏡射Aggregate上。在交會路徑中設定混合使用無鏡射與鏡射的集合體、可能會導致在切換作業之後無法存取無鏡射的集合體。



== 無鏡射集合體、CRS中繼資料磁碟區和資料SVM根磁碟區的考量

組態複寫服務（CRS）中繼資料磁碟區和資料SVM根磁碟區必須位於鏡射Aggregate上。您無法將這些磁碟區移至無鏡射的Aggregate。如果它們位於無鏡射的Aggregate上、則會對協調的切換和切換回復作業加以否決。如果發生這種情況、則使用支援功能檢查命令會發出警告。MetroCluster



== 無鏡射集合體和SVM的考量

SVM應僅在鏡射Aggregate上設定、或僅在無鏡射Aggregate上設定。設定混合使用無鏡射與鏡射的集合體、可能導致切換作業超過120秒、如果無鏡射的集合體未上線、則會導致資料中斷。



== 無鏡射集合體和SAN的考量

在9.9.1之前的版本中、LUN不應位於無鏡射的Aggregate上。ONTAP在未鏡射的集合體上設定LUN、可能會導致切換作業超過120秒、並導致資料中斷。
