---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: 您可以使用AFF 單一啟動器連接埠來設定FAS8020、AFF8020、FAS8200和E4A300系統、並為每個光纖配置兩個啟動器連接埠。 
---
= 使用兩個啟動器連接埠的系統連接埠指派
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用每個結構的單一啟動器連接埠和每個控制器的兩個啟動器連接埠來設定FAS8200和AFF A300系統。

您可以依照 FibreBridge 7600N 橋接器的佈線方法，僅使用一個 FC 連接埠（FC1 或 FC2）。無需使用四個啟動器，只需連接兩個啟動器，並將連接到交換器連接埠的另外兩個啟動器留空。

如果手動執行分區，則請遵循使用 FC 連接埠（FC1 或 FC2）的 FibreBridge 7600N 橋接器的分區方法。在這種情況下，每個網路結構中的每個區域成員都會添加一個啟動器端口，而不是兩個。

您可以使用中的程序、將分區變更或從 FiberBridge 6500N 升級至 FiberBridge 7500N link:../maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["使用光纖橋接器7600N或7500N橋接器熱交換光纖橋接器6500N"]。

下表顯示了當每個結構使用一個啟動器連接埠並且每個控制器使用兩個啟動器連接埠時Brocade FC 交換器的連接埠分配。

[cols="2a,2a,2a,2a"]
|===
4+| 僅使用一個 FC 連接埠（ FC1 或 FC2 ）、使用 FiberBridge 7500N 或 7600N 的組態 


 a| 
*支援1或DR群組1* MetroCluster



 a| 
*元件*
 a| 
*連接埠*
 a| 
*6505、6510、6520、7840、G620、G630、G610、G710、G720、G730 和 DCX 8510-8*



 a| 
*連接至FC交換器...*
 a| 
*連接至交換器連接埠...*



 a| 
控制器_x_1
 a| 
FC-VI連接埠A
 a| 
1.
 a| 
0



 a| 
FC-VI連接埠b
 a| 
2.
 a| 
0



 a| 
FC-VI連接埠c
 a| 
1.
 a| 
1.



 a| 
FC-VI連接埠d
 a| 
2.
 a| 
1.



 a| 
HBA連接埠A
 a| 
1.
 a| 
2.



 a| 
HBA連接埠b
 a| 
2.
 a| 
2.



 a| 
HBA連接埠c
 a| 
-
 a| 
-



 a| 
HBA連接埠d
 a| 
-
 a| 
-



 a| 
堆疊1
 a| 
bride_x_1a.
 a| 
1.
 a| 
8.



 a| 
bride_x_1b.
 a| 
2.
 a| 
8.



 a| 
堆疊y
 a| 
bride_x_ya
 a| 
1.
 a| 
11.



 a| 
bride_x_yb
 a| 
2.
 a| 
11.

|===