---
permalink: install-fc/reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, requirements, array, luns, mcc 
summary: 用於各種組態的支援系統、儲存陣列和FC交換器、必須符合這類組態的需求。ONTAP MetroCluster此外、您也必須考量SyncMirror 使用陣列LUN進行的各種不完整的功能需求MetroCluster 。 
---
= 使用陣列LUN進行動態組態的需求MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
用於各種組態的支援系統、儲存陣列和FC交換器、必須符合這類組態的需求。ONTAP MetroCluster此外、您也必須考量SyncMirror 使用陣列LUN進行的各種不完整的功能需求MetroCluster 。



== 系統需求ONTAP

* 必須將此支援的支援系統識別為支援的不支援的不支援的組態。ONTAP MetroCluster
+
在中 https://["NetApp互通性對照表工具IMT （不含）"]、您可以使用儲存解決方案欄位來選擇MetroCluster 您的解決方案。您可以使用*元件總管*來選取元件和ONTAP 更新版本、以精簡搜尋範圍。您可以按一下「*顯示結果*」來顯示符合條件的支援組態清單。

+

NOTE: 您必須參閱與您在互通性對照表中選取的任何組態相關的警示詳細資料。

* 所有的不完整組態的不完整系統都必須採用相同的模型。ONTAP MetroCluster
* 根據ONTAP 機型、FC-VI介面卡必須安裝在每個版本適用的插槽中。
+
https://["NetApp Hardware Universe"]





== 儲存陣列的需求

* 必須將儲存陣列識別為MetroCluster 支援的不支援的不支援的不支援功能。
+
https://["NetApp 互通性對照表工具"]

* 在不完整組態中的儲存陣列MetroCluster 必須對稱：
+
** 這兩個儲存陣列必須來自同一個支援的廠商系列、並且安裝相同的韌體版本。
+
https://["NetApp E系列儲存設備的虛擬化實作FlexArray"]

+
https://["適用於協力廠商儲存設備的虛擬化實作FlexArray"]

** 用於鏡射儲存設備的磁碟類型（例如SATA、SSD或SAS）必須在兩個儲存陣列上相同。
** 設定儲存陣列的參數（例如RAID類型和分層）必須在兩個站台之間相同。






== FC交換器需求

* 交換器和交換器韌體必須識別為MetroCluster 支援的支援功能、才能進行各種版本的支援。
+
https://["NetApp 互通性對照表工具"]

* 每個網路都必須有兩個FC交換器。
* 每ONTAP 個支援系統都必須使用備援元件連接至儲存設備、以便在設備和路徑故障時提供備援。
* 每個架構最多可支援八個ISL的FASA700、FAS9000、FASA900和FAS9500儲存系統。AFF AFF其他儲存系統機型則支援每個架構最多四個ISL。


交換器必須使用MetroCluster 不完整的基本交換器組態、ISL設定和FC-VI組態。

link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["手動設定Cisco或Brocade FC交換器"]



== 需求SyncMirror

* 需要使用以利進行一個不必要的組態設定。SyncMirror MetroCluster
* 鏡射儲存設備需要兩個獨立的儲存陣列、每個站台一個。
* 需要兩組陣列LUN。
+
本機儲存陣列（Pool0）上的Aggregate需要一組集合、而遠端儲存陣列則需要另一組集合來鏡射集合（Aggregate的另一個叢集、Pool1）。

+
陣列LUN的大小必須相同、才能鏡射集合體。

* 不鏡射的Aggregate也支援MetroCluster 在整個過程中使用。
+
當站台發生災難時、它們不會受到保護。


