---
permalink: install-fc/task_reset_the_cisco_fc_switch_to_factory_defaults.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, reset, cisco, fc, switch, factory, defaults 
summary: 在安裝新的軟體版本和RCFs之前、您必須先清除Cisco交換器組態並執行基本組態。 
---
= 將Cisco FC交換器重設為原廠預設值
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安裝新的軟體版本和RCFs之前、您必須先清除Cisco交換器組態並執行基本組態。

您必須在MetroCluster 整個過程中、針對每個採用支援的FC交換器重複上述步驟。


NOTE: 顯示的輸出適用於Cisco IP交換器、但這些步驟也適用於Cisco FC交換器。

.步驟
. 將交換器重設為原廠預設值：
+
.. 刪除現有的組態：+「*寫入清除*」
.. 重新載入交換器軟體：+「*重新載入*」
+
系統會重新開機並進入組態精靈。在開機期間、如果您收到「Abort Auto Provisioning」（中止自動資源配置）提示並繼續正常設定？（是/否）[n]、您應該回應「* yes *」以繼續進行。

.. 在組態精靈中、輸入基本的交換器設定：
+
*** 管理密碼
*** 交換器名稱
*** 頻外管理組態
*** 預設閘道
*** SSH服務（遠端支援代理程式）完成組態精靈後、交換器會重新開機。


.. 出現提示時、輸入使用者名稱和密碼以登入交換器。
+
以下範例顯示登入交換器時的提示和系統回應。角括弧（「*」<「*」）會顯示您輸入資訊的位置。

+
[listing]
----
---- System Admin Account Setup ----
Do you want to enforce secure password standard (yes/no) [y]:y  **<<<**

    Enter the password for "admin": password  **<<<**
  Confirm the password for "admin": password  **<<<**
         ---- Basic System Configuration Dialog VDC: 1 ----

This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus3000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus3000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.
----
.. 在下一組提示中輸入基本資訊、包括交換器名稱、管理位址和閘道、並輸入「* rSA*」作為SSH金鑰、如範例所示：
+
[listing]
----
Would you like to enter the basic configuration dialog (yes/no): yes
  Create another login account (yes/no) [n]:
  Configure read-only SNMP community string (yes/no) [n]:
  Configure read-write SNMP community string (yes/no) [n]:
  Enter the switch name : switch-name **<<<**
  Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]:
    Mgmt0 IPv4 address : management-IP-address  **<<<**
    Mgmt0 IPv4 netmask : management-IP-netmask  **<<<**
  Configure the default gateway? (yes/no) [y]: y **<<<**
    IPv4 address of the default gateway : gateway-IP-address  **<<<**
  Configure advanced IP options? (yes/no) [n]:
  Enable the telnet service? (yes/no) [n]:
  Enable the ssh service? (yes/no) [y]: y  **<<<**
    Type of ssh key you would like to generate (dsa/rsa) [rsa]: rsa **<<<**
    Number of rsa key bits <1024-2048> [1024]:
  Configure the ntp server? (yes/no) [n]:
  Configure default interface layer (L3/L2) [L2]:
  Configure default switchport interface state (shut/noshut) [noshut]: shut **<<<**
  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]:
----
+
最後一組提示會完成組態設定：

+
[listing]
----
The following configuration will be applied:
  password strength-check
  switchname IP_switch_A_1
vrf context management
ip route 0.0.0.0/0 10.10.99.1
exit
  no feature telnet
  ssh key rsa 1024 force
  feature ssh
  system default switchport
  system default switchport shutdown
  copp profile strict
interface mgmt0
ip address 10.10.99.10 255.255.255.0
no shutdown

Would you like to edit the configuration? (yes/no) [n]:

Use this configuration and save it? (yes/no) [y]:
2017 Jun 13 21:24:43 A1 %$ VDC-1 %$ %COPP-2-COPP_POLICY: Control-Plane is protected with policy copp-system-p-policy-strict.

[########################################] 100%
Copy complete.

User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
.
.
.
IP_switch_A_1#
----


. 儲存組態：
+
[listing]
----
IP_switch_A_1# copy running-config startup-config
----
. 重新啟動交換器、然後等待交換器重新載入：
+
[listing]
----
IP_switch_A_1# reload
----
. 在其他三個MetroCluster 交換器上重複上述步驟、以進行「支援不整」的組態設定。

