---
permalink: install-fc/task_configure_ontap_on_a_system_that_uses_only_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, array luns, ontap 
summary: 如果您要設定ONTAP 搭配陣列LUN使用的功能、則必須設定根Aggregate和根Volume、保留空間以執行診斷和恢復作業、以及設定叢集。 
---
= 在ONTAP 僅使用陣列LUN的系統上設定功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您要設定ONTAP 搭配陣列LUN使用的功能、則必須設定根Aggregate和根Volume、保留空間以執行診斷和恢復作業、以及設定叢集。

.開始之前
* 必須將此系統連接至儲存陣列。ONTAP
* 儲存陣列管理員必須已建立LUN、並將其呈現ONTAP 給
* 儲存陣列管理員必須已設定LUN安全性。


您必須設定要搭配陣列LUN使用的每個節點。如果節點位於HA配對中、則必須先在一個節點上完成組態程序、然後再繼續在合作夥伴節點上進行組態設定。

.步驟
. 在主控台看到下列訊息時、請開啟主節點電源並按Ctrl-C中斷開機程序：
+
「按下CTRL－C以取得特殊的開機功能表。

. 在開機功能表上選取選項* 4（乾淨組態並初始化所有磁碟）*。
+
畫面會顯示可供ONTAP 展示的陣列LUN清單。此外、也會指定建立根磁碟區所需的陣列LUN大小。根磁碟區建立所需的大小不同ONTAP 於一個實體系統。

+
** 如果先前未指派任何陣列LUN、ONTAP 則會偵測並顯示可用的陣列LUN、如下列範例所示：
+
[listing]
----
mcc8040-ams1::> disk show  NET-1.6 -instance
                  Disk: NET-1.6
        Container Type: aggregate
            Owner/Home: mcc8040-ams1-01 / mcc8040-ams1-01
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: NETAPP_INF_1
                Vendor: NETAPP
                 Model: INF-01-00
         Serial Number: 60080E50004317B4000003B158E35974
                   UID: 60080E50:004317B4:000003B1:58E35974:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: 87.50GB
              Position: data
Checksum Compatibility: block
             Aggregate: eseries
                  Plex: plex0
Paths:
                                LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
mcc8040-ams1-01    2c             0  mccb6505-ams1:16      mccb6505-ams1:18      AO  INU  20330080e54317b4              1   4 Gb/S             0             0
mcc8040-ams1-01    2a             0  mccb6505-ams1:17      mccb6505-ams1:19      ANO RDY  20320080e54317b4              0   4 Gb/S             0             0

Errors:
-
----
** 例如、如果陣列LUN先前是透過維護模式指派的、則它們會在可用陣列LUN清單中標示為「本機」或「合作夥伴」、視您要安裝ONTAP 的節點或其HA合作夥伴是否選取陣列LUN而定：
+
在此範例中、索引編號為3和6的陣列LUN會標示為「本機」、因為先前已從這個特定節點指派：

+
[listing]
----

**********************************************************************
* No disks are owned by this node, but array LUNs are assigned.      *
* You can use the following information to verify connectivity from  *
* HBAs to switch ports.  If the connectivity of HBAs to switch ports *
* does not match your expectations, configure your SAN and rescan.   *
* You can rescan by entering 'r' at the prompt for selecting         *
* array LUNs below.

**********************************************************************
             HBA  HBA WWPN           Switch port      Switch port WWPN
              ---  --------           -----------      ----------------
              0e 500a098001baf8e0  vgbr6510s203:25      20190027f88948dd
              0f 500a098101baf8e0 vgci9710s202:1-17      2011547feeead680
              0g 500a098201baf8e0  vgbr6510s203:27      201b0027f88948dd
              0h 500a098301baf8e0 vgci9710s202:1-18      2012547feeead680


No native disks were detected, but array LUNs were detected.
You will need to select an array LUN to be used to create the root aggregate and root volume.

The array LUNs visible to the system are listed below.  Select one array LUN to be used to
create the root aggregate and root volume.  **The root volume requires 350.0 GB of space.**

 Warning: The contents of the array LUN you select will be erased by ONTAP prior to their use.

Index  Array LUN Name           Model   Vendor    Size    Owner   Checksum  Serial Number
-----  -----------------------  ------  ------  --------  ------  --------  ------------------------
   0   vgci9710s202:2-24.0L19   RAID5   DGC     217.3 GB          Block     6006016083402B0048E576D7
   1   vgbr6510s203:30.126L20   RAID5   DGC     217.3 GB          Block     6006016083402B0049E576D7
   2   vgci9710s202:2-24.0L21   RAID5   DGC     217.3 GB          Block     6006016083402B004AE576D7
   3   vgbr6510s203:30.126L22   RAID5   DGC     405.4 GB  local   Block     6006016083402B004BE576D7
   4   vgci9710s202:2-24.0L23   RAID5   DGC     217.3 GB          Block     6006016083402B004CE576D7
   5   vgbr6510s203:30.126L24   RAID5   DGC     217.3 GB          Block     6006016083402B004DE576D7
   6   vgbr6510s203:30.126L25   RAID5   DGC     423.5 GB  local   Block     6006016083402B003CF93694
   7   vgci9710s202:2-24.0L26   RAID5   DGC     423.5 GB          Block     6006016083402B003DF93694
----


. 選取要指派為根磁碟區的陣列LUN對應的索引編號。
+
陣列LUN的大小必須足以建立根磁碟區。

+
選取用於建立根磁碟區的陣列LUN會標示為「local（root）（本機（root））」。

+
在下列範例中、索引編號為3的陣列LUN會標示為建立根磁碟區：

+
[listing]
----

The root volume will be created on switch 0:5.183L33.

**ONTAP requires that 11.0 GB of space be reserved for use in diagnostic and recovery
operations.**  Select one array LUN to be used as spare for diagnostic and recovery operations.

Index Array LUN Name    Model       Vendor    Size   Owner           Checksum  Serial Number
----- ----------------- ----------  ------  -------- --------------  --------  ------------------------
   0  switch0:5.183L1   SYMMETRIX   EMC     266.1 GB                 Block     600604803436313734316631
   1  switch0:5.183L3   SYMMETRIX   EMC     266.1 GB                 Block     600604803436316333353837
   2  switch0:5.183L31  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237643666
   3  switch0:5.183L33  SYMMETRIX   EMC     658.3 GB local  (root)   Block     600604803436316263613066
   4  switch0:7.183L0   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313261356235
   5  switch0:7.183L2   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313438396431
   6  switch0:7.183L4   SYMMETRIX   EMC     658.3 GB                 Block     600604803436313161663031
   7  switch0:7.183L30  SYMMETRIX   EMC     173.6 GB                 Block     600604803436316538353834
   8  switch0:7.183L32  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237353738
   9  switch0:7.183L34  SYMMETRIX   EMC     658.3 GB                 Block     600604803436313737333662
----
. 選取對應於您要指派用於診斷與恢復選項之陣列LUN的索引編號。
+
陣列LUN的大小必須足以用於診斷和恢復選項。如有需要、您也可以選取多個陣列LUN、其組合大小大於或等於指定大小。若要選取多個項目、您必須輸入與您要選取的陣列LUN對應的所有索引編號的以逗號分隔的值、以供診斷與還原選項使用。

+
下列範例顯示選取用於建立根磁碟區的陣列LUN清單、以及用於診斷與還原選項的陣列LUN清單：

+
[listing]
----

Here is a list of the selected array LUNs
Index Array LUN Name     Model      Vendor    Size    Owner          Checksum  Serial Number
----- -----------------  ---------  ------  --------  -------------  --------  ------------------------
   2  switch0:5.183L31   SYMMETRIX  EMC     266.1 GB  local          Block     600604803436313237643666
   3  switch0:5.183L33   SYMMETRIX  EMC     658.3 GB  local   (root) Block     600604803436316263613066
   4  switch0:7.183L0    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313261356235
   5  switch0:7.183L2    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313438396431
Do you want to continue (yes|no)?
----
+

NOTE: 選取「no」會清除LUN選擇。

. 系統提示時輸入「* y*」以繼續安裝程序。
+
根Aggregate和根磁碟區隨即建立、其餘的安裝程序也會繼續進行。

. 輸入所需的詳細資料以建立節點管理介面。
+
以下範例顯示節點管理介面畫面、並顯示確認建立節點管理介面的訊息：

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
Enter the node management interface IP address: 192.0.2.66

Enter the node management interface netmask: 255.255.255.192
Enter the node management interface default gateway: 192.0.2.7
A node management interface on port e0M with IP address 192.0.2.66 has been created.

This node has its management address assigned and is ready for cluster setup.
----


在ONTAP 您要搭配陣列LUN使用的所有節點上設定好「功能」之後、您應該完成https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html["叢集設定程序"]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["介紹虛擬化安裝需求與參考資料FlexArray"]
