---
permalink: install-fc/task_fmc_mcc_transition_ensure_isls_are_in_the_same_port_group_and_configure_zon.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, ensure, port, group, configure, zoning 
summary: 您必須確定交換器間連結（ISL）位於相同的連接埠群組中、並設定MetroCluster 用於更新的區域劃分、以便順利共用交換器架構。 
---
= 確保ISL位於同一個連接埠群組中、並設定分區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須確定交換器間連結（ISL）位於相同的連接埠群組中、並針對MetroCluster 「靜態」組態設定分區、以便成功共用交換器架構。

.步驟
. 如果ISL不在同一個連接埠群組中、請將其中一個ISL連接埠移至與另一個連接埠群組相同的連接埠群組。
+
除了32到45、您可以使用任何可用的連接埠、這些連接埠是由新MetroCluster 的版本介紹所使用。建議的ISL連接埠為46和47。

. 請依照中的步驟進行 link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["在Brocade FC交換器上設定分區"] 區段以啟用主幹連線和QoS區域。
+
共享Fabric時的連接埠編號與一節中所示的不同。共享時、將連接埠46和47用於ISL連接埠。如果您移動了ISL連接埠、則需要使用中的程序 link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["在Brocade FC交換器上設定E連接埠（ISL連接埠）"] 一節來設定連接埠。

. [step3_zones]請依照中的步驟進行 link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["在Brocade交換器上設定非E連接埠"] 一節來設定非E連接埠。
. 除了MetroCluster 中的流量隔離（TI）區域之外、請勿刪除後端交換器中已存在的區域或區域集（適用於7-Mode Fabric） ,步驟3.。
. 請遵循中的步驟 link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["在Brocade FC交換器上設定E連接埠（ISL連接埠）"] 一節、將新MetroCluster 版的功能區新增至現有的功能區集。
+
以下範例顯示建立區域的命令和系統輸出：

+
[listing]
----
Brocade-6510-2K0GG:admin> zonecreate "QOSH2_FCVI_1", "2,32; 2,35; 1,32; 1,35"

Brocade-6510-2K0GG:admin> zonecreate "STOR_A_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 1,47"

Brocade-6510-2K0GG:admin> zonecreate "STOR_B_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 2,47"


Brocade-6510-2K0GG:admin> cfgadd config_1_FAB2, "QOSH2_FCVI_1; STOR_A_2_47; STOR_B_2_47"

Brocade-6510-2K0GG:admin> cfgenable "config_1_FAB2"
You are about to enable a new zoning configuration.
This action will replace the old zoning configuration with the
current configuration selected. If the update includes changes
to one or more traffic isolation zones, the update may result in
localized disruption to traffic on ports associated with
the traffic isolation zone changes
Do you want to enable 'config_1_FAB2' configuration  (yes, y, no, n): [no] yes

Brocade-6510-2K0GG:admin> cfgsave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] yes
Nothing changed: nothing to save, returning ...
Brocade-6510-2K0GG:admin>
----

