---
permalink: install-fc/task_download_and_install_the_cisco_fc_switch_rcf_files.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, install, cisco, fc, rcf, files 
summary: 您必須將RCF檔案下載到MetroCluster 以「支援」為基礎的各個交換器組態中。 
---
= 在 MetroCluster FC 組態中下載並安裝 Cisco FC 交換器 RCF 檔案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須將參考組態檔案 (RCF) 下載到 MetroCluster 架構組態中的每個交換器。

.開始之前
這項工作需要檔案傳輸軟體（例如FTP、Trivial File Transfer Protocol（TFTP）、SFTP或Secure Copy Protocol（SCP））、才能將檔案複製到交換器。

.關於這項工作
這些步驟必須重複執行MetroCluster 到位在整個過程中的每個Cisco FC交換器上。

您必須使用支援的交換器軟體版本。

https://hwu.netapp.com["NetApp Hardware Universe"]

共有四個 RCF，分別對應 MetroCluster 架構組態中的四個交換器。您必須使用與所用交換器型號相符的正確 RCF。

|===


| 交換器 | RCF 


 a| 
FC_SWIT_A_1
 a| 
「NX323232_v1.80交換器-a1.txt」



 a| 
FC_SWIT_A_2
 a| 
「NX323232_v1.1_Switch-a2.txt'



 a| 
FC_SWIT_B_1
 a| 
「NX323232_v1.80交換器-B1.txt」



 a| 
FC_SWIT_B_2
 a| 
「NX323232_v1.1_Switch-b2.txt'

|===

NOTE: 顯示的輸出適用於Cisco IP交換器、但這些步驟也適用於Cisco FC交換器。

.步驟
. 從 https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab["RCF下載頁面MetroCluster"]下載 Cisco FC RCF。
. 將 RCF 複製到交換器。
+
.. 將 RCF 複製到第一個交換器：
+
「copy sftp：//_root@ft-server_ip-address/tftpboot/switch-specif_bootflash：VRF管理」

+
在本例中， `NX3232_v1.80_Switch-A1.txt` RCF 從 SFTP 伺服器 `10.10.99.99`複製到本機啟動快閃記憶體。您必須使用 TFTP/SFTP 伺服器的 IP 位址以及需要安裝的 RCF 檔案名稱。

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/NX3232_v1.8T-X1_Switch-A1.txt bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/NX3232_v1.80_Switch-A1.txt /bootflash/NX3232_v1.80_Switch-A1.txt
Fetching /tftpboot/NX3232_v1.80_Switch-A1.txt to /bootflash/NX3232_v1.80_Switch-A1.txt
/tftpboot/NX3232_v1.80_Switch-A1.txt          100% 5141     5.0KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
IP_switch_A_1#
----
.. 對其他三個交換器重複上一個子步驟，確保將相符的 RCF 複本複製到對應的交換器。


. 在每台交換器上驗證 RCF 是否存在於每台交換器的 `bootflash`目錄中：
+
《Dir bootflash:》

+
下列範例顯示檔案存在於ip_switch_a_1上：

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
       5514    Jun 13 22:09:05 2017  NX3232_v1.80_Switch-A1.txt
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. 將本機啟動快閃記憶體中相符的 RCF 複製到每台交換器的執行中組態：
+
「copy bootflash：__switch-specific-RCF__.txt執行組態」

. 將每台交換器的運作組態中的 RCF 檔案複製到啟動組態中：
+
「copy running-config startup-config」

+
您應該會看到類似下列的輸出：

+
[listing]
----
IP_switch_A_1# copy bootflash:NX3232_v1.80_Switch-A1.txt running-config
IP_switch_A_1# copy running-config startup-config
----
. 重新載入交換器：
+
"重裝"

+
[listing]
----
IP_switch_A_1# reload
----
. 在其他三個MetroCluster 交換器上重複上述步驟、以進行REIP組態設定。

