---
permalink: install-fc/task_fmc_mcc_transition_configure_the_mcc_hardware_for_share_a_7_mode_brocade_6510_fc_fabric_dure_transition.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, hardware, brocade, fc, transition 
summary: 如果您的7-Mode Fabric MetroCluster 支援組態使用Brocade 6510交換器、您可以使用新的叢集MetroCluster 式VMware組態來共享現有的交換器架構。共享交換器架構意味著全新MetroCluster 的支援功能不需要全新的獨立交換器架構。只有Brocade 6510交換器才支援這項暫時性組態、以供轉換之用。 
---
= 設定硬體、以便在轉換期間共用Brocade 6510 FC架構
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的7-Mode Fabric MetroCluster 支援組態使用Brocade 6510交換器、您可以使用新的叢集MetroCluster 式VMware組態來共享現有的交換器架構。共享交換器架構意味著全新MetroCluster 的支援功能不需要全新的獨立交換器架構。只有Brocade 6510交換器才支援這項暫時性組態、以供轉換之用。

.開始之前
* 7-Mode Fabric MetroCluster 的不全功能必須使用Brocade 6510交換器。
+
如果MetroCluster 目前未使用Brocade 6510交換器、則在使用此程序之前、必須先將交換器升級至Brocade 6510。

* 7-Mode Fabric MetroCluster 的不全配置必須僅使用SAS儲存櫃。
+
如果現有組態包含FC儲存櫃（例如DS14mk4 FC）、則不支援FC交換器架構共用。

* 新的叢集MetroCluster 式支援功能組態所使用的交換器連接埠上的SFP必須支援16-Gbps速率。
+
現有的7-Mode架構MetroCluster 不只能使用8-Gbps或16-Gbps SFP連接至連接埠。

* 在四個Brocade 6510交換器上、連接埠24到45必須可用、才能連接新MetroCluster 的支援元件的連接埠。
* 您應該確認現有的交換器間連結（ISL）位於連接埠46和47上。
* Brocade 6510交換器必須執行7-Mode Fabric MetroCluster VMware和叢集ONTAP MetroCluster 式VMware組態所支援的FOS韌體版本。


在分享架構並完成MetroCluster 支援功能後、您可以從7-Mode Fabric MetroCluster 支援組態轉換資料。

轉換資料之後、您可以移除7-Mode Fabric MetroCluster 資訊纜線、並視需要將叢集ONTAP MetroCluster 式的VMware纜線移至先前用於7-Mode MetroCluster 資訊纜線的編號較低的連接埠。連接埠顯示在「檢閱FC交換器連接埠指派以供四節點MetroCluster 使用」一節中。 您必須調整重新排列連接埠的分區。

link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["FC交換器的連接埠指派（使用ONTAP 版本不含更新版本）"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["複本型轉換"]
