= 叢集對等關係的先決條件
:allow-uri-read: 


每MetroCluster 個站台均設定為其合作夥伴站台的對等站台。您必須熟悉設定對等關係的先決條件和準則。這在決定是否要使用共享或專用連接埠來處理這些關係時非常重要。

.相關資訊
http://["叢集與SVM對等化快速組態"]



== 叢集對等關係的先決條件

在設定叢集對等之前、您應該確認連接埠、IP位址、子網路、防火牆和叢集命名需求之間是否符合連線要求。



=== 連線需求

本機叢集上的每個叢集間LIF都必須能夠與遠端叢集上的每個叢集間LIF通訊。

雖然不需要、但一般而言、設定用於同一子網路中叢集間LIF的IP位址較為簡單。IP位址可以與資料生命體位於同一個子網路中、也可以位於不同的子網路中。每個叢集所使用的子網路必須符合下列需求：

* 子網路必須有足夠的IP位址、才能為每個節點分配一個叢集間LIF。
+
例如、在四節點叢集中、用於叢集間通訊的子網路必須有四個可用的IP位址。



每個節點都必須具有叢集間LIF、並在叢集間網路上具有IP位址。

叢集間LIF可以有一個IPv4位址或IPv6位址。


NOTE: 藉由支援兩種傳輸協定同時出現在叢集間的LIF上、藉由使用支援功能、即可將對等網路從IPv4移轉至IPv6。ONTAP在早期版本中、整個叢集的所有叢集間關係都是IPV4或IPV6。這表示變更傳輸協定可能會造成中斷。



=== 連接埠需求

您可以使用專用連接埠進行叢集間通訊、或共用資料網路所使用的連接埠。連接埠必須符合下列需求：

* 用於與特定遠端叢集通訊的所有連接埠必須位於相同的IPspace中。
+
您可以使用多個IPspace與多個叢集對等。只有在IPspace內才需要配對全網狀網路連線。

* 用於叢集間通訊的廣播網域必須包含每個節點至少兩個連接埠、以便叢集間通訊能夠從一個連接埠容錯移轉到另一個連接埠。
+
新增至廣播網域的連接埠可以是實體網路連接埠、VLAN或介面群組（ifgrps）。

* 所有連接埠都必須以纜線連接。
* 所有連接埠都必須處於正常狀態。
* 連接埠的MTU設定必須一致。




=== 防火牆需求

防火牆和叢集間防火牆原則必須允許下列傳輸協定：

* ICMP服務
* TCP傳輸到連接埠10000、11104和11105上所有叢集間LIF的IP位址
* 叢集間LIF之間的雙向HTTPS


預設的叢集間防火牆原則允許透過HTTPS傳輸協定和所有IP位址（0.00.0.0/0）進行存取。如有必要、您可以修改或取代原則。



== 使用專用連接埠時的考量事項

在判斷叢集間複寫是否使用專用連接埠是正確的叢集間網路解決方案時、您應該考量LAN類型、可用WAN頻寬、複寫時間間隔、變更率及連接埠數量等組態與需求。

請考量網路的下列層面、判斷使用專用連接埠是否為最佳的叢集間網路解決方案：

* 如果可用的WAN頻寬量與LAN連接埠的頻寬量相似、而且複寫時間間隔會在正常的用戶端活動存在時進行複寫、則應將乙太網路連接埠專用於叢集間複寫、以避免複寫與資料傳輸協定之間發生爭用。
* 如果資料傳輸協定（CIFS、NFS和iSCSI）所產生的網路使用率超過50%、則在發生節點容錯移轉時、將連接埠專門用於複寫、以允許不降級的效能。
* 當實體10 GbE或更快的連接埠用於資料和複寫時、您可以建立用於複寫的VLAN連接埠、並將邏輯連接埠專用於叢集間複寫。
+
連接埠的頻寬會在所有VLAN和基礎連接埠之間共用。

* 請考量資料變更率和複寫時間間隔、以及每個時間間隔必須複寫的資料量是否需要足夠的頻寬。如果共享資料連接埠、這可能會導致資料傳輸協定發生爭用。




== 共享資料連接埠時的考量

當判斷叢集間複寫的資料連接埠共用是否為正確的叢集間網路解決方案時、您應該考量LAN類型、可用的WAN頻寬、複寫時間間隔、變更率及連接埠數量等組態與需求。

請考量網路的下列層面、判斷共享資料連接埠是否為最佳的叢集間連線解決方案：

* 對於高速網路（例如40 Gigabit乙太網路（40 GbE）網路）、可能有足夠的本機LAN頻寬可在用於資料存取的相同40 GbE連接埠上執行複寫。
+
在許多情況下、可用的WAN頻寬遠低於10 GbE LAN頻寬。

* 叢集中的所有節點可能必須複寫資料並共用可用的WAN頻寬、使資料連接埠共用更容易接受。
* 共享資料與複寫連接埠可免除專用連接埠進行複寫所需的額外連接埠數。
* 複寫網路的最大傳輸單元（MTU）大小將與資料網路上使用的大小相同。
* 請考量資料變更率和複寫時間間隔、以及每個時間間隔必須複寫的資料量是否需要足夠的頻寬。如果共享資料連接埠、這可能會導致資料傳輸協定發生爭用。
* 當叢集間複寫的資料連接埠為共用時、叢集間的生命體可以移轉到同一個節點上任何其他具有叢集功能的連接埠、以控制用於複寫的特定資料連接埠。

