= 
:allow-uri-read: 


您必須在DR群組中的每個節點上建立鏡射資料Aggregate。

.關於這項工作
* 您應該知道新的Aggregate將使用哪些磁碟機。
* 如果您的系統中有多種磁碟機類型 （異質儲存），您應該了解如何確保選擇正確的磁碟機類型。
* 磁碟機由特定節點擁有；當您建立Aggregate時、該Aggregate中的所有磁碟機都必須由同一個節點擁有、此節點會成為該Aggregate的主節點。
+
在使用ADP的系統中、會使用分割區來建立集合體、將每個磁碟機分割至P1、P2和P3分割區。

* Aggregate名稱應符合您在規劃MetroCluster 時所決定的名稱配置。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["磁碟與Aggregate管理"]

* Aggregate 名稱在所有 MetroCluster 站台上必須是唯一的。這意味著站台 A 和站台 B 上不能有兩個名稱相同的 Aggregate 。



NOTE: 為了獲得最佳儲存效能和可用性，建議您為鏡像 Aggregate 保留至少 20% 的可用空間。雖然對於非鏡像 Aggregate，建議保留 10% 的可用空間，但這額外的 10% 空間可供檔案系統用於吸收遞增變更。由於 ONTAP 採用基於 Snapshot 的寫入時複製架構，因此遞增變更會增加鏡像 Aggregate 的空間使用率。不遵循這些最佳實務做法可能會對效能產生負面影響。

.步驟
. 顯示可用備援磁碟機清單：
+
`storage disk show -spare -owner <node_name>`

. 建立Aggregate：
+
"集合體建立-鏡射真"

+
如果您已透過叢集管理介面登入叢集，則可以在叢集中的任何節點上建立 aggregate。若要驗證 aggregate 是否已建立在特定節點上，請使用  `-node` 參數或指定該節點擁有的磁碟機。

+
您可以指定下列選項：

+
** Aggregate的主節點（也就是在正常作業中擁有Aggregate的節點）
** 要新增至集合體的特定磁碟機清單
** 要納入的磁碟機數量
+

NOTE: 在可用磁碟機數量有限的最低支援組態中、您必須使用force-min-Aggregate選項來建立三個磁碟RAID-DP Aggregate。

** 用於Aggregate的Checksum樣式
** 要使用的磁碟機類型
** 要使用的磁碟機大小
** 使用的磁碟機速度
** 集合體上RAID群組的RAID類型
** RAID群組中可包含的磁碟機數目上限
** 是否允許使用不同RPM的磁碟機
+
有關這些選項的更多信息，請參見"shorage aggregate creation"手冊頁。

+
下列命令會建立10個磁碟的鏡射Aggregate：

+
[listing]
----
cluster_A::> storage aggregate create aggr1_node_A_1 -diskcount 10 -node node_A_1 -mirror true
[Job 15] Job is queued: Create aggr1_node_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----


. 驗證新Aggregate的RAID群組和磁碟機：
+
`storage aggregate show-status -aggregate <aggregate-name>`


