---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: 每個版本都提供 ONTAP Mediator 的新功能。  最新功能。 
---
= ONTAP Mediator 對MetroCluster IP 的支援有哪些新特性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解MetroCluster IP 的新功能和增強功能，以支援ONTAP Mediator。

有關ONTAP Mediator 每個版本的功能和增強特性的詳細信息，請參閱：link:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["ONTAP Mediator 的新增功能"^] 。

[cols="4,1"]
|===
| ONTAP Mediator 功能 | 可用的開始 


 a| 
從 ONTAP Mediator 1.12.1 開始，設定了 HTTPS 的單一 ONTAP Mediator 執行個體可以同時監控以下組態：

* 如果安裝在至少有 8 個 CPU 核心和至少 16GB RAM 的主機上，最多可以有 10 個四節點或 5 個八節點的 MetroCluster IP 組態。
* 如果安裝在具有 2 核心 CPU 的主機作業系統上，則需要一個四節點 MetroCluster IP 組態和一個 SnapMirror 活動同步對等關係。


link:../install-ip/concept_mediator_requirements.html#mediator-multiple-mccip["深入了解 ONTAP Mediator 對多個 MetroCluster IP 組態的支援"]。
 a| 
ONTAP 9.19.1



 a| 
ONTAP Mediator 1.12 支援配置使用 HTTPS 進行 MetroCluster IP 通訊的 ONTAP Mediator。HTTPS 透過使用 SSL/TLS 加密整個工作階段來提高安全性。您可以選擇安裝僅使用 HTTPS 傳輸協定的 ONTAP Mediator。如果使用此安裝方法，則不會安裝 SCST 套件。有關安裝僅使用 HTTPS 傳輸協定的 ONTAP Mediator 的更多資訊，請參閱 link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation["ONTAP Mediator 的 HTTPS 和 iSCSI 安裝選項"^]。

link:../install-ip/concept_mediator_requirements.html#select-a-communication-protocol-for-ontap-mediator["深入瞭解 ONTAP Mediator 中的 iSCSI 和 HTTPS 傳輸協定"]。
 a| 
ONTAP 9.19.1



 a| 
在MetroCluster IP 配置中， ONTAP Mediator 1.11 或更高版本支援 IPv6。

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["為MetroCluster IP 配置設定ONTAP調解器"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 增加了使用單一ONTAP Mediator 實例管理多達 10 個MetroCluster IP 配置的支援。

link:../install-ip/concept_mediator_requirements.html["準備在MetroCluster IP 配置中安裝ONTAP Mediator"]
 a| 
ONTAP 9.18.1



 a| 
在環境關機的情況下、支援中介協助的自動非計畫性切換（ MAUSO ）。

如果某個站台因環境關機而正常關機、則會觸發 MAUSO 。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAP 調解器如何支援自動排程外切換"]
 a| 
ONTAP 9.13.1.12.9.11.9.11.



 a| 
MetroCluster IP 配置中對 ONTAP 調解器的初步支持
 a| 
更新ONTAP

|===