---
permalink: releasenotes/mcc-config-support-features.html 
sidebar: sidebar 
keywords: metrocluster, configuration, support for ontap features 
summary:  
---
= MetroCluster 組態支援 ONTAP 功能的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個 ONTAP 9 資料管理軟體版本都提供全新且增強的功能、可改善 ONTAP MetroCluster 組態的功能、管理能力及效能。

如需影響 ONTAP MetroCluster 組態的已知問題、限制和升級注意事項詳細資料、請參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["發行說明ONTAP"^]。您必須使用 NetApp 帳戶登入、或建立帳戶才能存取版本資訊。

[cols="20,65,15"]
|===
| MetroCluster 組態中支援的功能 | 說明 | 可用的開始 


 a| 
MetroCluster IP 支援 NVMe
 a| 
四節點 MetroCluster IP 組態支援 NVMe / TCP 前端主機傳輸協定。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["SAN組態MetroCluster"^]
 a| 
ONTAP 9.15.1.1



 a| 
S3 物件儲存支援鏡射和無鏡射的集合體
 a| 
您可以在 MetroCluster IP 和 FC 組態中的鏡射或無鏡射集合體中、在 SVM 上啟用 S3 物件儲存伺服器。

https://docs.netapp.com/us-en/ontap/s3-config/index.html["S3組態總覽"]
 a| 
ONTAP 9.14.1.



 a| 
支援在 MetroCluster 叢集中的鏡射和非鏡射集合體上佈建 S3 儲存區
 a| 
您可以在 MetroCluster 組態中的鏡射或無鏡射集合體上建立貯體。

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html["在 MetroCluster 組態中的鏡射或無鏡射 Aggregate 上建立貯體"]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IP 支援 NVMe
 a| 
四節點 MetroCluster IP 組態支援 NVMe / FC 傳輸協定。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["SAN組態MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
支援 MetroCluster IP 和 MetroCluster 網路附加組態中的前端主機傳輸協定
 a| 
支援前端主機傳輸協定（例如 NFS 和 iSCSI ）的 IPsec 可在 MetroCluster IP 和 MetroCluster 網路附加組態中使用。

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["透過有線加密設定IP安全性（IPsec）"]
 a| 
零點9.11.1. ONTAP



 a| 
一致性群組
 a| 
MetroCluster 組態支援一致性群組。
 a| 
更新ONTAP



 a| 
可鏡射到各種組態FabricPool MetroCluster
 a| 
您可以在 MetroCluster 組態上設定鏡射 FabricPool 、將冷資料分層至兩個不同的故障區域。

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html["設定物件存放區以FabricPool 供在MetroCluster 一個不確定的組態中使用"]
 a| 
更新ONTAP



 a| 
SVM 災難恢復
 a| 
MetroCluster 組態中的作用中儲存虛擬機器（ SVM ）可作為 SnapMirror SVM 災難恢復功能的來源。
 a| 
版本9.5 ONTAP

|===