---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= MetroCluster 功能的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個 ONTAP 9 資料管理軟體版本都提供全新且增強的功能、可改善 ONTAP MetroCluster 組態的功能、管理能力及效能。

如需影響 ONTAP MetroCluster 組態的已知問題、限制和升級注意事項詳細資料、請參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["發行說明ONTAP"^]。您必須使用 NetApp 帳戶登入、或建立帳戶才能存取版本資訊。

[cols="20,65,15"]
|===
| MetroCluster 組態中支援的功能 | 說明及深入瞭解的地方 | 可用的開始 


 a| 
MetroCluster IP 配置中 FAS50 系統的快閃記憶體快取支持
 a| 
在MetroCluster IP 配置中，FAS50 系統支援快閃記憶體快取。

link:../install-ip/concept_considerations_drive_assignment.html#disk-assignment-on-fas50-systems-with-flash-cache["在配備快閃記憶體快取的 FAS50 系統上進行磁碟分配"]
 a| 
ONTAP 9.18.1



 a| 
支援端點對端點加密的 MetroCluster IP
 a| 
以下系統支援端對端加密，以加密MetroCluster IP 配置中的站點之間的後端流量，例如 NVlog 和儲存複製資料。

* AFF A800和AFF C800
* AFF A20、 AFF A30、 AFF C30、 AFF A50、 AFF C60
* AFF A70 、 AFF A90 、 AFF A1K 、 AFF C80
* FAS50 、 FAS70 、 FAS90


link:../maintain/task-configure-encryption.html["在 MetroCluster IP 組態中設定端點對端點加密"]
 a| 
ONTAP 9.17.1



 a| 
限制MetroCluster IP 配置的更改
 a| 
ONTAP 9.17.1 包含四節點MetroCluster IP 配置的以下限制更新：

* AFF C800、 AFF A800、 AFF A900、 AFF A90和AFF A1K系統有以下更新的限制：
+
** 每個節點的FlexVol volume限制：1250
** SVM 限制：每個叢集 64 個 SVM
** LIF 數量：每個集群 256 個 LIF


* AFF A400、 AFF C400、 ASA A400、 ASA C400、 AFF C80、 AFF A70和AFF A50 系統有下列更新的限制：
+
** 每個聚合體（單一或多個）的FlexVol volume限制：625
** 每個節點的FlexVol volume限制：1250
** 每個高可用性 (HA) 對的FlexVol volume限制：2500
** 每個集群的FlexVol volume限制：5000
** SVM 限制：每個叢集 64 個 SVM
** LIF 數量：每個集群 256 個 LIF




請參閱link:https://hwu.netapp.com["Hardware Universe"^]了解更多。
 a| 
ONTAP 9.17.1



 a| 
使用憑證更新 FibreBridge 韌體
 a| 
如果伺服器需要憑證來下載韌體包，您可以使用憑證來更新 FibreBridge 橋接器上的韌體。

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["更新光纖橋接器上的韌體"]
 a| 
ONTAP 9.16.1.



 a| 
SVM 資料移動性支援，可移轉 MetroCluster 組態
 a| 
ONTAP 支援下列 MetroCluster SVM 移轉：

* 在非 MetroCluster HA 配對和 MetroCluster IP 組態之間移轉 SVM
* 在兩個 MetroCluster IP 組態之間移轉 SVM
* 在 MetroCluster FC 組態和 MetroCluster IP 組態之間移轉 SVM


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["SVM資料移動性"^]
 a| 
ONTAP 9.16.1.



 a| 
BGP 對等群組的 MD5 驗證支援
 a| 
ONTAP 支援 BGP 對等群組上的 MD5 驗證，以保護 BGP 工作階段。啟用 MD5 時， BGP 工作階段只能在獲授權的對等點之間建立和處理，以防止未獲授權的使用者可能中斷工作階段。

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["設定虛擬IP（VIP）LIF"^]
 a| 
ONTAP 9.16.1.



 a| 
支援端點對端點加密的 MetroCluster IP
 a| 
AFF A400 、 FAS8300 和 FAS8700 系統支援端點對端點加密、可在 MetroCluster IP 組態中的站台之間加密後端流量、例如 NVlog 和儲存複寫資料。

link:../maintain/task-configure-encryption.html["在 MetroCluster IP 組態中設定端點對端點加密"]
 a| 
ONTAP 9.15.1.1



 a| 
AFF A800 和 AFF C800 系統上四節點 MetroCluster IP 組態的磁碟區限制增加
 a| 
在四節點 MetroCluster IP 組態中、 AFF A800 和 AFF C800 系統的下列磁碟區限制已增加：

* 每個集合體的 FlexVol 磁碟區數量上限從 200 個增加到 625 個。
* 每個節點的 FlexVol 磁碟區數量上限從 800 個增加至 1250 個。
* 每個 HA 對的最大FlexVol卷數從 1600 個增加到 2500 個。

 a| 
ONTAP 9.15.1.1



 a| 
MetroCluster IP 支援 NVMe
 a| 
四節點 MetroCluster IP 組態支援 NVMe / TCP 前端主機傳輸協定。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["SAN組態MetroCluster"^]
 a| 
ONTAP 9.15.1.1



 a| 
AFF A900 系統上四節點 MetroCluster IP 組態的磁碟區限制增加
 a| 
在四節點 MetroCluster IP 組態中、 AFF A900 系統的下列磁碟區限制已增加：

* 每個集合體的 FlexVol 磁碟區數量上限從 200 個增加到 625 個。
* 每個節點的 FlexVol 磁碟區數量上限從 800 個增加至 1250 個。
* 每個 HA 對的最大FlexVol卷數從 1600 個增加到 2500 個。

 a| 
ONTAP 9.14.1.



 a| 
S3 物件儲存支援鏡射和無鏡射的集合體
 a| 
您可以在 MetroCluster IP 和 FC 組態中的鏡射或無鏡射集合體中、在 SVM 上啟用 S3 物件儲存伺服器。

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["S3 支援 MetroCluster"^]
 a| 
ONTAP 9.14.1.



 a| 
支援在 MetroCluster 叢集中的鏡射和非鏡射集合體上佈建 S3 儲存區
 a| 
您可以在 MetroCluster 組態中的鏡射或無鏡射集合體上建立貯體。

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets["在 MetroCluster 組態中的鏡射或無鏡射集合體上建立 ONTAP S3 儲存區"^]
 a| 
ONTAP 9.14.1.



 a| 
使用 MetroCluster IP 和乙太網路附加儲存設備的共用交換器、從 MetroCluster FC 移轉至 MetroCluster IP
 a| 
您可以使用共用儲存交換器、在不中斷營運的情況下、從 MetroCluster FC 移轉至 MetroCluster IP 組態。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["不中斷營運地從MetroCluster 一個不中斷的FC移轉至MetroCluster 一個支援功能的IP組態ONTAP （版本號：9.8及更新版本）"]
 a| 
ONTAP 9.13.1.12.9.11.9.11.



 a| 
從八節點 MetroCluster FC 組態到 MetroCluster IP 組態的不中斷轉換
 a| 
您可以不中斷地將工作負載和資料從現有的八節點 MetroCluster FC 組態移轉至新的 MetroCluster IP 組態。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["從 MetroCluster FC 無中斷地轉換至 MetroCluster IP 組態"]
 a| 
ONTAP 9.13.1.12.9.11.9.11.



 a| 
使用切換和切換功能進行四節點 MetroCluster IP 組態升級
 a| 
您可以使用切換和切換來升級四節點 MetroCluster IP 組態中的控制器 `system controller replace` 命令。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["升級四節點 MetroCluster IP 組態中的控制器"]
 a| 
ONTAP 9.13.1.12.9.11.9.11.



 a| 
在環境關機時觸發中介協助的自動非計畫性切換（ MAUSO ）
 a| 
如果某個站台因環境關機而正常關機、則會觸發 MAUSO 。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["如何支援自動非計畫性切換ONTAP"]
 a| 
ONTAP 9.13.1.12.9.11.9.11.



 a| 
支援八節點 MetroCluster IP 組態
 a| 
您可以在八節點 MetroCluster IP 組態中升級控制器和儲存設備、方法是將組態擴充為暫時性的十二節點組態、然後移除舊的 DR 群組。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["重新整理四節點MetroCluster 的不全功能IP組態"]
 a| 
ONTAP 9.13.1.12.9.11.9.11.



 a| 
MetroCluster IP 組態轉換為共用儲存 MetroCluster 交換器組態
 a| 
您可以將 MetroCluster IP 組態轉換為共用儲存 MetroCluster 交換器組態。

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["更換IP交換器"]
 a| 
ONTAP 9.13.1.12.9.11.9.11.



 a| 
MetroCluster IP 組態中的 MetroCluster 自動強制切換功能
 a| 
您可以在 MetroCluster IP 組態中啟用 MetroCluster 自動強制切換功能。這項功能是由內建人員輔助的非計畫性切換（MAUSO）功能的延伸。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["自動切換限制"]
 a| 
ONTAP 9.12.1



 a| 
SVM 上的 S3 、位於 MetroCluster IP 組態中未鏡射的 Aggregate 上
 a| 
您可以在 MetroCluster IP 組態中的未鏡射集合體上、在 SVM 上啟用 ONTAP Simple Storage Service （ S3 ）物件儲存伺服器。

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["S3 支援 MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IP 支援 NVMe
 a| 
四節點 MetroCluster IP 組態支援 NVMe / FC 傳輸協定。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["SAN組態MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
支援 MetroCluster IP 和 MetroCluster 網路附加組態中的前端主機傳輸協定
 a| 
支援前端主機傳輸協定（例如 NFS 和 iSCSI ）的 IPsec 可在 MetroCluster IP 和 MetroCluster 網路附加組態中使用。

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["透過有線加密設定IP安全性（IPsec）"^]
 a| 
ONTAP 9.12.1



 a| 
從 MetroCluster FC 組態轉換為 AFF A250 或 FAS500f MetroCluster IP 組態
 a| 
您可以從 MetroCluster FC 組態轉換為 AFF A250 或 FAS500f MetroCluster IP 組態。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["移動本機叢集連線"]
 a| 
零點9.11.1. ONTAP



 a| 
一致性群組
 a| 
MetroCluster 組態支援一致性群組。

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups["一致性群組的MetroCluster 不一致性"^]
 a| 
零點9.11.1. ONTAP



 a| 
簡化 MetroCluster FC 組態中節點的控制器升級
 a| 
使用切換和切換功能的升級程序已簡化。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["使用MetroCluster 切換和切換功能升級採用SFC組態的控制器"]
 a| 
零點9.10.1 ONTAP



 a| 
第 3 層共享鏈路的 IP 支援
 a| 
MetroCluster IP 組態可透過 IP 路由（第 3 層）後端連線來實作。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["第3層廣域網路的考量"]
 a| 
部分9.9.1 ONTAP



 a| 
支援八節點 MetroCluster 組態
 a| 
IP 和光纖附加 MetroCluster 組態支援永久性的八節點叢集。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["安裝MetroCluster 和連接線的元件"]
 a| 
部分9.9.1 ONTAP

|===