---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks 
summary: 執行MetroCluster 硬體維護工作時、請務必選擇正確的程序。 
---
= 瞭解 MetroCluster 維護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解如何為 MetroCluster 維護工作做好準備，並為您的組態選擇正確的維護程序。



== 準備進行維護工作

在執行任何維護程序之前，請先檢閱中的資訊link:enable-console-logging-before-maintenance.html["準備 MetroCluster 維護"]。


NOTE: 在執行維護工作之前，您必須啟用主控台記錄，並移除 ONTAP Mediator 或 tiebreaker 監控。



== 不同類型 MetroCluster 組態的維護程序

* 如果您有 MetroCluster IP 組態、請參閱中的程序link:task-modify-ip-netmask-properties.html["MetroCluster IP 組態的維護程序"]。
* 如果您有 MetroCluster FC 組態、請參閱中的程序link:task_modify_switch_or_bridge_ip_address_for_health_monitoring.html["MetroCluster FC 組態的維護程序"]。
* 如果您在設定的特定章節中找不到程序，請參閱中的程序link:task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html["所有 MetroCluster 組態的維護程序"]。




== 所有其他維護程序

下表提供與 MetroCluster 維護相關的程序連結、這些程序不在上述三節中列出：

|===


| 元件 | 邊類（FC或IP）MetroCluster | 工作 | 程序 


 a| 
軟件ONTAP
 a| 
兩者兼具
 a| 
軟體升級ONTAP
 a| 
https://docs.netapp.com/us-en/ontap/upgrade/index.html["升級、回復或降級"^]



 a| 
控制器模組
 a| 
兩者兼具
 a| 
FRU更換（包括控制器模組、PCIe卡、FC-VI卡等）


NOTE: 不MetroCluster 支援將儲存控制器模組或NVRAM卡移至各個不支援的儲存系統。
 a| 
https://docs.netapp.com/platstor/index.jsp["ONTAP 硬體系統文件"^]



 a| 
升級與擴充
 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["升級與擴充MetroCluster"]



 a| 
從FC移轉至IP連線
 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["從MetroCluster 靜態FC移轉至MetroCluster 靜態IP"]



 a| 
磁碟機櫃
 a| 
FC
 a| 
所有其他機櫃維護程序。可使用標準程序。
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["維護DS460C DS224C和DS212C磁碟櫃"^]



 a| 
IP
 a| 
所有機櫃維護程序。可使用標準程序。

如果要新增磁碟櫃以供未鏡射的Aggregate使用、請參閱 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html["使用無鏡射Aggregate時的考量"^]
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["維護DS460C DS224C和DS212C磁碟櫃"^]

|===