---
permalink: maintain/task_migrating_root_agg_with_adp.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, migrate, root, aggregate, adp, disks, partition, advanced, disk, partitioning 
summary: 您可以不中斷地移轉使用進階磁碟分割（ ADP ）的現有根集合體。 
---
= 在 MetroCluster IP 組態中移轉使用 ADP 設定的根集合體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


如果根集合體空間不足、或您想要從使用低容量 SSD 切換到大容量 SSD 、您可以不中斷地移轉使用進階磁碟分割（ ADP ）的現有根集合體。

.關於這項工作
* 必須啟用本機高可用度（ HA ）配對、才能進行儲存容錯移轉。
* 此程序不中斷營運。
* 組態應保持穩定狀態、並正常提供資料、不會經常中斷。
* 在此程序中、請勿執行任何硬體升級或任何可能造成中斷的其他作業。
* 您一次只能移轉一個根 Aggregate 。請勿嘗試同時移轉兩個根集合體。


.步驟
. [[step 1 、 Verify the health of the configuration ]] 檢查組態的健全狀況。
+
.. 檢查MetroCluster 每個叢集上的功能是否已設定且處於正常模式：
 +
`metrocluster show`
+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 檢查每個節點是否已啟用鏡射：
+
「不一樣的秀」MetroCluster

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. 檢查MetroCluster 這些元件是否健全：
+
《不一樣的跑程》MetroCluster

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. 檢查是否沒有健全狀況警示：
+
「系統健全狀況警示顯示」



. 確認已啟用本機 HA 配對以進行儲存容錯移轉：
+
「容錯移轉顯示」

+
輸出應指出兩個節點均可進行接管：

+
[listing]
----
cluster_A::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ---------------------------
cluster-01     cluster-02      true     Connected to cluster-02

cluster-02     cluster-01      true     Connected to cluster-01
2 entries were displayed.
----
. 將備用磁碟歸零：
+
`run * disk zero spares`

. 識別根 Aggregate 大小：
+
`node run local aggr status -r <root_agg_name>`

+
在以下範例中、根 Aggregate 在「 Pool0 」中有十個磁碟、在「 Pool1 」中有十個磁碟。

+
[listing]
----
cluster_A::*> node run local aggr status -r <root_agg_name>
Aggregate <root_agg_name> (online, raid_dp, mirrored, fast zeroed) (block checksums)
  Plex /<root_agg_name>/plex0 (online, normal, active, pool0)
    RAID group /<root_agg_name>/plex0/rg0 (normal, block checksums, max_wdbn 5767167)

      RAID Disk Device  HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------  ------------- ---- ---- ---- ----- --------------    --------------
      dparity   e2a.11.0.0P3    e2a   11  0   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      parity    e10b.11.3.1P3   e10b  11  1   NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e2a.11.0.2P3    e2a   11  2   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e2a.11.0.3P3    e2a   11  3   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e2a.11.0.4P3    e2a   11  4   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.5P3   e10b  11  5   NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.12P3  e10b  11  12  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.13P3  e10b  11  13  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.14P3  e10b  11  14  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.15P3  e10b  11  15  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)

  Plex /<root_agg_name>/plex2 (online, normal, active, pool1)
    RAID group /<root_agg_name>/plex2/rg0 (normal, block checksums, max_wdbn 5767167)

      RAID Disk Device  HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------  ------------- ---- ---- ---- ----- --------------    --------------
      dparity   0m.i2.2L1P3     0m    22  5          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      parity    0m.i1.0L36P3    0m    22  14         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i2.2L18P3    0v    22  12         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i2.3L17P3    0v    22  2          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i1.0L25P3    0v    22  13         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i1.0L40P3    0v    22  4          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0m.i1.1L39P3    0m    22  17         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0m.i1.1L46P3    0m    22  15         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0m.i2.3L13P3    0m    22  0          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i1.1L26P3    0v    22  1          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)

cluster_A::*>
----
. 指派容器磁碟。
+
指派磁碟之前、請確認已將建議的備用磁碟機數量指派給每個節點。這些磁碟機會在根 Aggregate 移轉之前進行分割。如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_drive_assignment.html["自動指派磁碟機和ONTAP ADP系統的考量事項、位於更新版本的更新版本"]。

+
執行下列命令來指派磁碟：

+
`storage disk assign -disklist 1.11.0,1.11.1,…  -owner cluster-01 -pool 0`

. 識別根分割區大小。
+
根分割區大小取決於每個節點上可供分割區使用的磁碟數量。NetApp 建議每個節點至少有 12 個磁碟機可用於分割區。

+
您可以使用下表來判斷根 Aggregate 配置：

+
[cols="25,75"]
|===
| 要分割的磁碟數 | 根 Aggregate 配置 


| 每個節點 4 個磁碟 | 2 個資料磁碟機和 2 個同位元磁碟機 


| 每個節點 12 個磁碟 | 8 個資料磁碟機、 2 個同位元磁碟機和 2 個備用磁碟機 


| 每個節點 24 個磁碟 | 20 個資料磁碟機、 2 個同位元磁碟機和 2 個備用磁碟機 
|===
+
若要識別根分割區大小、您可以在所有資料磁碟機之間平均分配 4K 區塊的總數。

+
例如、如果您的根彙總配置是 8 個資料磁碟機、 2 個同位元磁碟機、以及 2 個根彙總大小為 112958795 區塊的備用磁碟機、則必須將 112958795 除以 8 才能取得根分割區大小。

+
（ 112958795 / 8 ） = 14119849.375

+
此圖四捨五入後、根分割區大小為 14119850 。

. 分割根 Aggregate 中的每個磁碟：
+
`cluster_A*> disk partition -n 3 -i 3 -b <root_partition_size> <disk_id>`

. 指派分割區。
+

NOTE: 在使用ADP的系統中、會使用分割區來建立集合體、將每個磁碟機分割至P1、P2和P3分割區。

+
.. 將 P3 分割區指派給擁有容器磁碟的同一個節點：
+
`storage disk assign -disk <disk_id> -root true -pool 0 -owner cluster-01`

.. 將 P1 分割區指派給 HA 配對中系統 ID 編號較低的系統：
+
`storage disk assign -disk <disk_id> -data1 true -pool 0 -owner cluster-01`

.. 將 P2 分割區指派給 HA 配對中系統 ID 編號較高的系統：
+
`storage disk assign -disk <disk_name> -data2 true -pool 0 -owner cluster-02`

+
對每個分割磁碟重複此步驟。



. 確認可以接管：
+
「容錯移轉顯示」

+
[listing]
----
cluster_A::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ---------------------------
cluster-01     cluster-02      true     Connected to cluster-02

cluster-02     cluster-01      true     Connected to cluster-01
2 entries were displayed.
----
. 移轉根 Aggregate 。
+
針對每個節點、執行移轉、指定 Pool0 中的磁碟清單、並將目標 RAID 類型指定為參數：

+
`system node migrate-root -node cluster-01 -disklist <pool0_disk_list> -raid-type <target_raid_type>`

+
例如、如果「 cluster-01 」的根 Aggregate 包含十個具有「 RAID_dp 」的磁碟、則下列命令會移轉根 Aggregate ：

+
[listing]
----
system node migrate-root -node cluster-01 -disklist 1.11.1.P3,1.11.2.P3,1.11.3.P3,1.11.4.P3,1.11.5.P3,1.11.6.P3,1.11.7.P3,1.11.8.P3,1.11.9.P3,1.11.10.P3 -raid-type raid_dp

Warning: This is a partially automated and guided procedure for migrating the
         root aggregate on the node "cluster-01".
         Negotiated switchover is about to start.
         Warning: This operation will create a new root aggregate and replace
         the existing root on the node "cluster-01". The existing root
         aggregate will be discarded.
Do you want to continue? {y|n}: y

Info: Started migrate-root job. Run "job show -id 51 -instance" command to
      check the progress of the job.
      Once the job is complete, mirror the root aggregate using the "storage
      aggregate mirror" command
----
+

IMPORTANT: 如果磁碟數量不足、請新增更多磁碟或選擇不同的 RAID 類型。

+
移轉程序可能需要幾分鐘的時間才能完成。在移轉期間、節點會重新開機數次、而您可能會在其他節點上看到錯誤、您可以安全地忽略這些錯誤、並等待移轉程序完成。

. 您也可以監控移轉進度。
+
從第二個站台執行：

+
`job show -id 51 -instance`

. 重新啟用所有 MetroCluster IP 節點的 RAID 自動分割：
+
`storage raidlm policy modify -node <node> -policy-name auto_partition_ssds_post_init -policy-type Shared-Disk -is-enable true`

. 確認移轉成功：
+
`run local aggr status -r <root_agg_name>`

+
[listing]
----
cluster_A::*> node run local aggr status -r <root_agg_name>
Aggregate <root_agg_name> (online, raid0, fast zeroed) (block checksums)
  Plex /<root_agg_name>/plex0 (online, normal, active, pool0)
    RAID group /<root_agg_name>/plex0/rg0 (normal, block checksums, max_wdbn 6127616)

      RAID Disk Device  HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------  ------------- ---- ---- ---- ----- --------------    --------------
      data      e2a.11.0.16P3   e2a   11  16  NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.17P3  e10b  11  17  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)

cluster_A::*>
----
. 重複步驟至 <<step_1,驗證組態的健全狀況>>。

