---
permalink: maintain/task_upgrade_or_downgrad_the_firmware_on_a_cisco_fc_switch_mcc.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, downgrade, firmware, cisco, fc, switch 
summary: 若要升級或降級Cisco FC交換器上的韌體、您必須使用Cisco專屬的命令來停用交換器、執行並驗證升級、以及重新開機並重新啟用交換器。 
---
= 升級或降級Cisco FC交換器上的韌體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要升級或降級Cisco FC交換器上的韌體、您必須使用Cisco專屬的命令來停用交換器、執行並驗證升級、以及重新開機並重新啟用交換器。

.關於這項工作
確認您已檢查並執行下列組態工作：

* 系統纜線正確。
* 所有通往儲存櫃的路徑均可用。
* 磁碟櫃堆疊穩定。
* FC 交換器架構健全。
* 系統中的所有元件都正常運作。
* 系統正常運作。
* 您擁有管理密碼、並可存取 FTP 或 SCP 伺服器。
* 已啟用主控台記錄。
+
link:enable-console-logging-before-maintenance.html["啟用主控台記錄"]



交換器架構在韌體升級或降級期間會停用、MetroCluster 而支援的功能則是仰賴第二個架構來繼續運作。

您必須在每個交換器架構上連續重複此工作、以確保所有交換器都執行相同的韌體版本。

您必須擁有韌體檔案。


NOTE: 此程序不中斷營運、約需一小時完成。

.步驟
. 登入網路中的每個交換器。
+
在這些範例中、交換器稱為FC_switch_a_1和FC_switch_B_1。

. 確定每個交換器上的bootflash目錄是否有足夠的空間：
+
’*目錄bootflash*

+
如果沒有、請使用「刪除bootflash:file_name」命令刪除不需要的韌體檔案。

. 將Kickstart和系統檔案複製到交換器：
+
‘* copy _source_filetarGet_file_*’

+
在以下範例中、kickstart檔案（「m9200-s2ek9-kickstart-mz.5.2.1.bin」）和系統檔案（「m9200-s2ek9-mz.5.2.1.bin」）位於FTP伺服器的路徑：him/韌 體/`。

+
以下範例顯示在FC_switch_a_1上發出的命令：

+
[listing]
----
FC_switch_A_1# copy ftp://10.10.10.55/firmware/m9200-s2ek9-kickstart-mz.5.2.1.bin bootflash:m9200-s2ek9-kickstart-mz.5.2.1.bin
FC_switch_A_1# copy ftp://10.10.10.55/firmware/m9200-s2ek9-mz.5.2.1.bin bootflash:m9200-s2ek9-mz.5.2.1.bin
----
. 停用此網路中兩個交換器上的所有VSAN。
+
請使用下列程序來停用VSAN：

+
.. 開啟組態終端機：
+
’*組態t*

.. 輸入：「* vSAN database*」
.. 檢查VSAN的狀態：
+
「* show vSAN*」

+
所有VSAN都必須處於作用中狀態。

.. 暫停VSAN：
+
「* vSAN _vSAN-num_ suspend*」

+
*範例：*「vSAN 10 suspend」

.. 再次檢查VSAN的狀態：
+
「* show vSAN*」+「All VSAN」必須暫停。

.. 結束組態終端機：
+
《*結束*》

.. 儲存組態。
+
‘*複製執行組態啟動組態*’

+
以下範例顯示FC_switch_a_1的輸出：

+
[listing]
----
FC_switch_A_1# config t
Enter configuration commands, one per line.  End with CNTL/Z.
FC_switch_A_1(config)# vsan database
FC_switch_A_1(config-vsan-db)# show vsan
vsan 1 information
         name:VSAN0001  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 30 information
         name:MC1_FCVI_2_30  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 40 information
         name:MC1_STOR_2_40  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 70 information
         name:MC2_FCVI_2_70  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 80 information
         name:MC2_STOR_2_80  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan

FC_switch_A_1(config-vsan-db)# vsan 1 suspend
FC_switch_A_1(config-vsan-db)# vsan 30 suspend
FC_switch_A_1(config-vsan-db)# vsan 40 suspend
FC_switch_A_1(config-vsan-db)# vsan 70 suspend
FC_switch_A_1(config-vsan-db)# vsan 80 suspend
FC_switch_A_1(config-vsan-db)# end
FC_switch_A_1#
FC_switch_A_1# show vsan
vsan 1 information
         name:VSAN0001  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 30 information
         name:MC1_FCVI_2_30  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 40 information
         name:MC1_STOR_2_40  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 70 information
         name:MC2_FCVI_2_70  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 80 information
         name:MC2_STOR_2_80  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan
----


. 在交換器上安裝所需的韌體：
+
"*安裝所有系統bootflash:_systemfile_name__ kickstart bootflash:_kickstartfile_name__*

+
以下範例顯示在FC_switch_a_1上發出的命令：

+
[listing]
----
FC_switch_A_1# install all system bootflash:m9200-s2ek9-mz.5.2.1.bin kickstart bootflash:m9200-s2ek9-kickstart-mz.5.2.1.bin
Enter Yes to confirm the installation.
----
. 檢查每個交換器上的韌體版本、確定已安裝正確版本：
+
’*顯示版本*

. 啟用此網路中兩個交換器上的所有VSAN。
+
請使用下列程序來啟用VSAN：

+
.. 開啟組態終端機：
+
’*組態t*

.. 輸入：「* vSAN database*」
.. 檢查VSAN的狀態：
+
「* show vSAN*」

+
VSAN必須暫停。

.. 啟動VSAN：
+
「*沒有vSAN _vSAN-num_ suspend*」

+
*範例：*「無vSAN 10暫停」

.. 再次檢查VSAN的狀態：
+
「* show vSAN*」

+
所有VSAN都必須處於作用中狀態。

.. 結束組態終端機：
+
《*結束*》

.. 儲存組態：
+
‘*複製執行組態啟動組態*’

+
以下範例顯示FC_switch_a_1的輸出：

+
[listing]
----
FC_switch_A_1# config t
Enter configuration commands, one per line.  End with CNTL/Z.
FC_switch_A_1(config)# vsan database
FC_switch_A_1(config-vsan-db)# show vsan
vsan 1 information
         name:VSAN0001  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 30 information
         name:MC1_FCVI_2_30  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 40 information
         name:MC1_STOR_2_40  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 70 information
         name:MC2_FCVI_2_70  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 80 information
         name:MC2_STOR_2_80  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan

FC_switch_A_1(config-vsan-db)# no vsan 1 suspend
FC_switch_A_1(config-vsan-db)# no vsan 30 suspend
FC_switch_A_1(config-vsan-db)# no vsan 40 suspend
FC_switch_A_1(config-vsan-db)# no vsan 70 suspend
FC_switch_A_1(config-vsan-db)# no vsan 80 suspend
FC_switch_A_1(config-vsan-db)#
FC_switch_A_1(config-vsan-db)# show vsan
vsan 1 information
         name:VSAN0001  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 30 information
         name:MC1_FCVI_2_30  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 40 information
         name:MC1_STOR_2_40  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 70 information
         name:MC2_FCVI_2_70  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 80 information
         name:MC2_STOR_2_80  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan

FC_switch_A_1(config-vsan-db)# end
FC_switch_A_1#
----


. 驗證MetroCluster 下列項目中的功能：ONTAP
+
.. 檢查系統是否具有多路徑：
+
‘*節點執行節點_norme-name_ sysconfig -A*’

.. 檢查兩個叢集上的任何健全狀況警示：
+
系統健全狀況警示顯示*

.. 確認MetroCluster 執行功能組態、並確認操作模式正常：
+
《*》*《*》MetroCluster

.. 執行功能檢查：MetroCluster
+
《* MetroCluster 》*《*執行檢查*》

.. 顯示MetroCluster 檢查結果：
+
《* MetroCluster 》*《*》《*》《*》《*》

.. 檢查交換器上是否有任何健全狀況警示（如果有）：
+
「*儲存交換器show *」

.. 執行Config Advisor
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"]

.. 執行Config Advisor 完功能後、請檢閱工具的輸出結果、並依照輸出中的建議來解決發現的任何問題。


. 對第二個交換器網路重複此程序。

