---
permalink: maintain/task_upgrade_rcf_files_on_cisco_ip_switches_with_cleanupfiles.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches, cleanupfiles, cisco 
summary: 您可能需要升級Cisco IP交換器上的RCF檔案。例如ONTAP 、進行升級時、或是交換器韌體升級時、都需要新的RCF檔案。 
---
= 使用高效能檔案升級Cisco IP交換器上的RCF檔案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要升級 Cisco IP 交換器上的參考組態檔案 （RCF）。例如，ONTAP 升級或交換器韌體升級都需要新的 RCF。

.關於這項工作
* 從RcfFileGenerator1.4a版開始、Cisco IP交換器上有一個新選項可以變更（升級、降級或更換）交換器組態、而不需要執行「寫入清除」。
* link:enable-console-logging-before-maintenance.html["啟用主控台記錄"] 在執行此工作之前。


* Cisco 9336C-FX2 交換器有兩種不同的交換器儲存類型、在 RCF 中命名不同。請使用下表判斷您的組態適用的正確 Cisco 9336C-FX2 儲存類型：
+
[cols="3*"]
|===
| 如果您要連線下列儲存設備 ... | 選擇 Cisco 9336C-FX2 儲存類型 ... | RCF 橫幅/MOTD 範例 


 a| 
** 直接連接的 SAS 機櫃
** 直接連接的 NVMe 磁碟櫃
** 連接至專用儲存交換器的 NVMe 磁碟櫃

 a| 
9336C-FX2 –僅限直接儲存
 a| 
`* Switch    : NX9336C (direct storage, L2 Networks, direct ISL)`



 a| 
** 直接連接的 SAS 機櫃
** 連接至 MetroCluster IP 交換器的 NVMe 機櫃



NOTE: 至少需要一個連接乙太網路的 NVMe 機櫃
 a| 
9336C-FX2 – SAS 與乙太網路儲存設備
 a| 
`* Switch    : NX9336C (SAS and Ethernet storage, L2 Networks, direct ISL)`

|===


.開始之前
如果您的組態符合下列需求、可以使用此方法：

* 套用標準RCF組態。
* The https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"]必須能夠建立與所應用的相同的 RCF，具有相同的版本和組態（平台、VLAN）。
* 所應用的 RCF 不是由 NetApp 為特殊組態所提供的。
* RCF 在套用之前未經任何變更。
* 在套用目前 RCF 之前，已依照步驟將交換器重設為出廠預設值。
* 套用RCF之後、不會變更交換器（連接埠）組態。
+
如果您不符合這些要求，則無法使用產生 RCF 時建立的 CleanUpFiles。但是，您可以運用函數建立通用 CleanUpFiles——使用此方法進行的清理工作源自 `show running-config`的輸出，並且是最佳實務做法。

+

NOTE: 您必須依照下列順序更新交換器：switch_a_1、Switch_B_1、Switch_a_2、Switch_B_2。或者、您也可以同時更新交換器Switch_a_1和Switch_B_1、然後再更新Switch_a_2和Switch_B_2。



.步驟
. link:../install-ip/switch-move-cluster-lifs.html["移動叢集 LIF"]在開始升級之前。
. 確定目前 RCF 版本，以及正在使用的連接埠和 VLAN： `IP_switch_A_1# show banner motd`
+

NOTE: 您需要從所有四個交換器取得此資訊、並填寫下列資訊表。

+
[listing]
----
* NetApp Reference Configuration File (RCF)
*
* Switch : NX9336C (SAS storage, L2 Networks, direct ISL)
* Filename : NX9336_v1.81_Switch-A1.txt
* Date : Generator version: v1.3c_2022-02-24_001, file creation time: 2021-05-11, 18:20:50
*
* Platforms : MetroCluster 1 : FAS8300, AFF-A400, FAS8700
*              MetroCluster 2 : AFF-A320, FAS9000, AFF-A700, AFF-A800
* Port Usage:
* Ports 1- 2: Intra-Cluster Node Ports, Cluster: MetroCluster 1, VLAN 111
* Ports 3- 4: Intra-Cluster Node Ports, Cluster: MetroCluster 2, VLAN 151
* Ports 5- 6: Ports not used
* Ports 7- 8: Intra-Cluster ISL Ports, local cluster, VLAN 111, 151
* Ports 9-10: MetroCluster 1, Node Ports, VLAN 119
* Ports 11-12: MetroCluster 2, Node Ports, VLAN 159
* Ports 13-14: Ports not used
* Ports 15-20: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 10
* Ports 21-24: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 11, breakout mode 10gx4
* Ports 25-30: Ports not used
* Ports 31-36: Ports not used
*

#
IP_switch_A_1#
----
+
您必須從此輸出中收集下表所示的資訊。

+
|===


| 一般資訊 | MetroCluster | 資料 


| RCF 版本 |  | 1.81 


| 交換器類型 |  | NX9336 


| 網路類型 |  | L2網路、直接ISL 


| 儲存類型 |  | SAS儲存設備 


.2+| 平台 | 1. | 解答400 AFF 


| 2. | FAS9000 
|===
+
|===
| VLAN資訊 | 網路 | 組態MetroCluster | 交換器連接埠 | 站台A | 站台B 


.4+| VLAN本機叢集 .2+| 網路1 | 1. | 1、2 | 111. | 222.22 


| 2. | 3、4. | 151. | 251. 


.2+| 網路2. | 1. | 1、2 | 111. | 222.22 


| 2. | 3、4. | 151. | 251. 


.4+| VLAN MetroCluster 功能 .2+| 網路1 | 1. | 9、10 | 119 | 119 


| 2. | 11、12 | 159. | 159. 


.2+| 網路2. | 1. | 9、10 | 219 | 219 


| 2. | 11、12 | 259 | 259 
|===
. [[Create-RCF-files-and-CleanUpFiles-or-create-generic-CleanUpFiles]] 建立 RCF 檔案和 CleanUpFiles，或為目前組態建立通用 CleanUpFiles。
+
如果您的組態符合先決條件中所述的需求、請選取*選項1*。如果您的組態*不符合先決條件中所列的需求、請選取*選項2*。

+
[role="tabbed-block"]
====
.方案一：建立 RCF 和 CleanUpFiles
--
如果組態符合要求、請使用此程序。

.步驟
.. 使用 RcfFileGenerator 1.4a （或更高版本）建立 RCF，其中包含您在步驟 1 中擷取的資訊。新版本的 RcfFileGenerator 會建立一組額外的 CleanUpFiles，您可以使用這些檔案來回復某些組態，並準備交換器以套用新的 RCF 組態。
.. 比較橫幅 motd 與目前套用的 RCF。平台類型、交換器類型、連接埠和 VLAN 使用情況必須一致。
+

NOTE: 您必須使用與 RCF 版本相同且組態完全相同的 CleanUpFiles。使用任何其他 CleanUpFile 都無法正常運作，且可能需要完全重設交換器。

+

NOTE: RCF 所針對的 ONTAP 版本無關緊要。只有 RCF 版本才重要。

+

NOTE: 即使是同一版本的 RCF，列出的平台數量也可能有所不同。請確保您的平台已列入其中。



--
.選項2：建立一般的高效能檔案
--
如果組態*不符合所有需求、請使用此程序。

.步驟
.. 從每個交換器擷取「show running-config」的輸出。
.. 開啟RcfFileGenerator,然後按一下視窗底部的「Create generic CleanUpFiles」
.. 將您在步驟1中從「One」交換器擷取的輸出複製到上方視窗。您可以移除或保留預設輸出。
.. 按一下「Create CUF Files」（建立CUF檔案）。
.. 將輸出內容從下方視窗複製到文字檔（此檔案為CleanUpFile）。
.. 對組態中的所有交換器重複步驟c、d和e。
+
在此程序結束時、您應該有四個文字檔、每個交換器一個。您可以使用與使用選項1建立的高效能檔案相同的方式來使用這些檔案。



--
====
. [[Create-the-new-RCF-files-for-the-new-configuration]] 為新組態建立「新的」RCF 檔案。建立這些檔案的方式與上一個步驟建立檔案的方式相同，只是需要選擇對應的 ONTAP 和 RCF 版本。
+
完成此步驟後，您應該會得到兩組 RCF 檔案，每組包含十二個檔案。

. 將檔案下載至bootflash。
+
.. 下載您在 <<Create-RCF-files-and-CleanUpFiles-or-create-generic-CleanUpFiles,建立 RCF 和 CleanUpFiles，或為目前組態建立通用 CleanUpFiles>> 中建立的 CleanUpFiles
+

NOTE: 此 CleanUpFile 適用於目前套用的 RCF，而*非*您要升級至的新 RCF。

+
例如：Switch-A1的高效能檔案：「Cleanup_NX9336_v1.81_Switch-a1.txt'

.. 下載您在 <<Create-the-new-RCF-files-for-the-new-configuration,為新組態建立「新的」RCF。>> 中建立的「新」RCF
+
交換器 A1 的範例 RCF： `NX9336_v1.90_Switch-A1.txt`

.. 下載您在 <<Create-the-new-RCF-files-for-the-new-configuration,為新組態建立「新的」RCF。>> 中建立的 CleanUpFiles。此步驟為選用步驟——您日後可使用該檔案來更新交換器組態。它與目前套用的組態相符。
+
例如：Switch-A1的高效能檔案：「Cleanup_NX9336_v1.90_Switch-a1.txt'

+

NOTE: 您必須使用高效能檔案取得正確（相符）的RCF版本。如果您針對不同的RCF版本或不同的組態使用高效能檔案、則可能無法正確清除組態。

+
以下範例將三個檔案複製到bootflash：

+
[listing]
----
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.81_MetroCluster-IP_L2Direct_A400FAS8700_xxx_xxx_xxx_xxx/Cleanup_NX9336_v1.81_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//NX9336_v1.90_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//Cleanup_NX9336_v1.90_Switch-A1.txt bootflash:
----
+

NOTE: 系統會提示您指定虛擬路由和轉送（VRF）。



. 套用高效能檔案或一般高效能檔案。
+
部分組態會還原、而且交換器連接埠會「離線」。

+
.. 確認啟動組態沒有擱置中的變更：「How running-config diff」
+
[listing]
----
IP_switch_A_1# show running-config diff
IP_switch_A_1#
----


. 如果看到系統輸出、請將執行組態儲存至啟動組態：「copy running-config startup-config」
+

NOTE: 系統輸出指出啟動組態和執行中組態不同、且處於擱置狀態。如果您未儲存擱置中的變更、則無法使用交換器的重新載入來回復。

+
.. 套用高效能檔案：
+
[listing]
----

IP_switch_A_1# copy bootflash:Cleanup_NX9336_v1.81_Switch-A1.txt running-config

IP_switch_A_1#
----
+

NOTE: 指令碼可能需要一段時間才能返回交換器提示。不需要輸出。



. 檢視執行中的組態、確認組態已清除：「How running-config」
+
目前的組態應顯示：

+
** 未設定類別對應和IP存取清單
** 未設定原則對應
** 未設定任何服務原則
** 未設定連接埠設定檔
** 所有乙太網路介面（mgmt0除外、它不應顯示任何組態、而且只應設定VLAN 1）。
+
如果發現上述任何一項已設定，則可能無法套用新的 RCF 組態。但是，您可以透過重新載入交換器（ *但不*將執行中的組態儲存到啟動組態）來回復至先前的組態。交換器將以先前的組態啟動。



. 套用 RCF 並驗證連接埠是否線上。
+
.. 套用 RCF。
+
[listing]
----
IP_switch_A_1# copy bootflash:NX9336_v1.90-X2_Switch-A1.txt running-config
----
+

NOTE: 套用組態時會出現一些警告訊息。通常不需要錯誤訊息。不過、如果您使用 SSH 登入、可能會收到下列錯誤： `Error: Can't disable/re-enable ssh:Current user is logged in through ssh`

.. 套用組態之後、請使用MetroCluster 下列命令之一「show interface brief」、「show cup neighbor」或「show LLDP鄰近設備」來確認叢集和列舉的各個連接埠是否已上線
+

NOTE: 如果您變更本機叢集的VLAN、並在站台升級第一台交換器、則叢集健全狀況監控可能不會將狀態報告為「健全」、因為舊組態和新組態的VLAN不相符。更新第二個交換器之後、狀態應恢復正常。

+
如果組態未正確套用、或您不想保留組態、您可以重新載入交換器*而不將執行中的組態儲存為啟動組態、以回復到先前的組態。交換器會顯示先前的組態。



. 儲存組態並重新載入交換器。
+
[listing]
----
IP_switch_A_1# copy running-config startup-config

IP_switch_A_1# reload
----
. 修改所有叢集 LIF 以啟用自動還原：
+
.. 重新啟用自動還原：
+
`network interface modify -vserver Cluster -lif * -auto-revert true`

+
[listing]
----
cluster_A::*> network interface modify -vserver Cluster -lif * -auto-revert true

Warning: Changes to a cluster LIF can affect the health of the Cluster. Are you
         sure you want to continue? {y|n}: y
4 entries were modified.

cluster_A::*>
----
.. 將所有目前不在原始連接埠上的叢集 LIF 恢復到其原始連接埠：
+
`network interface revert -vserver Cluster -lif *`

+
請稍等幾分鐘，讓 LIF 回復其主連接埠：

.. 確認所有 LIF 都位於其主連接埠：
+
[listing]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      192.168.204.88/18  node_A_1      e4a     true
            node_A_1_clus2 up/up      192.168.204.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      192.168.204.96/18  node_A_2      e4a     true
            node_A_2_clus2 up/up      192.168.204.97/18  node_A_2      e4b     true
4 entries were displayed.
----
.. 驗證 MetroCluster 節點狀態：
+
「不一樣的秀」MetroCluster

+
[listing]
----
cluster_A::*> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1           configured     enabled   normal
              node_A_2           configured     enabled   normal
      cluster_B
              node_B_1           configured     enabled   normal
              node_B_2           configured     enabled   normal
4 entries were displayed.

cluster_A::*>
----



