---
permalink: maintain/task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, replace, shelf, nondisruptively, stretch, configuration 
summary: 您可以在不中斷擴充MetroCluster 功能的情況下更換磁碟櫃、使用裝滿磁碟櫃或磁碟櫃機箱、並從您要移除的磁碟櫃傳輸元件。 
---
= 在延伸MetroCluster 的架構中、以不中斷營運的方式更換機櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在不中斷擴充MetroCluster 功能的情況下更換磁碟櫃、使用裝滿磁碟櫃或磁碟櫃機箱、並從您要移除的磁碟櫃傳輸元件。

您要安裝的磁碟櫃模型必須符合中指定的儲存系統需求 link:https://hwu.netapp.com["Hardware Universe"^]、包括支援的機櫃機型、支援的磁碟機類型、堆疊中的磁碟櫃數量上限、以及支援ONTAP 的版本。

.步驟
. 請妥善接地。
. 識別迴圈中所有有磁碟的集合體和磁碟區、其中包含您要更換的磁碟櫃、並記下受影響的叢名稱。
+
任一節點都可能包含受影響機櫃和主機集合體或主機磁碟區迴圈中的磁碟。

. 根據您規劃的替換案例、選擇下列兩個選項之一。
+
** 如果您要更換完整的磁碟櫃、包括機櫃機箱、磁碟和I/O模組（IOM）、請採取下表所述的對應行動：
+
|===


| 案例 | 行動 


 a| 
受影響的叢有較少的磁碟來自受影響的磁碟櫃。
 a| 
使用另一個機櫃的備援磁碟、逐一更換受影響機櫃上的磁碟。


NOTE: 您可以在完成磁碟更換之後、將叢連線至離線狀態。



 a| 
受影響的叢包含的磁碟數量大於受影響的磁碟櫃。
 a| 
將叢移離線、然後刪除叢。



 a| 
受影響的叢有受影響磁碟櫃中的任何磁碟。
 a| 
將叢移離線、但不要刪除它。

|===
** 如果您只更換磁碟櫃機箱、而沒有更換其他元件、請執行下列步驟：
+
... 將受影響的叢體從主控的控制器離線：
+
Aggregate offline

... 驗證叢體是否離線：
+
「Aggregate Status -r」





. 識別受影響磁碟櫃迴圈所連接的控制器SAS連接埠、並停用兩個站台控制器上的SAS連接埠：
+
「torage port disable-node_node_name_-port _SAs_port_」

+
受影響的機櫃迴圈會連接至兩個站台。

. 等待ONTAP 看到磁碟遺失。
+
.. 確認磁碟遺失：
+
「syssconfig -A」或「sysconfig -r」



. 關閉磁碟櫃上的電源開關。
. 從磁碟櫃拔下所有電源線。
. 記錄拔下纜線的連接埠、以便以相同方式連接新的磁碟櫃。
. 拔下並拔下將磁碟櫃連接至其他磁碟櫃或儲存系統的纜線。
. 從機架中取出磁碟櫃。
+
若要使磁碟櫃更輕、更容易操作、請移除電源供應器和IOM。如果您要安裝磁碟櫃機箱、請同時移除磁碟機或磁碟櫃。否則、請盡量避免移除磁碟機或磁碟機托架、因為過度處理可能導致內部磁碟機損壞。

. 將替換磁碟櫃安裝並固定在支撐托架和機架上。
. 如果您安裝磁碟櫃機箱、請重新安裝電源供應器和IOM。
. 將所有纜線連接至更換的磁碟櫃連接埠、重新設定磁碟櫃堆疊、完全符合您移除的磁碟櫃上所設定的配置。
. 開啟更換磁碟櫃的電源、並等待磁碟機加速運轉。
. 將磁碟櫃ID變更為從0到98的唯一ID。
. 啟用您先前停用的任何SAS連接埠。
+
.. 等待ONTAP 看到磁碟已插入、
.. 確認磁碟已插入：
+
「syssconfig -A」或「sysconfig -r」



. 如果要更換完整的磁碟櫃（磁碟櫃機箱、磁碟、IOM）、請執行下列步驟：
+

NOTE: 如果您只要更換磁碟櫃機箱、而不更換其他元件、請移至步驟19。

+
.. 確定是否已啟用磁碟自動指派（開啟）。
+
"torage disk option modify -autodassign"

+
磁碟指派會自動進行。

.. 如果未啟用磁碟自動指派、請手動指派磁碟擁有權。


. 將叢體移回線上：
+
"Aggregate online _plex name_"

. 重新建立透過鏡射集合體而刪除的任何叢體。
. 開始重新同步時、請監控叢：
+
「Aggregate Status -r < Aggregate name>'

. 驗證儲存系統是否如預期運作：
+
「系統健全狀況警示顯示」


