---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: 您可能需要在MetroCluster 一個不知如何的IP交換器上升級RCF檔案。例如ONTAP 、進行升級時、或是交換器韌體升級時、都需要新的RCF檔案。 
---
= 升級MetroCluster 不只是在靜態IP交換器上的RCF檔案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要在MetroCluster 一個不知如何的IP交換器上升級RCF檔案。例如ONTAP 、進行升級時、或是交換器韌體升級時、都需要新的RCF檔案。



== 確認RCF檔案受到支援

如果您要變更ONTAP 交換器上執行的更新版本、您應該確定該版本支援RCF檔案。如果您使用RCF產生器、將會為您產生正確的RCF檔案。

.步驟
. 使用交換器的下列命令來驗證RCF檔案的版本：
+
[cols="30,70"]
|===


| 從這個交換器... | 發出此命令... 


 a| 
Broadcom交換器
 a| 
「（ip_switch_a_1）# show clipbid'



 a| 
Cisco交換器
 a| 
「ip_switch_a_1# show banner motd」

|===
+
對於任一交換器、請在輸出中找出指示RCF檔案版本的行。例如、下列輸出來自Cisco交換器、表示RCF檔案版本為「'v1.80」。

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. 若要檢查特定ONTAP 的支援版本、交換器及平台的檔案、請使用RcfFileGenerator.如果您可以針對您的組態或您要升級至的組態產生RCF檔案、則會受到支援。
. 若要驗證交換器韌體是否受支援、請參閱下列內容：
+
** https://hwu.netapp.com["Hardware Universe"]
** https://mysupport.netapp.com/NOW/products/interoperability["NetApp互通性"]






== 升級RCF檔案

如果您要安裝新的交換器韌體、則必須先安裝交換器韌體、才能升級RCF檔案。

.關於這項工作
此程序會中斷升級RCF檔案的交換器流量。一旦套用新的RCF檔案、流量就會恢復。

.步驟
. 驗證組態的健全狀況。
+
.. 驗證MetroCluster 這些元件是否正常運作：
+
《不一樣的跑程》MetroCluster

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
此作業會在背景執行。

+
.. 完成「畫面檢查」作業後MetroCluster 、請執行「MetroCluster 畫面檢查」以檢視結果。
+
大約五分鐘後、會顯示下列結果：

+
[listing]
----
-----------
::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
.. 檢查執行MetroCluster 中的檢查作業狀態：
+
《不穩定作業歷史》顯示-job-id 38 MetroCluster

.. 確認沒有健全狀況警示：
+
「系統健全狀況警示顯示」



. 準備IP交換器以應用新的RCF檔案。
+
請依照交換器廠商的步驟進行：

+
** link:../install-ip/task_switch_config_broadcom.html["將Broadcom IP交換器重設為原廠預設值"]
** link:../install-ip/task_switch_config_cisco.html["將Cisco IP交換器重設為原廠預設值"]


. 視交換器廠商而定、下載並安裝IP RCF檔案。
+

NOTE: 請依下列順序更新交換器：switch_a_1、switch_b_1、Switch_a_2、Switch_B_2

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["下載並安裝Broadcom IP RCF檔案"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["下載並安裝Cisco IP RCF檔案"]
+

NOTE: 如果您有L2共用或L3網路組態、可能需要調整中繼/客戶交換器上的ISL連接埠。switchport模式可能會從「存取」模式變更為「主幹」模式。只有在交換器A_1和B_1之間的網路連線完全正常且網路正常時、才繼續升級第二個交換器配對（A_2、B_2）。




