---
permalink: maintain/task_replace_a_sle_fc_to_sas_bridge.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, replace, single, fc, sas, bridge 
summary: 您可以不中斷地以相同的橋接器或新的模型橋接器取代橋接器。 
---
= 更換單一FC對SAS橋接器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以不中斷地以相同的橋接器或新的模型橋接器取代橋接器。

您需要管理員密碼、才能存取FTP或scp伺服器。

此程序不中斷營運、約需60分鐘完成。

此程序使用橋接CLI來設定及管理橋接器、並更新橋接器韌體和Atto QuickNAV公用程式、以設定橋接器乙太網路管理1連接埠。如果其他介面符合需求、您可以使用這些介面。

link:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html["使用其他介面來設定及管理光纖橋接器的需求"]

link:task_fb_consolidate_replace_a_pair_of_fibrebridge_6500n_bridges_with_7500n_bridges.html["以7600N或7500N橋接器取代一對FibreBridge 6500N橋接器"]



== 驗證儲存設備連線能力

在更換橋接器之前、您應該先確認橋接器和儲存設備的連線能力。熟悉命令輸出之後、即可在進行組態變更後、確認連線能力。

您可以在MetroCluster 進行維護的站台上、從執行此功能的任何一個控制器模組的管理提示字元發出這些命令。

.步驟
. 在MetroCluster 任一個介紹節點上輸入下列命令、以確認與磁碟的連線：
+
執行本機sysconfig -v

+
輸出顯示連接至控制器上啟動器連接埠的磁碟、並識別連接至FC對SAS橋接器的磁碟櫃：

+
[listing]
----

node_A_1> run local sysconfig -v
NetApp Release 9.3.2X18: Sun Dec 13 01:23:24 PST 2017
System ID: 4068741258 (node_A_1); partner ID: 4068741260 (node_B_1)
System Serial Number: 940001025471 (node_A_1)
System Rev: 70
System Storage Configuration: Multi-Path HA**<=== Configuration should be multi-path HA**
.
.
.
slot 0: FC Host Adapter 0g (QLogic 8324 rev. 2, N-port, <UP>)**<=== Initiator port**
		Firmware rev:      7.5.0
		Flash rev:         0.0.0
		Host Port Id:      0x60130
		FC Node Name:      5:00a:098201:bae312
		FC Port Name:      5:00a:098201:bae312
		SFP Vendor:        UTILITIES CORP.
		SFP Part Number:   FTLF8529P3BCVAN1
		SFP Serial Number: URQ0Q9R
		SFP Capabilities:  4, 8 or 16 Gbit
		Link Data Rate:    16 Gbit
		Switch Port:       brcd6505-fcs40:1
  **<List of disks visible to port\>**
		 ID     Vendor   Model            FW    Size
		brcd6505-fcs29:12.126L1527     : NETAPP   X302_HJUPI01TSSM NA04 847.5GB (1953525168 512B/sect)
		brcd6505-fcs29:12.126L1528     : NETAPP   X302_HJUPI01TSSA NA02 847.5GB (1953525168 512B/sect)
		.
		.
		.
		**<List of FC-to-SAS bridges visible to port\>**
		FC-to-SAS Bridge:
		brcd6505-fcs40:12.126L0        : ATTO     FibreBridge6500N 1.61  FB6500N102980
		brcd6505-fcs42:13.126L0        : ATTO     FibreBridge6500N 1.61  FB6500N102980
		brcd6505-fcs42:6.126L0         : ATTO     FibreBridge6500N 1.61  FB6500N101167
		brcd6505-fcs42:7.126L0         : ATTO     FibreBridge6500N 1.61  FB6500N102974
		.
		.
		.
  **<List of storage shelves visible to port\>**
		brcd6505-fcs40:12.shelf6: DS4243  Firmware rev. IOM3 A: 0200  IOM3 B: 0200
		brcd6505-fcs40:12.shelf8: DS4243  Firmware rev. IOM3 A: 0200  IOM3 B: 0200
		.
		.
		.
----




== 以相同機型的替換橋接器熱交換橋接器

您可以將故障的橋接器熱抽換為同一機型的另一橋接器。

如果您要使用橋接器的頻內管理、而非IP管理、則可跳過設定乙太網路連接埠和IP設定的步驟、如相關步驟所述。


NOTE: 從ONTAP 功能組別9.8開始、「最小橋接器」命令會改為「系統橋接器」。以下步驟顯示了「shorage bridge」命令、但ONTAP 如果您執行的是更新版本的版本、最好使用「系統橋接器」命令。

.步驟
. 如果可以存取舊橋接器、您可以擷取組態資訊。
+
[cols="35,65"]
|===


| 如果... | 然後... 


 a| 
*您使用的是IP管理*
 a| 
使用Telnet連線連線到舊橋接器、然後複製橋接器組態的輸出。



 a| 
*您正在使用頻內管理*
 a| 
使用CLI以下列命令擷取組態資訊：ONTAP

「torage bridge run－CLI -name _bridge-name_－command "info"（torage bridge run－CLI名稱_網橋名稱_－命令"info"）」

「torage bridge run－CLI -name _bridge-name_－command "sasportlist"（torage bridge run－CLI名稱_橋接名稱_－命令"sasportlist"）」

|===
+
.. 輸入命令：
+
「torage bridge run－CLI -name bride_a1 -command "info"（英文）

+
[listing]
----
info

Device Status         = Good
Unsaved Changes       = None
Device                = "FibreBridge 7500N"
Serial Number         = FB7500N100000
Device Version        = 3.10
Board Revision        = 7
Build Number          = 007A
Build Type            = Release
Build Date            = "Aug 20 2019" 11:01:24
Flash Revision        = 0.02
Firmware Version      = 3.10
BCE Version (FPGA 1)  = 15
BAU Version (FPGA 2)  = 33
User-defined name     = "bridgeA1"
World Wide Name       = 20 00 00 10 86 A1 C7 00
MB of RAM Installed   = 512
FC1 Node Name         = 20 00 00 10 86 A1 C7 00
FC1 Port Name         = 21 00 00 10 86 A1 C7 00
FC1 Data Rate         = 16Gb
FC1 Connection Mode   = ptp
FC1 FW Revision       = 11.4.337.0
FC2 Node Name         = 20 00 00 10 86 A1 C7 00
FC2 Port Name         = 22 00 00 10 86 A1 C7 00
FC2 Data Rate         = 16Gb
FC2 Connection Mode   = ptp
FC2 FW Revision       = 11.4.337.0
SAS FW Revision       = 3.09.52
MP1 IP Address        = 10.10.10.10
MP1 IP Subnet Mask    = 255.255.255.0
MP1 IP Gateway        = 10.10.10.1
MP1 IP DHCP           = disabled
MP1 MAC Address       = 00-10-86-A1-C7-00
MP2 IP Address        = 0.0.0.0 (disabled)
MP2 IP Subnet Mask    = 0.0.0.0
MP2 IP Gateway        = 0.0.0.0
MP2 IP DHCP           = enabled
MP2 MAC Address       = 00-10-86-A1-C7-01
SNMP                  = enabled
SNMP Community String = public
PS A Status           = Up
PS B Status           = Up
Active Configuration  = NetApp

Ready.
----
.. 輸入命令：
+
「torage bridge run－CLI -name bride_a1 -command "sasportlist"」

+
[listing]
----


SASPortList

;Connector      PHY     Link            Speed   SAS Address
;=============================================================
Device  A       1       Up              6Gb     5001086000a1c700
Device  A       2       Up              6Gb     5001086000a1c700
Device  A       3       Up              6Gb     5001086000a1c700
Device  A       4       Up              6Gb     5001086000a1c700
Device  B       1       Disabled        12Gb    5001086000a1c704
Device  B       2       Disabled        12Gb    5001086000a1c704
Device  B       3       Disabled        12Gb    5001086000a1c704
Device  B       4       Disabled        12Gb    5001086000a1c704
Device  C       1       Disabled        12Gb    5001086000a1c708
Device  C       2       Disabled        12Gb    5001086000a1c708
Device  C       3       Disabled        12Gb    5001086000a1c708
Device  C       4       Disabled        12Gb    5001086000a1c708
Device  D       1       Disabled        12Gb    5001086000a1c70c
Device  D       2       Disabled        12Gb    5001086000a1c70c
Device  D       3       Disabled        12Gb    5001086000a1c70c
Device  D       4       Disabled        12Gb    5001086000a1c70c
----


. 如果橋接器採用網路連接MetroCluster 的功能、請停用連接到橋接FC連接埠或連接埠的所有交換器連接埠。
. 從「支援叢集」提示字元中、移除正在進行維護的橋接器、使其不受健全狀況監控：ONTAP
+
.. 移除橋接器：+「移除橋接器名稱_bridge-name_」
.. 查看受監控的橋接器清單、確認移除的橋接器不存在：+「串接橋接器展示」


. 請妥善接地。
. 關閉Atto橋接器。
+
[cols="35,65"]
|===


| 如果您使用的是... | 然後... 


 a| 
光纖橋接器7600N或7500N橋接器
 a| 
拔下連接至橋接器的電源線。



 a| 
光纖橋接器6500N橋接器
 a| 
關閉橋接器的電源開關。

|===
. 拔下連接至舊橋接器的纜線。
+
您應該記下每條纜線所連接的連接埠。

. 從機架中移除舊的橋接器。
. 將新的橋接器安裝到機架中。
. 重新連接電源線、如果設定以IP存取橋接器、則重新連接有遮蔽的乙太網路纜線。
+

IMPORTANT: 此時不得重新連接SAS或FC纜線。

. 將橋接器連接至電源、然後將其開啟。
+
橋接就緒LED可能需要30秒才能亮起、表示橋接器已完成開機自我測試程序。

. 如果設定用於頻內管理、請將纜線從FIBRBridge的RS-232序列連接埠連接至個人電腦上的序列（COM）連接埠。
+
序列連線將用於初始組態、然後透過ONTAP 功能區進行頻內管理、並可使用FC連接埠來監控及管理橋接器。

. 如果設定IP管理、請依照橋接器機型的_Atto FibreBridge安裝與操作手冊_第2.0節中的程序、為每個橋接器設定乙太網路管理1連接埠。
+
在執行ONTAP 版本不超過版本的系統中、頻內管理可透過FC連接埠（而非乙太網路連接埠）存取橋接器。從功能表9.8開始ONTAP 、僅支援頻內管理、且SNMP管理已過時。

+
執行QuickNAV以設定乙太網路管理連接埠時、只會設定以太網路纜線所連接的乙太網路管理連接埠。例如、如果您也想要設定乙太網路管理2連接埠、則需要將乙太網路纜線連接至連接埠2並執行QuickNAV。

. 設定橋接器。
+
如果您從舊橋接器擷取組態資訊、請使用該資訊來設定新橋接器。

+
請務必記下您指定的使用者名稱和密碼。

+
橋接器機型的_Atto FibreBridge安裝與操作手冊_提供最新的可用命令資訊、以及如何使用這些命令。

+

NOTE: 請勿在Atto FibreBridge 7600N或7500N上設定時間同步。Atto FIBreBridge 7600N或7500N的時間同步設定為ONTAP 叢集時間、之後橋接器被人發現。它也會每天定期同步一次。使用的時區為GMT,不可變更。

+
.. 如果設定IP管理、請設定橋接器的IP設定。
+
若要在不使用QuickNAV公用程式的情況下設定IP位址、您需要連線至FibreBridge。

+
如果使用CLI、您必須執行下列命令：

+
「設定IP位址MP1 _IP位址」

+
"et ipsubnetmaskMP1 _subnet-mask_"

+
"et ipgateway MP1 x x x．x．x"

+
停用了MP1

+
「設定etethernetspeed MP1 1000」

.. 設定橋接器名稱。
+
橋接器在MetroCluster 整個支援架構中應各有一個獨特的名稱。

+
每個站台上一個堆疊群組的橋接名稱範例：

+
*** bride_a_1a.
*** bride_a_1b
*** bride_B_1a
*** bride_b_1b.
+
如果使用CLI、您必須執行下列命令：

+
《以太網的方式來處理問題》



.. 如果執行ONTAP 的是S得9.4或更早版本、請在橋接器上啟用SNMP：
+
「已啟用SNMP」

+
在執行ONTAP 版本不超過版本的系統中、頻內管理可透過FC連接埠（而非乙太網路連接埠）存取橋接器。從功能表9.8開始ONTAP 、僅支援頻內管理、且SNMP管理已過時。



. 設定橋接FC連接埠。
+
.. 設定橋接FC連接埠的資料速率/速度。
+
支援的FC資料速率取決於您的機型橋接器。

+
*** 最多支援32、16或8 Gbps的FibreBridge 7600橋接器。
*** 最多支援16、8或4 Gbps的光纖橋接器。
*** 最多支援8、4或2 Gbps的FibreBridge 6500橋接器。
+

NOTE: 您選取的FCDataRate速度會限制為橋接器和橋接連接埠所連接的交換器所支援的最大速度。佈線距離不得超過SFP和其他硬體的限制。

+
如果使用CLI、您必須執行下列命令：

+
「et FCDataRate _port-Number port-spe__」



.. 如果您要設定的是FIBreBridge 7500N或6500N橋接器、請設定連接埠用於PTP的連線模式。
+

NOTE: 設定FIBreBridge 7600N橋接器時、不需要FCConnMode設定。

+
如果使用CLI、您必須執行下列命令：

+
「et FCConnMode _port-number_ PTP」

.. 如果您要設定的是FIBreBridge 7600N或7500N橋接器、則必須設定或停用FC2連接埠。
+
*** 如果您使用第二個連接埠、則必須針對FC2連接埠重複上述子步驟。
*** 如果您不使用第二個連接埠、則必須停用連接埠：
+
「fcportDisable _port-number_」



.. 如果您要設定的是FIBreBridge 7600N或7500N橋接器、請停用未使用的SAS連接埠：
+
"AsportDisable _SAS-port_"（停用_SAS-port_）

+

NOTE: 預設會啟用SAS連接埠A到D。您必須停用未使用的SAS連接埠。如果只使用SAS連接埠A、則必須停用SAS連接埠B、C和D。



. 安全存取橋接器並儲存橋接器的組態。
+
.. 在控制器提示字元中、檢查橋接器的狀態：「torage bridge show」（橋接器顯示）
+
輸出顯示哪個橋接器未受到保護。

.. 檢查不安全的橋接器連接埠狀態：
+
《資訊》

+
輸出會顯示乙太網路連接埠MP1和MP2的狀態。

.. 如果已啟用乙太網路連接埠MP1、請執行下列命令：
+
「設定乙太網路連接埠MP1已停用」

+

NOTE: 如果也啟用乙太網路連接埠MP2、請針對連接埠MP2重複上一個子步驟。

.. 儲存橋接器的組態。
+
您必須執行下列命令：

+
「另存組態」

+
「FirmwareRestart」

+
系統會提示您重新啟動橋接器。



. 更新每個橋接器上的FibreBridge韌體。
+
如果新橋接器的類型與合作夥伴橋接器的類型相同、請升級至與合作夥伴橋接器相同的韌體。如果新橋接器與合作夥伴橋接器的類型不同、請升級至橋接器和ONTAP 版本的更新韌體。請參閱「_ESIFATE_ MetroCluster 」中的「更新連接到光纖橋接器上的韌體」一節。

. [[step17-elende-Newbrida]將SAS和FC纜線重新連接至新橋接器上的相同連接埠。
+
如果新的橋接器為光纖橋接器7600N或7500N、您必須更換將橋接器連接至機架堆疊頂端或底部的纜線。因為使用SAS纜線的是光纖橋接器6500N；而使用光纖橋接器7600N和7500N橋接器的這些連線需要使用Mini-SAS纜線。

+

NOTE: 連接連接埠之前、請至少等待10秒鐘。SAS纜線連接器採用鎖定式設計；若方向正確放入SAS連接埠、連接器會卡入定位、而磁碟櫃SAS連接埠LNK LED會亮起綠色。若為磁碟櫃、請插入SAS纜線連接器、拉片朝下（位於連接器底部）。對於控制器、SAS連接埠的方向可能會因平台機型而異、因此SAS纜線連接器的正確方向會有所不同。

. [[step18-verify-each bridge ]確認每個橋接器都能看到橋接器所連接的所有磁碟機和磁碟櫃。
+
[cols="35,65"]
|===


| 如果您使用... | 然後... 


 a| 
Atto ExpressNAV GUI
 a| 
.. 在支援的網頁瀏覽器中、於瀏覽器方塊中輸入橋接器的IP位址。
+
您會被帶到Atto FibreBridge首頁、其中有一個連結。

.. 按一下連結、然後輸入您在設定橋接器時所指定的使用者名稱和密碼。
+
Atto FIBreBridge狀態頁面會出現、左側會顯示功能表。

.. 按一下功能表中的*進階*。
.. 檢視連線的裝置：
+
「astargets」

.. 按一下*提交*。




 a| 
序列連接埠連線
 a| 
檢視連線的裝置：

「astargets」

|===
+
輸出顯示連接橋接器的裝置（磁碟和磁碟櫃）。輸出線會依序編號、以便您快速計算裝置數量。

+

NOTE: 如果輸出開頭出現截短的文字回應、您可以使用Telnet連線到橋接器、然後使用「sastargets」命令檢視所有輸出。

+
下列輸出顯示已連接10個磁碟：

+
[listing]
----
Tgt VendorID ProductID        Type SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK 3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK 3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK 3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK 3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK 3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK 3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK 3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK 3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK 3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK 3QP1FXW600009940VERQ
----
. 確認命令輸出顯示橋接器已連接至堆疊中所有適當的磁碟和磁碟櫃。
+
[cols="35,65"]
|===


| 如果輸出是... | 然後... 


 a| 
正確
 a| 
重複 <<step18-verify-each-bridge,步驟18>> 每個剩餘的橋接器。



 a| 
不正確
 a| 
.. 檢查SAS纜線是否鬆脫、或重複修正SAS纜線 <<step17-reconnect-newbridge,步驟17>>。
.. 重複 <<step18-verify-each-bridge,步驟18>>。


|===
. 如果橋接器採用網路連接MetroCluster 的功能區、請重新啟用您在本程序開始時停用的FC交換器連接埠。
+
這應該是連接到橋接器的連接埠。

. 從兩個控制器模組的系統主控台、確認所有的控制器模組都能透過新的橋接器存取磁碟櫃（也就是系統已連接多重路徑HA的纜線）：
+
執行本機系統管理

+

NOTE: 系統可能需要一分鐘時間才能完成探索。

+
如果輸出未顯示多重路徑HA、您必須修正SAS和FC纜線、因為並非所有的磁碟機都能透過新的橋接器存取。

+
下列輸出指出系統已連接多重路徑HA的纜線：

+
[listing]
----
NetApp Release 8.3.2: Tue Jan 26 01:41:49 PDT 2016
System ID: 1231231231 (node_A_1); partner ID: 4564564564 (node_A_2)
System Serial Number: 700000123123 (node_A_1); partner Serial Number: 700000456456 (node_A_2)
System Rev: B0
System Storage Configuration: Multi-Path HA
System ACP Connectivity: NA
----
+

IMPORTANT: 當系統未以多重路徑HA連線時、重新啟動橋接器可能會導致磁碟機存取中斷、並導致多磁碟嚴重損毀。

. 如果執行ONTAP 的是S得9.4或更早版本、請確認橋接器已設定為使用SNMP。
+
如果您使用的是橋接CLI、請執行下列命令：

+
[listing]
----
get snmp
----
. 從「叢集提示」中、將橋接器新增至健全狀況監控：ONTAP
+
.. 使用適用於ONTAP 您的版本的命令來新增橋接器：
+
[cols="25,75"]
|===


| 版本ONTAP | 命令 


 a| 
9.5及更新版本
 a| 
「torage bridge add -address0.0.00.0.00.-managed by in-band -name _bridge-name_」



 a| 
9.4及更早版本
 a| 
「torage bridge add -address_bridge-ip-address_-name _bridge-name_」

|===
.. 確認橋接器已新增且設定正確：
+
《龍橋秀》

+
由於輪詢時間間隔、可能需要15分鐘才能反映所有資料。如果「狀態」欄中的值為「ok」、則可聯絡及監控此橋接器、並顯示全球名稱（WWN）等其他資訊。ONTAP

+
以下範例顯示已設定FC對SAS橋接器：

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----


. 驗證MetroCluster 下列項目中的功能：ONTAP
+
.. 檢查系統是否具有多路徑：+「節點執行-node-name_ sysconfig -A」
.. 檢查兩個叢集上是否有任何健全狀況警示：+「系統健全狀況警示顯示」
.. 確認MetroCluster 此功能的組態、並確認操作模式正常：+「MetroCluster show」
.. 執行MetroCluster 功能不全：+ MetroCluster 「功能不全」
.. 顯示MetroCluster 不實檢查的結果：+ MetroCluster 「不實檢查顯示」
.. 檢查交換器上是否有任何健全狀況警示（如果有）：+「切換顯示」
.. 執行Config Advisor
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]

.. 執行Config Advisor 完功能後、請檢閱工具的輸出結果、並依照輸出中的建議來解決發現的任何問題。




link:concept_in_band_management_of_the_fc_to_sas_bridges.html["FC至SAS橋接器的頻內管理"]



== 以7600N橋接器熱交換使用FibreBridge 7500N

您可以使用7600N橋接器熱抽換到光纖橋接器7500N。

如果您要使用橋接器的頻內管理、而非IP管理、則可跳過設定乙太網路連接埠和IP設定的步驟、如相關步驟所述。


NOTE: 從ONTAP 功能組別9.8開始、「最小橋接器」命令會改為「系統橋接器」。以下步驟顯示了「shorage bridge」命令、但ONTAP 如果您執行的是更新版本的版本、最好使用「系統橋接器」命令。

.步驟
. 如果橋接器採用網路連接MetroCluster 的功能、請停用連接到橋接FC連接埠或連接埠的所有交換器連接埠。
. 從「支援叢集」提示字元中、移除正在進行維護的橋接器、使其不受健全狀況監控：ONTAP
+
.. 移除橋接器：+「移除橋接器名稱_bridge-name_」
.. 查看受監控的橋接器清單、確認移除的橋接器不存在：+「串接橋接器展示」


. 請妥善接地。
. 拔下連接至橋接器的電源線、以關閉橋接器電源。
. 拔下連接至舊橋接器的纜線。
+
您應該記下每條纜線所連接的連接埠。

. 從機架中移除舊的橋接器。
. 將新的橋接器安裝到機架中。
. 重新連接電源線和有遮蔽的乙太網路纜線。
+

IMPORTANT: 此時不得重新連接SAS或FC纜線。

. 將橋接器連接至電源、然後將其開啟。
+
橋接就緒LED可能需要30秒才能亮起、表示橋接器已完成開機自我測試程序。

. 如果設定用於頻內管理、請將纜線從FIBRBridge的RS-232序列連接埠連接至個人電腦上的序列（COM）連接埠。
+
序列連線將用於初始組態、然後透過ONTAP 功能區進行頻內管理、並可使用FC連接埠來監控及管理橋接器。

. 如果設定用於頻內管理、請將纜線從FIBRBridge的RS-232序列連接埠連接至個人電腦上的序列（COM）連接埠。
+
序列連線將用於初始組態、然後透過ONTAP 功能區進行頻內管理、並可使用FC連接埠來監控及管理橋接器。

. 如果設定IP管理、請依照橋接器機型的_Atto FibreBridge安裝與操作手冊_第2.0節中的程序、為每個橋接器設定乙太網路管理1連接埠。
+
在執行ONTAP 版本不超過版本的系統中、頻內管理可透過FC連接埠（而非乙太網路連接埠）存取橋接器。從功能表9.8開始ONTAP 、僅支援頻內管理、且SNMP管理已過時。

+
執行QuickNAV以設定乙太網路管理連接埠時、只會設定以太網路纜線所連接的乙太網路管理連接埠。例如、如果您也想要設定乙太網路管理2連接埠、則需要將乙太網路纜線連接至連接埠2並執行QuickNAV。

. 設定橋接器。
+
請務必記下您指定的使用者名稱和密碼。

+
橋接器機型的_Atto FibreBridge安裝與操作手冊_提供最新的可用命令資訊、以及如何使用這些命令。

+

NOTE: 請勿在FibreBridge 7600N上設定時間同步。連接橋ONTAP 接器發現後、將連接器7600N的時間同步設為叢集時間。它也會每天定期同步一次。使用的時區為GMT,不可變更。

+
.. 如果設定IP管理、請設定橋接器的IP設定。
+
若要在不使用QuickNAV公用程式的情況下設定IP位址、您需要連線至FibreBridge。

+
如果使用CLI、您必須執行下列命令：

+
「et ipaddressMP1 _ip-address_」

+
"et ipsubnetmaskMP1 _subnet-mask_"

+
"et ipgateway MP1 x x x．x．x"

+
停用了MP1

+
「設定etethernetspeed MP1 1000」

.. 設定橋接器名稱。
+
橋接器在MetroCluster 整個支援架構中應各有一個獨特的名稱。

+
每個站台上一個堆疊群組的橋接名稱範例：

+
*** bride_a_1a.
*** bride_a_1b
*** bride_B_1a
*** bride_b_1b.
+
如果使用CLI、您必須執行下列命令：

+
《以太網的方式來處理問題》



.. 如果執行ONTAP 的是S得9.4或更早版本、請在橋接器上啟用SNMP：+「設為SNMP啟用」
+
在執行ONTAP 版本不超過版本的系統中、頻內管理可透過FC連接埠（而非乙太網路連接埠）存取橋接器。從功能表9.8開始ONTAP 、僅支援頻內管理、且SNMP管理已過時。



. 設定橋接FC連接埠。
+
.. 設定橋接FC連接埠的資料速率/速度。
+
支援的FC資料速率取決於您的機型橋接器。

+
*** 最多支援32、16或8 Gbps的FibreBridge 7600橋接器。
*** 最多支援16、8或4 Gbps的光纖橋接器。
*** 最多支援8、4或2 Gbps的FibreBridge 6500橋接器。
+

NOTE: 您選取的FCDataRate速度會限制為橋接器與控制器模組或橋接連接埠所連接之交換器的FC連接埠所支援的最大速度。佈線距離不得超過SFP和其他硬體的限制。

+
如果使用CLI、您必須執行下列命令：

+
「et FCDataRate _port-Number port-spe__」



.. 您必須設定或停用FC2連接埠。
+
*** 如果您使用第二個連接埠、則必須針對FC2連接埠重複上述子步驟。
*** 如果您不使用第二個連接埠、則必須停用未使用的連接埠：
+
「fcport停 用連接埠號碼」

+
下列範例顯示停用FC連接埠2：

+
[listing]
----
FCPortDisable 2

Fibre Channel Port 2 has been disabled.
----


.. 停用未使用的SAS連接埠：
+
"AsportDisable _SAS-port_"（停用_SAS-port_）

+

NOTE: 預設會啟用SAS連接埠A到D。您必須停用未使用的SAS連接埠。

+
如果只使用SAS連接埠A、則必須停用SAS連接埠B、C和D。下列範例顯示停用SAS連接埠B同樣地、您必須停用SAS連接埠C和D：

+
[listing]
----
SASPortDisable b

SAS Port B has been disabled.
----


. 安全存取橋接器並儲存橋接器的組態。
+
.. 在控制器提示字元中、檢查橋接器的狀態：
+
《龍橋秀》

+
輸出顯示哪個橋接器未受到保護。

.. 檢查不安全的橋接器連接埠狀態：
+
《資訊》

+
輸出會顯示乙太網路連接埠MP1和MP2的狀態。

.. 如果已啟用乙太網路連接埠MP1、請執行下列命令：
+
「設定乙太網路連接埠MP1已停用」

+

NOTE: 如果也啟用乙太網路連接埠MP2、請針對連接埠MP2重複上一個子步驟。

.. 儲存橋接器的組態。
+
您必須執行下列命令：+

+
「另存組態」

+
「FirmwareRestart」

+
系統會提示您重新啟動橋接器。



. 更新每個橋接器上的FibreBridge韌體。
+
link:task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["在執行ONTAP 版本號為9.4或更新版本的組態上、更新FIBreBridge 7600N或7500N上的韌體"]

. [[step17-rede-cables]將SAS和FC纜線重新連接至新橋接器上的相同連接埠。
+

NOTE: 連接連接埠之前、請至少等待10秒鐘。SAS纜線連接器採用鎖定式設計；若方向正確放入SAS連接埠、連接器會卡入定位、而磁碟櫃SAS連接埠LNK LED會亮起綠色。若為磁碟櫃、請插入SAS纜線連接器、拉片朝下（位於連接器底部）。對於控制器、SAS連接埠的方向可能會因平台機型而異、因此SAS纜線連接器的正確方向會有所不同。

. 確認每個橋接器都能看到橋接器所連接的所有磁碟機和磁碟櫃：
+
「astargets」

+
輸出顯示連接橋接器的裝置（磁碟和磁碟櫃）。輸出線會依序編號、以便您快速計算裝置數量。

+
下列輸出顯示已連接10個磁碟：

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. 確認命令輸出顯示橋接器已連接至堆疊中所有適當的磁碟和磁碟櫃。
+
[cols="25,75"]
|===


| 如果輸出是... | 然後... 


 a| 
正確
 a| 
針對其餘的每個橋接重複上一步。



 a| 
不正確
 a| 
.. 檢查SAS纜線是否鬆脫、或重複修正SAS纜線 <<step17-reconnect-cables,步驟17>>。
.. 重複上一步。


|===
. 如果橋接器採用網路連接MetroCluster 的功能區、請重新啟用您在本程序開始時停用的FC交換器連接埠。
+
這應該是連接到橋接器的連接埠。

. 從兩個控制器模組的系統主控台、確認所有的控制器模組都能透過新的橋接器存取磁碟櫃（也就是系統已連接多重路徑HA的纜線）：
+
執行本機系統管理

+

NOTE: 系統可能需要一分鐘時間才能完成探索。

+
如果輸出未顯示多重路徑HA、您必須修正SAS和FC纜線、因為並非所有的磁碟機都能透過新的橋接器存取。

+
下列輸出指出系統已連接多重路徑HA的纜線：

+
[listing]
----
NetApp Release 8.3.2: Tue Jan 26 01:41:49 PDT 2016
System ID: 1231231231 (node_A_1); partner ID: 4564564564 (node_A_2)
System Serial Number: 700000123123 (node_A_1); partner Serial Number: 700000456456 (node_A_2)
System Rev: B0
System Storage Configuration: Multi-Path HA
System ACP Connectivity: NA
----
+

IMPORTANT: 當系統未以多重路徑HA連線時、重新啟動橋接器可能會導致磁碟機存取中斷、並導致多磁碟嚴重損毀。

. 如果執行ONTAP 的是S得9.4或更早版本、請確認橋接器已設定為使用SNMP。
+
如果您使用的是橋接CLI、請執行下列命令：

+
"Get SNMP（獲取SNMP）"

. 從「叢集提示」中、將橋接器新增至健全狀況監控：ONTAP
+
.. 使用適用於ONTAP 您的版本的命令來新增橋接器：
+
[cols="25,75"]
|===


| 版本ONTAP | 命令 


 a| 
9.5及更新版本
 a| 
「torage bridge add -address0.0.00.0.00.-managed by in-band -name _bridge-name_」



 a| 
9.4及更早版本
 a| 
「torage bridge add -address_bridge-ip-address_-name _bridge-name_」

|===
.. 確認橋接器已新增且設定正確：
+
《龍橋秀》

+
由於輪詢時間間隔、可能需要15分鐘才能反映所有資料。如果「狀態」欄中的值為「ok」、則可聯絡及監控此橋接器、並顯示全球名稱（WWN）等其他資訊。ONTAP

+
以下範例顯示已設定FC對SAS橋接器：

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----


. 驗證MetroCluster 下列項目中的功能：ONTAP
+
.. 檢查系統是否具有多路徑：+「節點執行-node-name_ sysconfig -A」
.. 檢查兩個叢集上是否有任何健全狀況警示：+「系統健全狀況警示顯示」
.. 確認MetroCluster 此功能的組態、並確認操作模式正常：+「MetroCluster show」
.. 執行MetroCluster 功能不全：+ MetroCluster 「功能不全」
.. 顯示MetroCluster 外觀檢查的結果：+
+
《不一樣的表演》MetroCluster

.. 檢查交換器上是否有任何健全狀況警示（如果有）：+「切換顯示」
.. 執行Config Advisor
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]

.. 執行Config Advisor 完功能後、請檢閱工具的輸出結果、並依照輸出中的建議來解決發現的任何問題。




link:concept_in_band_management_of_the_fc_to_sas_bridges.html["FC至SAS橋接器的頻內管理"]



== 使用光纖橋接器7600N或7500N橋接器熱交換光纖橋接器6500N

您可以使用光纖橋接器7600N或7500N橋接器熱抽換至光纖橋接器6500N橋接器、以取代故障橋接器、或是在光纖連接或橋接式MetroCluster 連接的不支援配置中升級橋接器。

.關於這項工作
* 此程序適用於以單一光纖橋接器7600N或7500N橋接器進行熱插拔。
* 當您將光纖橋接器6500N橋接器熱插拔至Fibre Bridge 7600N或7500N橋接器時、您必須在Fibre Bridge 7600N或7500N橋接器上僅使用一個FC連接埠和一個SAS連接埠。
* 如果您要使用橋接器的頻內管理、而非IP管理、則可跳過設定乙太網路連接埠和IP設定的步驟、如相關步驟所述。



IMPORTANT: 如果您在配對中同時熱交換兩個FibreBridge 6500N橋接器、則必須使用 link:task_fb_consolidate_replace_a_pair_of_fibrebridge_6500n_bridges_with_7500n_bridges.html["整合多個儲存堆疊"] 分區指示程序。藉由更換橋接器上的兩個FibreBridge 6500N橋接器、您就能充分利用光纖橋接器7600N或7500N橋接器上的其他連接埠。


NOTE: 從ONTAP 功能組別9.8開始、「最小橋接器」命令會改為「系統橋接器」。以下步驟顯示了「shorage bridge」命令、但ONTAP 如果您執行的是更新版本的版本、最好使用「系統橋接器」命令。

.步驟
. 執行下列其中一項：
+
** 如果故障的橋接器採用網路附加MetroCluster 的功能、請停用連接到橋接FC連接埠的交換器連接埠。
** 如果故障的橋接器採用延伸MetroCluster 的邊架構配置、請使用任一可用的FC連接埠。


. 從「支援叢集」提示字元中、移除正在進行維護的橋接器、使其不受健全狀況監控：ONTAP
+
.. 移除橋接器：
+
「torage bridge remove -name _bridge-name_」

.. 檢視受監控的橋接器清單、確認移除的橋接器不存在：
+
《龍橋秀》



. 請妥善接地。
. 關閉橋接器的電源開關。
. 拔下從磁碟櫃連接至FIBreBridge 6500N橋接連接埠和電源線的纜線。
+
您應該記下每條纜線所連接的連接埠。

. 從機架上移除需要更換的FibreBridge 6500N橋接器。
. 將新的FibreBridge 7600N或7500N橋接器安裝到機架中。
. 重新連接電源線、必要時重新連接有遮蔽的乙太網路纜線。
+

IMPORTANT: 此時請勿重新連接SAS或FC纜線。

. 如果設定用於頻內管理、請將纜線從FIBRBridge的RS-232序列連接埠連接至個人電腦上的序列（COM）連接埠。
+
序列連線將用於初始組態、然後透過ONTAP 功能區進行頻內管理、並可使用FC連接埠來監控及管理橋接器。

. 如果設定IP管理、請使用乙太網路纜線、將每個橋接器上的乙太網路管理1連接埠連接至網路。
+
在執行ONTAP 版本不超過版本的系統中、頻內管理可透過FC連接埠（而非乙太網路連接埠）存取橋接器。從功能表9.8開始ONTAP 、僅支援頻內管理、且SNMP管理已過時。

+
乙太網路管理1連接埠可讓您快速下載橋接韌體（使用Atto ExpressNAV或FTP管理介面）、並擷取核心檔案和擷取記錄。

. 如果設定IP管理、請依照橋接器機型的_Atto FibreBridge安裝與操作手冊_第2.0節中的程序、為每個橋接器設定乙太網路管理1連接埠。
+
在執行ONTAP 版本不超過版本的系統中、頻內管理可透過FC連接埠（而非乙太網路連接埠）存取橋接器。從功能表9.8開始ONTAP 、僅支援頻內管理、且SNMP管理已過時。

+
執行QuickNAV以設定乙太網路管理連接埠時、只會設定以太網路纜線所連接的乙太網路管理連接埠。例如、如果您也想要設定乙太網路管理2連接埠、則需要將乙太網路纜線連接至連接埠2並執行QuickNAV。

. 設定橋接器。
+
如果您從舊橋接器擷取組態資訊、請使用該資訊來設定新橋接器。

+
請務必記下您指定的使用者名稱和密碼。

+
橋接器機型的_Atto FibreBridge安裝與操作手冊_提供最新的可用命令資訊、以及如何使用這些命令。

+

NOTE: 請勿在Atto FibreBridge 7600N或7500N上設定時間同步。Atto FIBreBridge 7600N或7500N的時間同步設定為ONTAP 叢集時間、之後橋接器被人發現。它也會每天定期同步一次。使用的時區為GMT,不可變更。

+
.. 如果設定IP管理、請設定橋接器的IP設定。
+
若要在不使用QuickNAV公用程式的情況下設定IP位址、您需要連線至FibreBridge。

+
如果使用CLI、您必須執行下列命令：

+
「et ipaddressMP1 _ip-address_」

+
"et ipsubnetmaskMP1 _subnet-mask_"

+
"et ipgateway MP1 x x x．x．x"

+
停用了MP1

+
「設定etethernetspeed MP1 1000」

.. 設定橋接器名稱。
+
橋接器在MetroCluster 整個支援架構中應各有一個獨特的名稱。

+
每個站台上一個堆疊群組的橋接名稱範例：

+
*** bride_a_1a.
*** bride_a_1b
*** bride_B_1a
*** bride_b_1b.
+
如果使用CLI、您必須執行下列命令：

+
《以太網的方式來處理問題》



.. 如果執行ONTAP 的是S得9.4或更早版本、請在橋接器上啟用SNMP：+「設為SNMP啟用」
+
在執行ONTAP 版本不超過版本的系統中、頻內管理可透過FC連接埠（而非乙太網路連接埠）存取橋接器。從功能表9.8開始ONTAP 、僅支援頻內管理、且SNMP管理已過時。



. 設定橋接FC連接埠。
+
.. 設定橋接FC連接埠的資料速率/速度。
+
支援的FC資料速率取決於您的機型橋接器。

+
*** 最多支援32、16或8 Gbps的FibreBridge 7600橋接器。
*** 最多支援16、8或4 Gbps的光纖橋接器。
*** 最多支援8、4或2 Gbps的FibreBridge 6500橋接器。
+

NOTE: 您選取的FCDataRate速度會限制為橋接器和橋接連接埠所連接的交換器所支援的最大速度。佈線距離不得超過SFP和其他硬體的限制。

+
如果使用CLI、您必須執行下列命令：

+
「et FCDataRate _port-Number port-spe__」



.. 如果您要設定的是FIBreBridge 7500N或6500N橋接器、請設定連接埠用於PTP的連線模式。
+

NOTE: 設定FIBreBridge 7600N橋接器時、不需要FCConnMode設定。

+
如果使用CLI、您必須執行下列命令：

+
「et FCConnMode _port-number_ PTP」

.. 如果您要設定的是FIBreBridge 7600N或7500N橋接器、則必須設定或停用FC2連接埠。
+
*** 如果您使用第二個連接埠、則必須針對FC2連接埠重複上述子步驟。
*** 如果您不使用第二個連接埠、則必須停用連接埠：
+
「fcportDisable _port-number_」



.. 如果您要設定的是FIBreBridge 7600N或7500N橋接器、請停用未使用的SAS連接埠：
+
"AsportDisable _SAS-port_"（停用_SAS-port_）

+

NOTE: 預設會啟用SAS連接埠A到D。您必須停用未使用的SAS連接埠。如果只使用SAS連接埠A、則必須停用SAS連接埠B、C和D。



. 安全存取橋接器並儲存橋接器的組態。
+
.. 在控制器提示字元中、檢查橋接器的狀態：
+
《龍橋秀》

+
輸出顯示哪個橋接器未受到保護。

.. 檢查不安全的橋接器連接埠狀態：
+
《資訊》

+
輸出會顯示乙太網路連接埠MP1和MP2的狀態。

.. 如果已啟用乙太網路連接埠MP1、請執行下列命令：
+
「設定乙太網路連接埠MP1已停用」

+

NOTE: 如果也啟用乙太網路連接埠MP2、請針對連接埠MP2重複上一個子步驟。

.. 儲存橋接器的組態。
+
您必須執行下列命令：

+
「另存組態」

+
「FirmwareRestart」

+
系統會提示您重新啟動橋接器。



. 開啟FIBreBridge 7600N或7500N橋接器的健全狀況監控。
. 更新每個橋接器上的FibreBridge韌體。
+
如果新橋接器的類型與合作夥伴橋接器的類型相同、請升級至與合作夥伴橋接器相同的韌體。如果新橋接器與合作夥伴橋接器的類型不同、請升級至橋接器和ONTAP 版本的更新韌體。請參閱《_ MetroCluster 資料維護指南_》中的「更新光纖橋接器上的韌體」一節。

. [[step17-recable）]將SAS和FC纜線重新連接至新橋接器上的SAS A和Fibre Channel 1連接埠。
+
SAS連接埠必須連線至與連接到的光纖橋接器6500N相同的機櫃連接埠。

+
FC連接埠必須連接至與Fibre Bridge 6500N橋接器連接的相同交換器或控制器連接埠。

+

NOTE: 請勿將連接器強制插入連接埠。迷你SAS纜線採用鎖定式設計；若方向正確放入SAS連接埠、SAS纜線會卡入定位、而磁碟櫃SAS連接埠LKLED會亮起綠色。對於磁碟櫃、您可以插入SAS纜線連接器、拉片朝下（位於連接器底部）。對於控制器、SAS連接埠的方向可能會因平台機型而異、因此SAS纜線連接器的正確方向會有所不同。

. 驗證橋接器是否能偵測到其所連接的所有磁碟機和磁碟櫃。
+
[cols="25,75"]
|===


| 如果您使用... | 然後... 


 a| 
Atto ExpressNAV GUI
 a| 
.. 在支援的網頁瀏覽器中、於瀏覽器方塊中輸入橋接器的IP位址。
+
您會被帶到Atto FibreBridge首頁、其中有一個連結。

.. 按一下連結、然後輸入您在設定橋接器時所指定的使用者名稱和密碼。
+
Atto FIBreBridge狀態頁面會出現、左側會顯示功能表。

.. 按一下功能表中的*進階*。
.. 輸入下列命令、然後按一下*提交*以查看橋接器可見的磁碟清單：
+
「astargets」





 a| 
序列連接埠連線
 a| 
顯示橋接器可見的磁碟清單：

「astargets」

|===
+
輸出會顯示橋接器所連接的裝置（磁碟和磁碟櫃）。輸出線會依序編號、以便您快速計算裝置數量。例如、下列輸出顯示已連接10個磁碟：

+
[listing]
----

Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
+

NOTE: 如果輸出開頭出現「回應被截短」文字、您可以使用Telnet存取橋接器、然後輸入相同的命令來查看所有輸出。

. 確認命令輸出顯示橋接器已連接至堆疊中所有必要的磁碟和磁碟櫃。
+
[cols="25,75"]
|===


| 如果輸出是... | 然後... 


 a| 
正確
 a| 
針對其餘的每個橋接重複上一步。



 a| 
不正確
 a| 
.. 檢查SAS纜線是否鬆脫、或重複修正SAS纜線 <<step17-recable,步驟17>>。
.. 針對其餘的每個橋接重複上一步。


|===
. 重新啟用連接至橋接器的FC交換器連接埠。
. 確認所有控制器都能透過新的橋接器存取磁碟櫃（系統已連接多重路徑HA的纜線）、位於兩個控制器的系統主控台：
+
執行本機系統管理

+

NOTE: 系統可能需要一分鐘時間才能完成探索。

+
例如、下列輸出顯示系統已連接多重路徑HA的纜線：

+
[listing]
----
NetApp Release 8.3.2: Tue Jan 26 01:23:24 PST 2016
System ID: 1231231231 (node_A_1); partner ID: 4564564564 (node_A_2)
System Serial Number: 700000123123 (node_A_1); partner Serial Number: 700000456456 (node_A_2)
System Rev: B0
System Storage Configuration: Multi-Path HA
System ACP Connectivity: NA
----
+
如果命令輸出指出組態是混合路徑或單路徑HA、您必須修正SAS和FC纜線、因為並非所有的磁碟機都能透過新的橋接器存取。

+

IMPORTANT: 當系統未以多重路徑HA連線時、重新啟動橋接器可能會導致磁碟機存取中斷、並導致多磁碟嚴重損毀。

. 從「叢集提示」中、將橋接器新增至健全狀況監控：ONTAP
+
.. 使用適用於ONTAP 您的版本的命令來新增橋接器：
+
[cols="25,75"]
|===


| 版本ONTAP | 命令 


 a| 
9.5及更新版本
 a| 
「torage bridge add -address0.0.00.0.00.-managed by in-band -name _bridge-name_」



 a| 
9.4及更早版本
 a| 
「torage bridge add -address_bridge-ip-address_-name _bridge-name_」

|===
.. 確認橋接器已新增且設定正確：+「橋接器展示」
+
由於輪詢時間間隔、可能需要15分鐘才能反映所有資料。如果「狀態」欄中的值為「ok」、則可聯絡及監控此橋接器、並顯示全球名稱（WWN）等其他資訊。ONTAP

+
以下範例顯示已設定FC對SAS橋接器：

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----


. 驗證MetroCluster 下列項目中的功能：ONTAP
+
.. 檢查系統是否具有多路徑：
+
「節點執行節點_norme-name_ sysconfig -A」

.. 檢查兩個叢集上是否有任何健全狀況警示：+「系統健全狀況警示顯示」
.. 確認MetroCluster 執行功能組態、並確認操作模式正常：
+
《不看》MetroCluster

.. 執行功能檢查：MetroCluster
+
《不一樣的跑程》MetroCluster

.. 顯示MetroCluster 檢查結果：
+
《不一樣的表演》MetroCluster

.. 檢查交換器上是否有任何健全狀況警示（如果有）：
+
「torage switchshow」

.. 執行Config Advisor
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"^]

.. 執行Config Advisor 完功能後、請檢閱工具的輸出結果、並依照輸出中的建議來解決發現的任何問題。


. 更換零件後、請將故障零件歸還給NetApp、如套件隨附的RMA指示所述。請參閱 link:https://mysupport.netapp.com/site/info/rma["產品退貨安培；更換"] 頁面以取得更多資訊。


link:concept_in_band_management_of_the_fc_to_sas_bridges.html["FC至SAS橋接器的頻內管理"]
