---
permalink: maintain/task_change_speed_of_isl_ports_on_a_cisco_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, speed, isl, ports, cisco, fc, switch 
summary: 您可能需要變更交換器上ISL連接埠的速度、以改善ISL的品質。長距離行駛的ISL可能需要降低速度以改善品質。 
---
= 變更Cisco FC交換器上ISL連接埠的速度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要變更交換器上ISL連接埠的速度、以改善ISL的品質。長距離行駛的ISL可能需要降低速度以改善品質。

.關於這項工作
* 完成兩台交換器上的所有步驟、以確保 ISL 連線。
* link:enable-console-logging-before-maintenance.html["啟用主控台記錄"] 在執行此工作之前。


.步驟
. 停用ISL的ISL連接埠、以變更Fabric中兩個交換器的速度：
+
f_switch_a_1#組態t*

+
輸入組態命令、每行輸入一個。輸入所有組態命令後、以A-Z結束。

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----
. 變更網路中兩台交換器上ISL連接埠的速度：
+
f_switch_a_1#組態t*

+
輸入組態命令、每行輸入一個。輸入所有組態命令後、以A-Z結束。

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# switchport speed 16000
----
+

NOTE: 連接埠的速度為16 = 16、000 Gbps、8 = 8、000 Gbps、4 = 4、000 Gbps。

+
請確定您交換器的這些ISL連接埠已列於_架構附加MetroCluster 的《安裝與組態指南》_。

. 在光纖網路中的兩個交換器上啟用所有ISL連接埠（若未啟用）：
+
f_switch_a_1#組態t*

+
輸入組態命令、每行輸入一個。輸入所有組態命令後、以A-Z結束。

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----
. 驗證是否在兩個交換器之間建立ISL：
+
’*顯示拓撲ISL *

+
[listing]
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----
. 對第二個交換器網路重複此程序。

