---
permalink: maintain/task_add_remove_or_change_isl_ports_nondisruptively.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, add, remove, change, isl, ports, nondisruptively 
summary: 您可能需要新增、移除或變更ISL連接埠。您可以將專用ISL連接埠轉換成共享ISL連接埠、或變更交換器上ISL連接埠的速度。長距離行駛的ISL可能需要較低的速度來改善品質。如果您要新增或升級硬體、可能還需要提高ISL連接埠的速度、才能充分利用系統升級的優勢、並將ISL新增至Cisco IP交換器。 
---
= 在 Cisco IP 交換器上以不中斷營運的方式新增、移除或變更 ISL 連接埠
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要在 Cisco IP 交換器上新增、移除或變更 ISL 連接埠。您可以將專用 ISL 連接埠轉換為共享 ISL 連接埠、或變更 Cisco IP 交換器上 ISL 連接埠的速度。

.關於這項工作
如果您要將專用ISL連接埠轉換成共享ISL連接埠、請確定新的連接埠符合 link:../install-ip/concept_considerations_layer_2.html["共享ISL連接埠的需求"]。

您必須完成兩台交換器上的所有步驟、以確保ISL連線能力。

下列程序假設您要以兩個連接至交換器連接埠17和18的100-GB ISL取代連接至交換器連接埠eth1/24/1的10-GB ISL。


NOTE: 如果您在連接 NS224 機櫃的共享組態中使用 Cisco 9336C-FX2 交換器、變更 ISL 可能需要新的 RCF 檔案。如果您目前和新的 ISL 速度為 40Gbps 和 100Gbps 、則不需要新的 RCF 檔案。所有其他 ISL 速度變更都需要新的 RCF 檔案。例如、將 ISL 速度從 40Gbps 變更為 100Gbps 並不需要新的 RCF 檔案、但將 ISL 速度從 10Gbps 變更為 40Gbps 則需要新的 RCF 檔案。

.開始之前
請參閱的 * 切換開關 * 一節 link:https://hwu.netapp.com/["NetApp Hardware Universe"^] 驗證支援的收發器。

link:enable-console-logging-before-maintenance.html["啟用主控台記錄"] 在執行此工作之前。

.步驟
. 在您要變更的光纖網路中、停用兩個交換器上ISL的ISL連接埠。
+
--

NOTE: 只有當您將目前的ISL連接埠移至不同的連接埠、或ISL的速度正在改變時、才需要停用這些連接埠。如果您要新增的ISL連接埠速度與現有ISL相同、請移至步驟3。

--
+
每行只能輸入一個組態命令、並在輸入所有命令後按Ctrl-Z、如下列範例所示：

+
[listing]
----

switch_A_1# conf t
switch_A_1(config)# int eth1/24/1
switch_A_1(config-if)# shut
switch_A_1(config-if)#
switch_A_1#

switch_B_1# conf t
switch_B_1(config)# int eth1/24/1
switch_B_1(config-if)# shut
switch_B_1(config-if)#
switch_B_1#
----
. 移除現有的纜線和收發器。
. 視需要變更ISL連接埠。
+

NOTE: 如果您在連接 NS224 機櫃的共享組態中使用 Cisco 9336C-FX2 交換器、而您需要升級 RCF 檔案、並將新組態套用至新的 ISL 連接埠、請遵循的步驟 link:task_upgrade_rcf_files_on_mcc_ip_switches.html["升級 MetroCluster IP 交換器上的 RCF 檔案。"]

+
[cols="30,70"]
|===


| 選項 | 步驟 


 a| 
若要變更ISL連接埠的速度...
 a| 
根據新ISL的速度、將其連接至指定的連接埠。您必須確保交換器的這些ISL連接埠列在_EIP MetroCluster 安裝與組態_中。



 a| 
若要新增ISL ...
 a| 
將QFSP插入要新增為ISL連接埠的連接埠。請確定它們列在_ MetroCluster 《IP安裝與組態》_中、並依此連接纜線。

|===
. 從下列命令開始、在光纖中的兩個交換器上啟用所有ISL連接埠（如果未啟用）：
+
「Switch_a_1#」

+
每行只能輸入一個組態命令、並在輸入所有命令後按Ctrl-Z：

+
[listing]
----
switch_A_1# conf t
switch_A_1(config)# int eth1/17
switch_A_1(config-if)# no shut
switch_A_1(config-if)# int eth1/18
switch_A_1(config-if)# no shut
switch_A_1(config-if)#
switch_A_1#
switch_A_1# copy running-config startup-config

switch_B_1# conf t
switch_B_1(config)# int eth1/17
switch_B_1(config-if)# no shut
switch_B_1(config-if)# int eth1/18
switch_B_1(config-if)# no shut
switch_B_1(config-if)#
switch_B_1#
switch_B_1# copy running-config startup-config
----
. 確認 ISL 的 ISL 和連接埠通道是在兩台交換器之間建立的：
+
`switch_A_1# show int brief`

+
您應該會在命令輸出中看到ISL介面、如下列範例所示：

+
[listing]
----
Switch_A_1# show interface brief
--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch #
--------------------------------------------------------------------------------
Eth1/17         1       eth  access down    XCVR not inserted        auto(D) --
Eth1/18         1       eth  access down    XCVR not inserted        auto(D) --

------------------------------------------------------------------------------------------
Port-channel VLAN    Type Mode   Status  Reason                              Speed   Protocol
Interface
------------------------------------------------------------------------------------------
Po10         1       eth  trunk  up      none                                a-100G(D)  lacp
Po11         1       eth  trunk  up      none                                a-100G(D)  lacp
----
. 重複執行Fabric 2的程序。

