---
permalink: maintain/task_fb_hot_add_a_disk_shelf_install_7500n.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, disk, shelf 
summary: 您可以在不降低效能的情況下、隨時熱新增磁碟櫃來增加儲存容量。 
---
= 熱新增磁碟櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在不降低效能的情況下、隨時熱新增磁碟櫃來增加儲存容量。

* 系統必須符合中的所有需求 link:task_fb_hot_add_shelf_prepare_7500n.html["準備熱新增SAS磁碟櫃"]。
* 您的環境必須符合下列其中一種情況、才能熱新增機櫃：
+
** 您有兩個連接至SAS磁碟櫃堆疊的FibreBridge 7500N橋接器。
** 您有一個連接至SAS磁碟櫃堆疊的FIBreBridge 7500N橋接器和一個FIBreBridge 6500N橋接器。
** 您有兩個連接至SAS磁碟櫃堆疊的FibreBridge 6500N橋接器。


* 此程序適用於將磁碟櫃熱新增至堆疊中的最後一個磁碟櫃。
+
這項程序是假設堆疊中的最後一個磁碟櫃是從IOM A連接到橋接器A、從IOM B連接到橋接器B

* 這是不中斷營運的程序。
* 您應該在每個站台熱新增相同數量的磁碟櫃。
* 如果您要熱新增多個磁碟櫃、則必須一次熱新增一個磁碟櫃。
+

NOTE: 每對一對的FIBEBridge 7500N或7600N橋接器最多可支援四個堆疊。




IMPORTANT: 若要熱新增磁碟櫃、您必須在進階模式中執行「儲存磁碟韌體更新」命令、以更新熱新增磁碟櫃上的磁碟機韌體。如果系統中現有磁碟機的韌體版本較舊、執行此命令可能會造成中斷。


IMPORTANT: 如果您將SAS纜線插入錯誤的連接埠、從SAS連接埠拔下纜線時、必須等待至少120秒、才能將纜線插入其他SAS連接埠。如果您無法這麼做、系統將無法辨識纜線是否已移至其他連接埠。

.步驟
. 請妥善接地。
. 從任一控制器的系統主控台驗證磁碟櫃連線能力：
+
"*sysconfig -v*

+
輸出類似於下列內容：

+
** 每個橋接器位於獨立的線路上、並位於每個可見的FC連接埠下方；例如、熱新增磁碟櫃至一組Fibre Bridge 7500N橋接器、會產生下列輸出：
+
[listing]
----
FC-to-SAS Bridge:
cisco_A_1-1:9.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100189
cisco_A_1-2:1.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100162
----
** 每個磁碟櫃位於每個可見的FC連接埠下方的獨立線路上：
+
[listing]
----
Shelf   0: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
Shelf   1: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
----
** 每個磁碟機位於每個可見FC連接埠下方的獨立線路上：
+
[listing]
----
cisco_A_1-1:9.126L1   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
cisco_A_1-1:9.126L2   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
----


. 檢查您的系統是否已從任一控制器的主控台啟用磁碟自動指派：
+
「*儲存磁碟選項」顯示*

+
自動指派原則會顯示在自動指派欄中。

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. 如果您的系統未啟用磁碟自動指派、或是同一個堆疊中的磁碟機同時由兩個控制器擁有、請將磁碟機指派給適當的資源池。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["磁碟與Aggregate管理"]

+
[NOTE]
====
如果您要在兩個控制器之間分割單一磁碟櫃堆疊、則必須先停用磁碟自動指派、才能指派磁碟擁有權；否則、當您指派任何單一磁碟機時、其餘的磁碟機可能會自動指派給同一個控制器和集區。

"storage disk option modify -node-name_-autodassign off"命令會停用磁碟自動指派。

====
+

NOTE: 在磁碟機和磁碟櫃韌體更新之前、不得將磁碟機新增至集合體或磁碟區。

. 使用下載韌體的指示、將磁碟櫃韌體更新至最新版本。
+
您可以從任一控制器的系統主控台執行程序中的命令。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp下載：磁碟櫃韌體"]

. 安裝並連接磁碟櫃：
+
請注意下列考量事項：

+
** 若為光纖橋接器6500N橋接器：
+
連接連接埠之前、請至少等待10秒鐘。SAS纜線連接器採用鎖定式設計；若方向正確放入SAS連接埠、連接器會卡入定位、而磁碟櫃SAS連接埠LKLED會亮起綠色。若為磁碟櫃、請插入SAS纜線連接器、拉片方向向下（位於連接器底部）。

** 若為FibreBridge 7500N橋接器：
+
請勿將連接器強制插入連接埠。迷你SAS纜線採用鎖定式設計；若方向正確放入SAS連接埠、SAS纜線會卡入定位、且磁碟櫃SAS連接埠LKLED會亮起綠色。若為磁碟櫃、請插入SAS纜線連接器、拉片朝上（位於連接器頂端）。

+
... 安裝磁碟櫃、開啟電源、然後設定機櫃ID。
+
磁碟櫃模型的安裝指南_提供安裝磁碟櫃的詳細資訊。

+

NOTE: 您必須為磁碟櫃重新開機、並讓整個儲存系統內每個SAS磁碟櫃的機櫃ID保持唯一。

... 從堆疊中最後一個機櫃的IOM B連接埠拔下SAS纜線、然後將其重新連接至新機櫃中的相同連接埠。
+
此纜線的另一端仍連接至橋接器B

... 將新的機櫃IOM連接埠（IOM A和IOM B）連接至最後一個機櫃IOM連接埠（IOM A和IOM B）、以菊環鏈連接新的磁碟櫃。




+
磁碟櫃模型的安裝指南_提供有關菊環鏈式磁碟櫃的詳細資訊。

. 從系統主控台將磁碟機韌體更新至最新版本。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp下載：磁碟機韌體"]

+
.. 變更為進階權限等級：+「*設定-權限進階*」
+
當系統提示您繼續進入進階模式並查看進階模式提示字元（*>）時、您需要使用「* y*」來回應。

.. 從系統主控台將磁碟機韌體更新至最新版本：+「*儲存磁碟韌體更新*」
.. 返回管理權限等級：+`* set -priv榮幸admin*
.. 在其他控制器上重複上述子步驟。


. 驗證MetroCluster 下列項目中的功能：ONTAP
+
.. 檢查系統是否具有多路徑：
+
‘*節點執行節點_norme-name_ sysconfig -A*’

.. 檢查兩個叢集上是否有任何健全狀況警示：+「*系統健全狀況警示顯示*」
.. 確認MetroCluster 此功能的組態、並確認操作模式正常：+「* MetroCluster 」「*」「show *」
.. 執行MetroCluster 功能不全：+「* MetroCluster 效能不全*」
.. 顯示MetroCluster 檢查結果：
+
《* MetroCluster 》*《*》《*》《*》《*》

.. 檢查交換器上是否有任何健全狀況警示（如果有）：
+
「*儲存交換器show *」

.. 執行Config Advisor
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp下載Config Advisor"]

.. 執行Config Advisor 完功能後、請檢閱工具的輸出結果、並依照輸出中的建議來解決發現的任何問題。


. 如果您要熱新增多個磁碟櫃、請針對要熱新增的每個磁碟櫃重複上述步驟。

