---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: 升級MetroCluster 靜態IP交換器上的韌體。 
---
= 升級MetroCluster 韌體至靜態IP交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要在MetroCluster 一個無法更新的IP交換器上升級韌體。

.關於這項工作
您必須在每個交換器上連續重複此工作。

link:enable-console-logging-before-maintenance.html["啟用主控台記錄"] 在執行此工作之前。

[[step_1_fw_upgrade]]
.步驟
. 檢查組態的健全狀況。
+
.. 檢查MetroCluster 每個叢集上的功能是否已設定且處於正常模式：
+
《不看》MetroCluster

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 檢查每個節點是否已啟用鏡射：
+
「不一樣的秀」MetroCluster

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. 檢查MetroCluster 這些元件是否健全：
+
《不一樣的跑程》MetroCluster

+
[listing]
----
cluster_A::*> metrocluster check run
----
+
此作業會在背景執行。

.. 之後 `metrocluster check run` 作業完成、執行：
+
《不一樣的表演》MetroCluster

+
大約五分鐘後、會顯示下列結果：

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. 檢查是否沒有健全狀況警示：
+
「系統健全狀況警示顯示」



. 在第一台交換器上安裝軟體。
+

NOTE: 您必須依照下列順序在交換器上安裝交換器軟體：switch_a_1、switch_b_1、switch_a_2、switch_b_2。

+
根據交換機類型是 Broadcom 、 Cisco 還是 NVIDIA 、請依照相關主題中的步驟安裝交換器軟體：

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["下載並安裝 Broadcom 交換器 EFOS 軟體"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["下載並安裝 Cisco 交換器 NX-OS 軟體"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["下載並安裝 NVIDIA SN2100 交換器 Cumulus 軟體"]


. 針對每個交換器重複上述步驟。
. 重複 <<step_1_fw_upgrade,步驟1.>> 檢查組態的健全狀況。

