---
permalink: install-stretch/concept_required_mcc_components_and_naming_conventions_for_two_node_bridge_attached_stretch_configurations_mcc.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, required, hardware, components, naming, conventions, two, node, stretch, bridge 
summary: 規劃MetroCluster 您的不完整組態時、您必須瞭解所需及支援的軟硬體元件。為了方便且清楚、您也應該瞭解整個文件範例中元件的命名慣例。例如、一個站台稱為站台A、另一個站台稱為站台B 
---
= 雙節點橋接延伸組態所需MetroCluster 的零件和命名慣例
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
規劃MetroCluster 您的不完整組態時、您必須瞭解所需及支援的軟硬體元件。為了方便且清楚、您也應該瞭解整個文件範例中元件的命名慣例。例如、一個站台稱為站台A、另一個站台稱為站台B



== 支援的軟體與硬體

硬體與軟體必須支援MetroCluster 以利支援不支援使用。

https://["NetApp Hardware Universe"]

使用AFF 不完整的系統時、MetroCluster 必須將不完整組態中的所有控制器模組設定為AFF 不完整的系統。



== 硬體備援功能MetroCluster

由於在整個過程中使用了硬體備援、MetroCluster 因此每個站台都有兩個元件。站台會任意指派字母A和B、而個別元件則會任意指派數字1和2。



== 需要兩ONTAP 個單節點的叢集

連接橋接的Stretch MetroCluster 等位配置需要兩ONTAP 個單節點的叢集。

命名必須在MetroCluster 整個功能區組態中是唯一的。

範例名稱：

* 站台A：叢集_A
* 站台B：叢集B




== 需要兩個儲存控制器模組

連接橋接的Stretch MetroCluster 位向組態需要兩個儲存控制器模組。

控制器必須符合下列要求：

* 命名必須在MetroCluster 整個功能區組態中是唯一的。
* 所有採用此功能的控制器模組MetroCluster 都必須執行相同版本ONTAP 的功能。
* DR群組中的所有控制器模組都必須為相同的機型。
* DR群組中的所有控制器模組都必須使用相同的FC-VI組態。
+
某些控制器模組支援兩種FC-VI連線選項：

+
** 內建FC-VI連接埠
** 插槽1中的FC-VI卡
+
不支援混合使用內建FC-VI連接埠的控制器模組、以及使用附加FC-VI卡的控制器模組。例如、如果某個節點使用內建的FC-VI組態、則DR群組中的所有其他節點也必須使用內建的FC-VI組態。





範例名稱：

* 站台A：控制器_a_1
* 站台B：控制器_B_1




== FC至SAS橋接器的需求

連接橋接的Stretch MetroCluster Setch組態需要在每個站台上使用兩個以上的FC對SAS橋接器。

這些橋接器會將SAS磁碟櫃連接至控制器模組。


NOTE: 在執行ONTAP 支援升級版本的組態中、不支援使用FibreBridge 6500N橋接器。

* 最多可支援四個SAS堆疊的FIBreBridge 7600N和7500N橋接器。
* FibreBridge 6500N橋接器僅支援一個SAS堆疊。
* 每個堆疊可以使用不同的IOM機型、但堆疊內的所有磁碟櫃都必須使用相同的機型。
+
支援的IOM機型取決於ONTAP 您執行的版本。

* 命名必須在MetroCluster 整個功能區組態中是唯一的。


本程序中所使用的建議名稱可識別橋接器所連接的控制器模組和連接埠。

範例名稱：

* 站台A：
+
** bridge_a_1_`_port-number_``
** bridge_a_2_`_port-number_``


* 站台B：
+
** bridge_B_1_`_port-number_``
** bridge_B_2_`_port-number_``






== 至少需要四個SAS磁碟櫃（建議）

橋接式延伸MetroCluster 支援組態至少需要兩個SAS磁碟櫃。不過、每個站台建議使用兩個磁碟櫃、以每個磁碟櫃為單位、總共四個SAS磁碟櫃。

每個站台至少支援一個機櫃。

範例名稱：

* 站台A：
+
** 機櫃_a_1_1
** 機櫃_a_1_2


* 站台B：
+
** 機櫃_B_1_1
** 機櫃_B_1_2






== 在堆疊中混合IOM12和IOM 6模組

您的ONTAP 版本必須支援機櫃混合。請參閱互通性對照表工具IMT （英文）、瞭解您的ONTAP 版本的支援機櫃混合。 https://["NetApp互通性"^]

如需機櫃混合的詳細資訊、請參閱： https://["將含有IOM12模組的熱新增磁碟櫃放到具有IOM6模組的磁碟櫃堆疊中"^]
